My FreeRTOS Project: inc/Bluetooth.h File Reference
Bluetooth.h File Reference
Asociaciones a Bluetooth.c.
#include "RegsLPC1769.h"
Macros
#define ResetHC05 1,4
#define ATHC05 1,0
#define STATE_PIN 1,1
#define NAME "AT+NAME=TD2-G8\r\n"
#define PASSWORD "AT+PSWD=1235\r\n"
#define ROL "AT+ROLE=0\r\n"
Functions
void IntToAscii (uint32_t BaudRate, uint8_t *buffer, uint32_t lenght, uint32_t n)
Traduce el Baudrate.
void MandarAT (uint8_t *buff)
Envia comando AT.
void ResetearHC05 ()
Reinicia el modulo HC05.
void ConfigPinBluetooth ()
Configura hardware asociado al modulo HC05.
void Bluetooth_Init (uint32_t)
Inicializa sofware asociado al modulo HC05.
void TestPointInitBT (void)
Funcion de testeo de bluetooth en hardware.
Detailed Description
Asociaciones a Bluetooth.c.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file Bluetooth.h.
Macro Definition Documentation
ATHC05
#define ATHC05 1,0
Definition at line 21 of file Bluetooth.h.
Referenced by Bluetooth_Init(), and ConfigPinBluetooth().
NAME
#define NAME "AT+NAME=TD2-G8\r\n"
Definition at line 25 of file Bluetooth.h.
Referenced by Bluetooth_Init().
PASSWORD
#define PASSWORD "AT+PSWD=1235\r\n"
Definition at line 26 of file Bluetooth.h.
Referenced by Bluetooth_Init().
ResetHC05
#define ResetHC05 1,4
Definition at line 20 of file Bluetooth.h.
Referenced by ConfigPinBluetooth(), and ResetearHC05().
ROL
#define ROL "AT+ROLE=0\r\n"
Definition at line 27 of file Bluetooth.h.
Referenced by Bluetooth_Init().
STATE_PIN
#define STATE_PIN 1,1
Definition at line 22 of file Bluetooth.h.
Referenced by SerialManager(), and TestPointInitBT().
Function Documentation
Bluetooth_Init()
void Bluetooth_Init (uint32_t BaudRate)
Inicializa sofware asociado al modulo HC05.
Parameters
BaudRate
Definition at line 89 of file Bluetooth.c.
References ATHC05, ConfigPinBluetooth(), IntToAscii(), MandarAT(), NAME, PASSWORD, ResetearHC05(), ROL, SetPIN(), and UART_Init().
ConfigPinBluetooth()
void ConfigPinBluetooth ()
Configura hardware asociado al modulo HC05.
Definition at line 77 of file Bluetooth.c.
References ATHC05, ResetHC05, SetDIR(), and SetPINSEL().
Referenced by Bluetooth_Init().
IntToAscii()
void IntToAscii (uint32_t BaudRate, uint8_t * buffer, uint32_t lenght, uint32_t n)
Traduce el Baudrate.
Parameters
BaudRate Variable de baudrate
buffer Buffer pointer
lenght Longitud dle buffer
n Indice
Definition at line 30 of file Bluetooth.c.
Referenced by Bluetooth_Init().
MandarAT()
void MandarAT (uint8_t * buff)
Envia comando AT.
Parameters
buff Puntero al dato a enviar.
Definition at line 53 of file Bluetooth.c.
References Serial_PushTx().
Referenced by Bluetooth_Init().
ResetearHC05()
void ResetearHC05 ()
Reinicia el modulo HC05.
Definition at line 65 of file Bluetooth.c.
References ResetHC05, and SetPIN().
Referenced by Bluetooth_Init().
TestPointInitBT()
void TestPointInitBT (void)
Funcion de testeo de bluetooth en hardware.
Definition at line 136 of file Bluetooth.c.
References SetDIR(), SetPINSEL(), and STATE_PIN.
Referenced by UART_Init().