My FreeRTOS Project: Drivers/Bluetooth.c File Reference
Bluetooth.c File Reference
Asociados a la comunicacion Bluetooth.
#include "GPIOLPC1769.h"
#include "Serial.h"
#include "Bluetooth.h"
#include "PinoutConfigLPC1769.h"
Functions
void IntToAscii (uint32_t BaudRate, uint8_t *buffer, uint32_t lenght, uint32_t n)
Traduce el Baudrate.
void MandarAT (uint8_t *buff)
Envia comando AT.
void ResetearHC05 ()
Reinicia el modulo HC05.
void ConfigPinBluetooth ()
Configura hardware asociado al modulo HC05.
void Bluetooth_Init (uint32_t BaudRate)
Inicializa sofware asociado al modulo HC05.
void TestPointInitBT (void)
Funcion de testeo de bluetooth en hardware.
Detailed Description
Asociados a la comunicacion Bluetooth.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file Bluetooth.c.
Function Documentation
Bluetooth_Init()
void Bluetooth_Init (uint32_t BaudRate)
Inicializa sofware asociado al modulo HC05.
Parameters
BaudRate
Definition at line 89 of file Bluetooth.c.
References ATHC05, ConfigPinBluetooth(), IntToAscii(), MandarAT(), NAME, PASSWORD, ResetearHC05(), ROL, SetPIN(), and UART_Init().
ConfigPinBluetooth()
void ConfigPinBluetooth ()
Configura hardware asociado al modulo HC05.
Definition at line 77 of file Bluetooth.c.
References ATHC05, ResetHC05, SetDIR(), and SetPINSEL().
Referenced by Bluetooth_Init().
IntToAscii()
void IntToAscii (uint32_t BaudRate, uint8_t * buffer, uint32_t lenght, uint32_t n)
Traduce el Baudrate.
Parameters
BaudRate Variable de baudrate
buffer Buffer pointer
lenght Longitud dle buffer
n Indice
Definition at line 30 of file Bluetooth.c.
Referenced by Bluetooth_Init().
MandarAT()
void MandarAT (uint8_t * buff)
Envia comando AT.
Parameters
buff Puntero al dato a enviar.
Definition at line 53 of file Bluetooth.c.
References Serial_PushTx().
Referenced by Bluetooth_Init().
ResetearHC05()
void ResetearHC05 ()
Reinicia el modulo HC05.
Definition at line 65 of file Bluetooth.c.
References ResetHC05, and SetPIN().
Referenced by Bluetooth_Init().
TestPointInitBT()
void TestPointInitBT (void)
Funcion de testeo de bluetooth en hardware.
Definition at line 136 of file Bluetooth.c.
References SetDIR(), SetPINSEL(), and STATE_PIN.
Referenced by UART_Init().