My FreeRTOS Project: src/cr_startup_lpc175x_6x.c File Reference
cr_startup_lpc175x_6x.c File Reference
Macros
#define WEAK __attribute__ ((weak))
#define ALIAS(f) __attribute__ ((weak, alias (#f)))
Functions
void ResetISR (void)
WEAK void NMI_Handler (void)
WEAK void HardFault_Handler (void)
WEAK void MemManage_Handler (void)
WEAK void BusFault_Handler (void)
WEAK void UsageFault_Handler (void)
WEAK void SVC_Handler (void)
WEAK void DebugMon_Handler (void)
WEAK void PendSV_Handler (void)
WEAK void SysTick_Handler (void)
WEAK void IntDefaultHandler (void)
void WDT_IRQHandler (void TIMER0_IRQHandler() ALIAS(IntDefaultHandler) void)
__attribute__ ((section(".after_vectors")))
Variables
unsigned int __data_section_table
unsigned int __data_section_table_end
unsigned int __bss_section_table
unsigned int __bss_section_table_end
Macro Definition Documentation
ALIAS
#define ALIAS (f) __attribute__ ((weak, alias (#f)))
Definition at line 48 of file cr_startup_lpc175x_6x.c.
WEAK
#define WEAK __attribute__ ((weak))
Definition at line 47 of file cr_startup_lpc175x_6x.c.
Function Documentation
__attribute__()
__attribute__ ((section(".after_vectors")))
Definition at line 225 of file cr_startup_lpc175x_6x.c.
References __bss_section_table, __bss_section_table_end, __data_section_table, __data_section_table_end, BusFault_Handler(), DebugMon_Handler(), HardFault_Handler(), IntDefaultHandler(), main(), MemManage_Handler(), NMI_Handler(), PendSV_Handler(), ResetISR(), SVC_Handler(), SystemInit(), SysTick_Handler(), and UsageFault_Handler().
BusFault_Handler()
WEAK void BusFault_Handler (void)
Referenced by __attribute__().
DebugMon_Handler()
WEAK void DebugMon_Handler (void)
Referenced by __attribute__().
HardFault_Handler()
WEAK void HardFault_Handler (void)
Referenced by __attribute__().
IntDefaultHandler()
WEAK void IntDefaultHandler (void)
Referenced by __attribute__().
MemManage_Handler()
WEAK void MemManage_Handler (void)
Referenced by __attribute__().
NMI_Handler()
WEAK void NMI_Handler (void)
Referenced by __attribute__().
PendSV_Handler()
WEAK void PendSV_Handler (void)
Referenced by __attribute__().
ResetISR()
void ResetISR (void)
Referenced by __attribute__().
SVC_Handler()
WEAK void SVC_Handler (void)
Referenced by __attribute__().
SysTick_Handler()
WEAK void SysTick_Handler (void)
Referenced by __attribute__().
UsageFault_Handler()
WEAK void UsageFault_Handler (void)
Referenced by __attribute__().
WDT_IRQHandler()
void WDT_IRQHandler (void TIMER0_IRQHandler() ALIAS(IntDefaultHandler) void)
Definition at line 88 of file cr_startup_lpc175x_6x.c.
Variable Documentation
__bss_section_table
unsigned int __bss_section_table
Referenced by __attribute__().
__bss_section_table_end
unsigned int __bss_section_table_end
Referenced by __attribute__().
__data_section_table
unsigned int __data_section_table
Referenced by __attribute__().
__data_section_table_end
unsigned int __data_section_table_end
Referenced by __attribute__().