My FreeRTOS Project: spi/inc/diskio.h File Reference
diskio.h File Reference
#include "integer.h"
Macros
#define _USE_WRITE 1 /* 1: Enable disk_write function */
#define _USE_IOCTL 1 /* 1: Enable disk_ioctl fucntion */
#define STA_NOINIT 0x01 /* Drive not initialized */
#define STA_NODISK 0x02 /* No medium in the drive */
#define STA_PROTECT 0x04 /* Write protected */
#define CTRL_SYNC 0 /* Flush disk cache (for write functions) */
#define GET_SECTOR_COUNT 1 /* Get media size (for only f_mkfs()) */
#define GET_SECTOR_SIZE 2 /* Get sector size (for multiple sector size (_MAX_SS >= 1024)) */
#define GET_BLOCK_SIZE 3 /* Get erase block size (for only f_mkfs()) */
#define CTRL_ERASE_SECTOR 4 /* Force erased a block of sectors (for only _USE_ERASE) */
#define CTRL_POWER 5 /* Get/Set power status */
#define CTRL_LOCK 6 /* Lock/Unlock media removal */
#define CTRL_EJECT 7 /* Eject media */
#define CTRL_FORMAT 8 /* Create physical format on the media */
#define MMC_GET_TYPE 10 /* Get card type */
#define MMC_GET_CSD 11 /* Get CSD */
#define MMC_GET_CID 12 /* Get CID */
#define MMC_GET_OCR 13 /* Get OCR */
#define MMC_GET_SDSTAT 14 /* Get SD status */
#define ATA_GET_REV 20 /* Get F/W revision */
#define ATA_GET_MODEL 21 /* Get model name */
#define ATA_GET_SN 22 /* Get serial number */
#define CT_MMC 0x01 /* MMC ver 3 */
#define CT_SD1 0x02 /* SD ver 1 */
#define CT_SD2 0x04 /* SD ver 2 */
#define CT_SDC (CT_SD1|CT_SD2) /* SD */
#define CT_BLOCK 0x08 /* Block addressing */
Typedefs
typedef BYTE DSTATUS
Enumerations
enum DRESULT {
RES_OK = 0, RES_ERROR, RES_WRPRT, RES_NOTRDY,
RES_PARERR
}
Functions
DSTATUS disk_initialize (BYTE)
DSTATUS disk_status (BYTE)
DRESULT disk_read (BYTE, BYTE *, DWORD, UINT)
DRESULT disk_write (BYTE, const BYTE *, DWORD, UINT)
DRESULT disk_ioctl (BYTE, BYTE, void *)
Macro Definition Documentation
_USE_IOCTL
#define _USE_IOCTL 1 /* 1: Enable disk_ioctl fucntion */
Definition at line 13 of file diskio.h.
_USE_WRITE
#define _USE_WRITE 1 /* 1: Enable disk_write function */
Definition at line 12 of file diskio.h.
ATA_GET_MODEL
#define ATA_GET_MODEL 21 /* Get model name */
Definition at line 72 of file diskio.h.
ATA_GET_REV
#define ATA_GET_REV 20 /* Get F/W revision */
Definition at line 71 of file diskio.h.
ATA_GET_SN
#define ATA_GET_SN 22 /* Get serial number */
Definition at line 73 of file diskio.h.
CT_BLOCK
#define CT_BLOCK 0x08 /* Block addressing */
Definition at line 81 of file diskio.h.
Referenced by disk_initialize(), disk_read(), and disk_write().
CT_MMC
#define CT_MMC 0x01 /* MMC ver 3 */
Definition at line 77 of file diskio.h.
Referenced by disk_initialize().
CT_SD1
#define CT_SD1 0x02 /* SD ver 1 */
Definition at line 78 of file diskio.h.
Referenced by disk_initialize(), and disk_write().
CT_SD2
#define CT_SD2 0x04 /* SD ver 2 */
Definition at line 79 of file diskio.h.
Referenced by disk_initialize(), and disk_write().
CT_SDC
#define CT_SDC (CT_SD1|CT_SD2) /* SD */
Definition at line 80 of file diskio.h.
Referenced by disk_write().
CTRL_EJECT
#define CTRL_EJECT 7 /* Eject media */
Definition at line 60 of file diskio.h.
CTRL_ERASE_SECTOR
#define CTRL_ERASE_SECTOR 4 /* Force erased a block of sectors (for only _USE_ERASE) */
Definition at line 55 of file diskio.h.
CTRL_FORMAT
#define CTRL_FORMAT 8 /* Create physical format on the media */
Definition at line 61 of file diskio.h.
CTRL_LOCK
#define CTRL_LOCK 6 /* Lock/Unlock media removal */
Definition at line 59 of file diskio.h.
CTRL_POWER
#define CTRL_POWER 5 /* Get/Set power status */
Definition at line 58 of file diskio.h.
Referenced by disk_write().
CTRL_SYNC
#define CTRL_SYNC 0 /* Flush disk cache (for write functions) */
Definition at line 51 of file diskio.h.
Referenced by disk_write(), f_rename(), and sync_fs().
GET_BLOCK_SIZE
#define GET_BLOCK_SIZE 3 /* Get erase block size (for only f_mkfs()) */
Definition at line 54 of file diskio.h.
Referenced by disk_write(), and f_rename().
GET_SECTOR_COUNT
#define GET_SECTOR_COUNT 1 /* Get media size (for only f_mkfs()) */
Definition at line 52 of file diskio.h.
Referenced by disk_write(), and f_rename().
GET_SECTOR_SIZE
#define GET_SECTOR_SIZE 2 /* Get sector size (for multiple sector size (_MAX_SS >= 1024)) */
Definition at line 53 of file diskio.h.
Referenced by disk_write(), f_rename(), and find_volume().
MMC_GET_CID
#define MMC_GET_CID 12 /* Get CID */
Definition at line 66 of file diskio.h.
Referenced by disk_write().
MMC_GET_CSD
#define MMC_GET_CSD 11 /* Get CSD */
Definition at line 65 of file diskio.h.
Referenced by disk_write().
MMC_GET_OCR
#define MMC_GET_OCR 13 /* Get OCR */
Definition at line 67 of file diskio.h.
Referenced by disk_write().
MMC_GET_SDSTAT
#define MMC_GET_SDSTAT 14 /* Get SD status */
Definition at line 68 of file diskio.h.
Referenced by disk_write().
MMC_GET_TYPE
#define MMC_GET_TYPE 10 /* Get card type */
Definition at line 64 of file diskio.h.
Referenced by disk_write().
STA_NODISK
#define STA_NODISK 0x02 /* No medium in the drive */
Definition at line 44 of file diskio.h.
Referenced by disk_initialize(), and disk_timerproc().
STA_NOINIT
#define STA_NOINIT 0x01 /* Drive not initialized */
Definition at line 43 of file diskio.h.
Referenced by disk_initialize(), disk_read(), disk_status(), disk_timerproc(), disk_write(), f_rename(), find_volume(), and validate().
STA_PROTECT
#define STA_PROTECT 0x04 /* Write protected */
Definition at line 45 of file diskio.h.
Referenced by disk_write(), f_rename(), and find_volume().
Typedef Documentation
DSTATUS
typedef BYTE DSTATUS
Definition at line 19 of file diskio.h.
Enumeration Type Documentation
DRESULT
enum DRESULT
Enumerator
RES_OK
RES_ERROR
RES_WRPRT
RES_NOTRDY
RES_PARERR
Definition at line 22 of file diskio.h.
Function Documentation
disk_initialize()
DSTATUS disk_initialize (BYTE)
Definition at line 319 of file mmc.c.
References ACMD41, CardType, CMD0, CMD1, CMD16, CMD58, CMD8, CT_BLOCK, CT_MMC, CT_SD1, CT_SD2, deselect(), FCLK_FAST, FCLK_SLOW, power_off(), power_on(), rcvr_spi(), send_cmd(), STA_NODISK, STA_NOINIT, Stat, and Timer1.
Referenced by f_rename(), and find_volume().
disk_ioctl()
DRESULT disk_ioctl (BYTE , BYTE , void *)
Referenced by disk_write(), f_rename(), find_volume(), remove_chain(), and sync_fs().
disk_read()
DRESULT disk_read (BYTE , BYTE * , DWORD , UINT)
Definition at line 388 of file mmc.c.
References CardType, CMD12, CMD17, CMD18, CT_BLOCK, deselect(), rcvr_datablock(), RES_ERROR, RES_NOTRDY, RES_OK, RES_PARERR, send_cmd(), STA_NOINIT, and Stat.
Referenced by f_lseek(), f_open(), f_read(), f_rename(), f_write(), and move_window().
disk_status()
DSTATUS disk_status (BYTE)
Definition at line 374 of file mmc.c.
References STA_NOINIT, and Stat.
Referenced by find_volume(), and validate().
disk_write()
DRESULT disk_write (BYTE , const BYTE * , DWORD , UINT)
Definition at line 426 of file mmc.c.
References ACMD13, ACMD23, CardType, chk_power(), CMD10, CMD24, CMD25, CMD58, CMD9, CT_BLOCK, CT_SD1, CT_SD2, CT_SDC, CTRL_POWER, CTRL_SYNC, deselect(), disk_ioctl(), GET_BLOCK_SIZE, GET_SECTOR_COUNT, GET_SECTOR_SIZE, MMC_GET_CID, MMC_GET_CSD, MMC_GET_OCR, MMC_GET_SDSTAT, MMC_GET_TYPE, power_off(), power_on(), rcvr_datablock(), rcvr_spi(), RES_ERROR, RES_NOTRDY, RES_OK, RES_PARERR, RES_WRPRT, select_(), send_cmd(), STA_NOINIT, STA_PROTECT, Stat, and xmit_datablock().
Referenced by f_lseek(), f_read(), f_rename(), f_sync(), f_truncate(), f_write(), sync_fs(), and sync_window().