My FreeRTOS Project: Applications/Display.c File Reference
Display.c File Reference
Funciones asociadas a la entidad del proyecto.
#include "Display.h"
#include "RegsLPC1769.h"
#include "myTimers.h"
#include "GPIOLPC1769.h"
#include "PinoutConfigLPC1769.h"
#include "Shifter.h"
#include "HallSensor.h"
#include "InterruptHandler.h"
#include "StatusHandler.h"
#include "Serial.h"
#include "myTasks.h"
Functions
void DisplaySend (Shifter_t *This_Shifter)
Inicia la sencuencia de impresion.
void DisplayStop (void)
Detiene la sencuencia de impresion.
void PrintStart (Shifter_t *This_Shifter)
Indica el inicio de la secuencia de impresion.
void PrintStop (void)
Indica el final de la secuencia de impresion.
void CargaData (Shifter_t *This_Shifter)
Funcion de traduccion de buffers de datos.
void Descomprimir (void)
Funcion de descompresion.
void Stream (void)
Aviso de refresco a la APP.
void TestPointInitGeneral (void)
Inicializa Test Points en Hardware.
Detailed Description
Funciones asociadas a la entidad del proyecto.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file Display.c.
Function Documentation
CargaData()
void CargaData (Shifter_t * This_Shifter)
Funcion de traduccion de buffers de datos.
Aplica una transformacion a los datos recibidos descomprimidos de la aplicacion de PC en un tipo de dato unsigned int y aplica logica de ordenamiento para dejar los datos listos para ser interpretados por el hardware en un Shifter_t.
Parameters
This_Shifter Puntero a donde alojar el dato post-procesado.
Definition at line 88 of file Display.c.
References Buffer::Buffers, Shifter::Data, Shifter::DataSource, FILAS_SHIFTERS, Image, MYIR, N_CIR, N_LEDS, and PhaseRefresh.
Referenced by tCargaData().
Descomprimir()
void Descomprimir (void)
Funcion de descompresion.
Toma el dato post-procesado por el algoritmo lz4 y lo guarda en el buffer de la matriz imagen completa. Por ultimo levanta el status flag indicando que esta listo para recibir y procesar otro dato.
Definition at line 156 of file Display.c.
References Buffer::Buffer_Index, Buffer::Buffers, Image, IW, LZ4_decompress_safe_usingDict(), MYIR, N_PIX, ON, Status_Flags, STREAM, Buffer::Stream_Buffer, and Buffer::Stream_Size.
Referenced by tDescomprimir().
DisplaySend()
void DisplaySend (Shifter_t * This_Shifter)
Inicia la sencuencia de impresion.
Se abstrajo de PrintStart para sumar una capa de nivel al programa.
Parameters
This_Shifter Puntero a la estructura
Definition at line 37 of file Display.c.
References PrintStart().
Referenced by tInit().
DisplayStop()
void DisplayStop (void)
Detiene la sencuencia de impresion.
Se abstrajo de PrintStop para sumar una capa de nivel al programa.
Definition at line 47 of file Display.c.
References PrintStop().
Referenced by tInit().
PrintStart()
void PrintStart (Shifter_t * This_Shifter)
Indica el inicio de la secuencia de impresion.
Reinicia el indice de PWM, arranca el timer 0 encargado del shifteo y coloca los bits menos significativos (que es de donde parte la secuencia) en los pines fisicos de hardware.
Parameters
This_Shifter Puntero a la estructura
Definition at line 58 of file Display.c.
References CE, D0_PIN, D1_PIN, D2_PIN, D3_PIN, Shifter::Data, MYCR, PwmStateIndex, SetPIN(), and T0TCR.
Referenced by DisplaySend().
PrintStop()
void PrintStop (void)
Indica el final de la secuencia de impresion.
Para y reinicia el timer 0 y el indice de shifteo de la informacion.
Definition at line 73 of file Display.c.
References CE, MYCR, ShiftCounter, and T0TCR.
Referenced by DisplayStop().
Stream()
void Stream (void)
Aviso de refresco a la APP.
Avisa a la aplicacion de pc, una vez recibido el dato, que puede enviar uno nuevo.
Definition at line 176 of file Display.c.
References ON, Serial_PushTx(), Status_Flags, and STREAM.
Referenced by tPeriodic().
TestPointInitGeneral()
void TestPointInitGeneral (void)
Inicializa Test Points en Hardware.
Declaro todos los test points genericos del hardware y les grabo una secuencia para medir.
Definition at line 191 of file Display.c.
References SetDIR(), SetPIN(), SetPINSEL(), TPGPIO1, TPGPIO2, TPGPIO3, TPGPIO4, and TPGPIO5.
Referenced by Inicializar().