My FreeRTOS Project: spi/src/ff.c File Reference
ff.c File Reference
#include "ff.h"
#include "diskio.h"
Macros
#define ABORT(fs, res) { fp->err = (BYTE)(res); LEAVE_FF(fs, res); }
#define ENTER_FF(fs)
#define LEAVE_FF(fs, res) return res
#define SS(fs) ((UINT)_MAX_SS) /* Fixed sector size */
#define GET_FATTIME() get_fattime()
#define IsUpper(c) (((c)>='A')&&((c)<='Z'))
#define IsLower(c) (((c)>='a')&&((c)<='z'))
#define IsDigit(c) (((c)>='0')&&((c)<='9'))
#define IsDBCS1(c) 0
#define IsDBCS2(c) 0
#define AM_VOL 0x08 /* Volume label */
#define AM_LFN 0x0F /* LFN entry */
#define AM_MASK 0x3F /* Mask of defined bits */
#define FA_SEEKEND 0x20 /* Seek to end of the file on file open */
#define FA_MODIFIED 0x40 /* File has been modified */
#define FA_DIRTY 0x80 /* FIL.buf[] needs to be written-back */
#define NSFLAG 11 /* Index of name status byte in fn[] */
#define NS_LOSS 0x01 /* Out of 8.3 format */
#define NS_LFN 0x02 /* Force to create LFN entry */
#define NS_LAST 0x04 /* Last segment */
#define NS_BODY 0x08 /* Lower case flag (body) */
#define NS_EXT 0x10 /* Lower case flag (ext) */
#define NS_DOT 0x20 /* Dot entry */
#define NS_NOLFN 0x40 /* Do not find LFN */
#define NS_NONAME 0x80 /* Not followed */
#define MAX_FAT12 0xFF5 /* Maximum number of FAT12 clusters */
#define MAX_FAT16 0xFFF5 /* Maximum number of FAT16 clusters */
#define MAX_FAT32 0xFFFFFF5 /* Maximum number of FAT32 clusters */
#define MAX_EXFAT 0x7FFFFFFD /* Maximum number of exFAT clusters (limited by implementation) */
#define MAX_DIR 0x200000 /* Maximum size of FAT directory */
#define MAX_DIR_EX 0x10000000 /* Maximum size of exFAT directory */
#define BS_JmpBoot 0 /* x86 jump instruction (3-byte) */
#define BS_OEMName 3 /* OEM name (8-byte) */
#define BPB_BytsPerSec 11 /* Sector size [byte] (WORD) */
#define BPB_SecPerClus 13 /* Cluster size [sector] (BYTE) */
#define BPB_RsvdSecCnt 14 /* Size of reserved area [sector] (WORD) */
#define BPB_NumFATs 16 /* Number of FATs (BYTE) */
#define BPB_RootEntCnt 17 /* Size of root directory area for FAT12/16 [entry] (WORD) */
#define BPB_TotSec16 19 /* Volume size (16-bit) [sector] (WORD) */
#define BPB_Media 21 /* Media descriptor (BYTE) */
#define BPB_FATSz16 22 /* FAT size (16-bit) [sector] (WORD) */
#define BPB_SecPerTrk 24 /* Track size for int13h [sector] (WORD) */
#define BPB_NumHeads 26 /* Number of heads for int13h (WORD) */
#define BPB_HiddSec 28 /* Volume offset from top of the drive (DWORD) */
#define BPB_TotSec32 32 /* Volume size (32-bit) [sector] (DWORD) */
#define BS_DrvNum 36 /* Physical drive number for int13h (BYTE) */
#define BS_NTres 37 /* Error flag (BYTE) */
#define BS_BootSig 38 /* Extended boot signature (BYTE) */
#define BS_VolID 39 /* Volume serial number (DWORD) */
#define BS_VolLab 43 /* Volume label string (8-byte) */
#define BS_FilSysType 54 /* File system type string (8-byte) */
#define BS_BootCode 62 /* Boot code (448-byte) */
#define BPB_FATSz32 36 /* FAT32: FAT size [sector] (DWORD) */
#define BPB_ExtFlags32 40 /* FAT32: Extended flags (WORD) */
#define BPB_FSVer32 42 /* FAT32: File system version (WORD) */
#define BPB_RootClus32 44 /* FAT32: Root directory cluster (DWORD) */
#define BPB_FSInfo32 48 /* FAT32: Offset of FSINFO sector (WORD) */
#define BPB_BkBootSec32 50 /* FAT32: Offset of backup boot sector (WORD) */
#define BS_DrvNum32 64 /* FAT32: Physical drive number for int13h (BYTE) */
#define BS_NTres32 65 /* FAT32: Error flag (BYTE) */
#define BS_BootSig32 66 /* FAT32: Extended boot signature (BYTE) */
#define BS_VolID32 67 /* FAT32: Volume serial number (DWORD) */
#define BS_VolLab32 71 /* FAT32: Volume label string (8-byte) */
#define BS_FilSysType32 82 /* FAT32: File system type string (8-byte) */
#define BS_BootCode32 90 /* FAT32: Boot code (420-byte) */
#define BPB_ZeroedEx 11 /* exFAT: MBZ field (53-byte) */
#define BPB_VolOfsEx 64 /* exFAT: Volume offset from top of the drive [sector] (QWORD) */
#define BPB_TotSecEx 72 /* exFAT: Volume size [sector] (QWORD) */
#define BPB_FatOfsEx 80 /* exFAT: FAT offset from top of the volume [sector] (DWORD) */
#define BPB_FatSzEx 84 /* exFAT: FAT size [sector] (DWORD) */
#define BPB_DataOfsEx 88 /* exFAT: Data offset from top of the volume [sector] (DWORD) */
#define BPB_NumClusEx 92 /* exFAT: Number of clusters (DWORD) */
#define BPB_RootClusEx 96 /* exFAT: Root directory cluster (DWORD) */
#define BPB_VolIDEx 100 /* exFAT: Volume serial number (DWORD) */
#define BPB_FSVerEx 104 /* exFAT: File system version (WORD) */
#define BPB_VolFlagEx 106 /* exFAT: Volume flags (BYTE) */
#define BPB_ActFatEx 107 /* exFAT: Active FAT flags (BYTE) */
#define BPB_BytsPerSecEx 108 /* exFAT: Log2 of sector size in byte (BYTE) */
#define BPB_SecPerClusEx 109 /* exFAT: Log2 of cluster size in sector (BYTE) */
#define BPB_NumFATsEx 110 /* exFAT: Number of FATs (BYTE) */
#define BPB_DrvNumEx 111 /* exFAT: Physical drive number for int13h (BYTE) */
#define BPB_PercInUseEx 112 /* exFAT: Percent in use (BYTE) */
#define BPB_RsvdEx 113 /* exFAT: Reserved (7-byte) */
#define BS_BootCodeEx 120 /* exFAT: Boot code (390-byte) */
#define FSI_LeadSig 0 /* FAT32 FSI: Leading signature (DWORD) */
#define FSI_StrucSig 484 /* FAT32 FSI: Structure signature (DWORD) */
#define FSI_Free_Count 488 /* FAT32 FSI: Number of free clusters (DWORD) */
#define FSI_Nxt_Free 492 /* FAT32 FSI: Last allocated cluster (DWORD) */
#define MBR_Table 446 /* MBR: Offset of partition table in the MBR */
#define SZ_PTE 16 /* MBR: Size of a partition table entry */
#define PTE_Boot 0 /* MBR PTE: Boot indicator */
#define PTE_StHead 1 /* MBR PTE: Start head */
#define PTE_StSec 2 /* MBR PTE: Start sector */
#define PTE_StCyl 3 /* MBR PTE: Start cylinder */
#define PTE_System 4 /* MBR PTE: System ID */
#define PTE_EdHead 5 /* MBR PTE: End head */
#define PTE_EdSec 6 /* MBR PTE: End sector */
#define PTE_EdCyl 7 /* MBR PTE: End cylinder */
#define PTE_StLba 8 /* MBR PTE: Start in LBA */
#define PTE_SizLba 12 /* MBR PTE: Size in LBA */
#define BS_55AA 510 /* Signature word (WORD) */
#define DIR_Name 0 /* Short file name (11-byte) */
#define DIR_Attr 11 /* Attribute (BYTE) */
#define DIR_NTres 12 /* Lower case flag (BYTE) */
#define DIR_CrtTime10 13 /* Created time sub-second (BYTE) */
#define DIR_CrtTime 14 /* Created time (DWORD) */
#define DIR_LstAccDate 18 /* Last accessed date (WORD) */
#define DIR_FstClusHI 20 /* Higher 16-bit of first cluster (WORD) */
#define DIR_ModTime 22 /* Modified time (DWORD) */
#define DIR_FstClusLO 26 /* Lower 16-bit of first cluster (WORD) */
#define DIR_FileSize 28 /* File size (DWORD) */
#define LDIR_Ord 0 /* LFN entry order and LLE flag (BYTE) */
#define LDIR_Attr 11 /* LFN attribute (BYTE) */
#define LDIR_Type 12 /* LFN type (BYTE) */
#define LDIR_Chksum 13 /* Checksum of the SFN entry (BYTE) */
#define LDIR_FstClusLO 26 /* Must be zero (WORD) */
#define XDIR_Type 0 /* Type of exFAT directory entry (BYTE) */
#define XDIR_NumLabel 1 /* Number of volume label characters (BYTE) */
#define XDIR_Label 2 /* Volume label (11-WORD) */
#define XDIR_CaseSum 4 /* Sum of case conversion table (DWORD) */
#define XDIR_NumSec 1 /* Number of secondary entries (BYTE) */
#define XDIR_SetSum 2 /* Sum of the set of directory entries (WORD) */
#define XDIR_Attr 4 /* File attribute (WORD) */
#define XDIR_CrtTime 8 /* Created time (DWORD) */
#define XDIR_ModTime 12 /* Modified time (DWORD) */
#define XDIR_AccTime 16 /* Last accessed time (DWORD) */
#define XDIR_CrtTime10 20 /* Created time subsecond (BYTE) */
#define XDIR_ModTime10 21 /* Modified time subsecond (BYTE) */
#define XDIR_CrtTZ 22 /* Created timezone (BYTE) */
#define XDIR_ModTZ 23 /* Modified timezone (BYTE) */
#define XDIR_AccTZ 24 /* Last accessed timezone (BYTE) */
#define XDIR_GenFlags 33 /* Gneral secondary flags (WORD) */
#define XDIR_NumName 35 /* Number of file name characters (BYTE) */
#define XDIR_NameHash 36 /* Hash of file name (WORD) */
#define XDIR_ValidFileSize 40 /* Valid file size (QWORD) */
#define XDIR_FstClus 52 /* First cluster of the file data (DWORD) */
#define XDIR_FileSize 56 /* File/Directory size (QWORD) */
#define SZDIRE 32 /* Size of a directory entry */
#define LLEF 0x40 /* Last long entry flag in LDIR_Ord */
#define DDEM 0xE5 /* Deleted directory entry mark set to DIR_Name[0] */
#define RDDEM 0x05 /* Replacement of the character collides with DDEM */
#define DEF_NAMBUF
#define INIT_NAMBUF(fs)
#define FREE_NAMBUF()
Functions
static WORD ld_word (const BYTE *ptr)
static DWORD ld_dword (const BYTE *ptr)
static void st_word (BYTE *ptr, WORD val)
static void st_dword (BYTE *ptr, DWORD val)
static void mem_cpy (void *dst, const void *src, UINT cnt)
static void mem_set (void *dst, int val, UINT cnt)
static int mem_cmp (const void *dst, const void *src, UINT cnt)
static int chk_chr (const char *str, int chr)
static FRESULT sync_window (FATFS *fs)
static FRESULT move_window (FATFS *fs, DWORD sector)
static FRESULT sync_fs (FATFS *fs)
static DWORD clust2sect (FATFS *fs, DWORD clst)
static DWORD get_fat (_FDID *obj, DWORD clst)
static FRESULT put_fat (FATFS *fs, DWORD clst, DWORD val)
static FRESULT remove_chain (_FDID *obj, DWORD clst, DWORD pclst)
static DWORD create_chain (_FDID *obj, DWORD clst)
static FRESULT dir_sdi (DIR *dp, DWORD ofs)
static FRESULT dir_next (DIR *dp, int stretch)
static FRESULT dir_alloc (DIR *dp, UINT nent)
static DWORD ld_clust (FATFS *fs, const BYTE *dir)
static void st_clust (FATFS *fs, BYTE *dir, DWORD cl)
static FRESULT dir_read (DIR *dp, int vol)
static FRESULT dir_find (DIR *dp)
static FRESULT dir_register (DIR *dp)
static FRESULT dir_remove (DIR *dp)
static void get_fileinfo (DIR *dp, FILINFO *fno)
static FRESULT create_name (DIR *dp, const TCHAR **path)
static FRESULT follow_path (DIR *dp, const TCHAR *path)
static int get_ldnumber (const TCHAR **path)
static BYTE check_fs (FATFS *fs, DWORD sect)
static FRESULT find_volume (const TCHAR **path, FATFS **rfs, BYTE mode)
static FRESULT validate (void *dfp, FATFS **fs)
FRESULT f_mount (FATFS *fs, const TCHAR *path, BYTE opt)
FRESULT f_open (FIL *fp, const TCHAR *path, BYTE mode)
FRESULT f_read (FIL *fp, void *buff, UINT btr, UINT *br)
FRESULT f_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
FRESULT f_sync (FIL *fp)
FRESULT f_close (FIL *fp)
FRESULT f_lseek (FIL *fp, FSIZE_t ofs)
FRESULT f_opendir (DIR *dp, const TCHAR *path)
FRESULT f_closedir (DIR *dp)
FRESULT f_readdir (DIR *dp, FILINFO *fno)
FRESULT f_stat (const TCHAR *path, FILINFO *fno)
FRESULT f_getfree (const TCHAR *path, DWORD *nclst, FATFS **fatfs)
FRESULT f_truncate (FIL *fp)
FRESULT f_unlink (const TCHAR *path)
FRESULT f_mkdir (const TCHAR *path)
FRESULT f_rename (const TCHAR *path_old, const TCHAR *path_new)
Variables
static FATFS * FatFs [_VOLUMES]
static WORD Fsid
Macro Definition Documentation
ABORT
#define ABORT (fs, res) { fp->err = (BYTE)(res); LEAVE_FF(fs, res); }
Definition at line 36 of file ff.c.
Referenced by f_lseek(), f_read(), f_rename(), f_truncate(), and f_write().
AM_LFN
#define AM_LFN 0x0F /* LFN entry */
Definition at line 356 of file ff.c.
Referenced by dir_find(), dir_read(), and st_clust().
AM_MASK
#define AM_MASK 0x3F /* Mask of defined bits */
Definition at line 357 of file ff.c.
Referenced by dir_find(), and dir_read().
AM_VOL
#define AM_VOL 0x08 /* Volume label */
Definition at line 355 of file ff.c.
Referenced by dir_find(), dir_read(), and f_rename().
BPB_ActFatEx
#define BPB_ActFatEx 107 /* exFAT: Active FAT flags (BYTE) */
Definition at line 438 of file ff.c.
BPB_BkBootSec32
#define BPB_BkBootSec32 50 /* FAT32: Offset of backup boot sector (WORD) */
Definition at line 418 of file ff.c.
Referenced by f_rename().
BPB_BytsPerSec
#define BPB_BytsPerSec 11 /* Sector size [byte] (WORD) */
Definition at line 393 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_BytsPerSecEx
#define BPB_BytsPerSecEx 108 /* exFAT: Log2 of sector size in byte (BYTE) */
Definition at line 439 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_DataOfsEx
#define BPB_DataOfsEx 88 /* exFAT: Data offset from top of the volume [sector] (DWORD) */
Definition at line 432 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_DrvNumEx
#define BPB_DrvNumEx 111 /* exFAT: Physical drive number for int13h (BYTE) */
Definition at line 442 of file ff.c.
Referenced by f_rename().
BPB_ExtFlags32
#define BPB_ExtFlags32 40 /* FAT32: Extended flags (WORD) */
Definition at line 414 of file ff.c.
BPB_FatOfsEx
#define BPB_FatOfsEx 80 /* exFAT: FAT offset from top of the volume [sector] (DWORD) */
Definition at line 430 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_FATSz16
#define BPB_FATSz16 22 /* FAT size (16-bit) [sector] (WORD) */
Definition at line 400 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_FATSz32
#define BPB_FATSz32 36 /* FAT32: FAT size [sector] (DWORD) */
Definition at line 413 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_FatSzEx
#define BPB_FatSzEx 84 /* exFAT: FAT size [sector] (DWORD) */
Definition at line 431 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_FSInfo32
#define BPB_FSInfo32 48 /* FAT32: Offset of FSINFO sector (WORD) */
Definition at line 417 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_FSVer32
#define BPB_FSVer32 42 /* FAT32: File system version (WORD) */
Definition at line 415 of file ff.c.
Referenced by find_volume().
BPB_FSVerEx
#define BPB_FSVerEx 104 /* exFAT: File system version (WORD) */
Definition at line 436 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_HiddSec
#define BPB_HiddSec 28 /* Volume offset from top of the drive (DWORD) */
Definition at line 403 of file ff.c.
Referenced by f_rename().
BPB_Media
#define BPB_Media 21 /* Media descriptor (BYTE) */
Definition at line 399 of file ff.c.
Referenced by f_rename().
BPB_NumClusEx
#define BPB_NumClusEx 92 /* exFAT: Number of clusters (DWORD) */
Definition at line 433 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_NumFATs
#define BPB_NumFATs 16 /* Number of FATs (BYTE) */
Definition at line 396 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_NumFATsEx
#define BPB_NumFATsEx 110 /* exFAT: Number of FATs (BYTE) */
Definition at line 441 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_NumHeads
#define BPB_NumHeads 26 /* Number of heads for int13h (WORD) */
Definition at line 402 of file ff.c.
Referenced by f_rename().
BPB_PercInUseEx
#define BPB_PercInUseEx 112 /* exFAT: Percent in use (BYTE) */
Definition at line 443 of file ff.c.
Referenced by f_rename().
BPB_RootClus32
#define BPB_RootClus32 44 /* FAT32: Root directory cluster (DWORD) */
Definition at line 416 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_RootClusEx
#define BPB_RootClusEx 96 /* exFAT: Root directory cluster (DWORD) */
Definition at line 434 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_RootEntCnt
#define BPB_RootEntCnt 17 /* Size of root directory area for FAT12/16 [entry] (WORD) */
Definition at line 397 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_RsvdEx
#define BPB_RsvdEx 113 /* exFAT: Reserved (7-byte) */
Definition at line 444 of file ff.c.
BPB_RsvdSecCnt
#define BPB_RsvdSecCnt 14 /* Size of reserved area [sector] (WORD) */
Definition at line 395 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_SecPerClus
#define BPB_SecPerClus 13 /* Cluster size [sector] (BYTE) */
Definition at line 394 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_SecPerClusEx
#define BPB_SecPerClusEx 109 /* exFAT: Log2 of cluster size in sector (BYTE) */
Definition at line 440 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_SecPerTrk
#define BPB_SecPerTrk 24 /* Track size for int13h [sector] (WORD) */
Definition at line 401 of file ff.c.
Referenced by f_rename().
BPB_TotSec16
#define BPB_TotSec16 19 /* Volume size (16-bit) [sector] (WORD) */
Definition at line 398 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_TotSec32
#define BPB_TotSec32 32 /* Volume size (32-bit) [sector] (DWORD) */
Definition at line 404 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_TotSecEx
#define BPB_TotSecEx 72 /* exFAT: Volume size [sector] (QWORD) */
Definition at line 429 of file ff.c.
Referenced by f_rename(), and find_volume().
BPB_VolFlagEx
#define BPB_VolFlagEx 106 /* exFAT: Volume flags (BYTE) */
Definition at line 437 of file ff.c.
Referenced by f_rename().
BPB_VolIDEx
#define BPB_VolIDEx 100 /* exFAT: Volume serial number (DWORD) */
Definition at line 435 of file ff.c.
Referenced by f_rename().
BPB_VolOfsEx
#define BPB_VolOfsEx 64 /* exFAT: Volume offset from top of the drive [sector] (QWORD) */
Definition at line 428 of file ff.c.
Referenced by f_rename().
BPB_ZeroedEx
#define BPB_ZeroedEx 11 /* exFAT: MBZ field (53-byte) */
Definition at line 427 of file ff.c.
Referenced by find_volume().
BS_55AA
#define BS_55AA 510 /* Signature word (WORD) */
Definition at line 465 of file ff.c.
Referenced by check_fs(), f_rename(), find_volume(), and sync_fs().
BS_BootCode
#define BS_BootCode 62 /* Boot code (448-byte) */
Definition at line 411 of file ff.c.
BS_BootCode32
#define BS_BootCode32 90 /* FAT32: Boot code (420-byte) */
Definition at line 425 of file ff.c.
BS_BootCodeEx
#define BS_BootCodeEx 120 /* exFAT: Boot code (390-byte) */
Definition at line 445 of file ff.c.
Referenced by f_rename().
BS_BootSig
#define BS_BootSig 38 /* Extended boot signature (BYTE) */
Definition at line 407 of file ff.c.
Referenced by f_rename().
BS_BootSig32
#define BS_BootSig32 66 /* FAT32: Extended boot signature (BYTE) */
Definition at line 421 of file ff.c.
Referenced by f_rename().
BS_DrvNum
#define BS_DrvNum 36 /* Physical drive number for int13h (BYTE) */
Definition at line 405 of file ff.c.
Referenced by f_rename().
BS_DrvNum32
#define BS_DrvNum32 64 /* FAT32: Physical drive number for int13h (BYTE) */
Definition at line 419 of file ff.c.
Referenced by f_rename().
BS_FilSysType
#define BS_FilSysType 54 /* File system type string (8-byte) */
Definition at line 410 of file ff.c.
Referenced by check_fs().
BS_FilSysType32
#define BS_FilSysType32 82 /* FAT32: File system type string (8-byte) */
Definition at line 424 of file ff.c.
Referenced by check_fs().
BS_JmpBoot
#define BS_JmpBoot 0 /* x86 jump instruction (3-byte) */
Definition at line 391 of file ff.c.
Referenced by check_fs(), and f_rename().
BS_NTres
#define BS_NTres 37 /* Error flag (BYTE) */
Definition at line 406 of file ff.c.
BS_NTres32
#define BS_NTres32 65 /* FAT32: Error flag (BYTE) */
Definition at line 420 of file ff.c.
BS_OEMName
#define BS_OEMName 3 /* OEM name (8-byte) */
Definition at line 392 of file ff.c.
BS_VolID
#define BS_VolID 39 /* Volume serial number (DWORD) */
Definition at line 408 of file ff.c.
Referenced by f_rename().
BS_VolID32
#define BS_VolID32 67 /* FAT32: Volume serial number (DWORD) */
Definition at line 422 of file ff.c.
Referenced by f_rename().
BS_VolLab
#define BS_VolLab 43 /* Volume label string (8-byte) */
Definition at line 409 of file ff.c.
Referenced by f_rename().
BS_VolLab32
#define BS_VolLab32 71 /* FAT32: Volume label string (8-byte) */
Definition at line 423 of file ff.c.
Referenced by f_rename().
DDEM
#define DDEM 0xE5 /* Deleted directory entry mark set to DIR_Name[0] */
Definition at line 506 of file ff.c.
Referenced by create_name(), dir_alloc(), dir_find(), dir_read(), dir_remove(), f_rename(), and get_fileinfo().
DEF_NAMBUF
#define DEF_NAMBUF
Definition at line 538 of file ff.c.
Referenced by f_close(), f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), and f_unlink().
DIR_Attr
#define DIR_Attr 11 /* Attribute (BYTE) */
Definition at line 468 of file ff.c.
Referenced by dir_find(), dir_read(), f_mkdir(), f_open(), f_rename(), f_sync(), and get_fileinfo().
DIR_CrtTime
#define DIR_CrtTime 14 /* Created time (DWORD) */
Definition at line 471 of file ff.c.
Referenced by f_open().
DIR_CrtTime10
#define DIR_CrtTime10 13 /* Created time sub-second (BYTE) */
Definition at line 470 of file ff.c.
DIR_FileSize
#define DIR_FileSize 28 /* File size (DWORD) */
Definition at line 476 of file ff.c.
Referenced by f_open(), f_sync(), and get_fileinfo().
DIR_FstClusHI
#define DIR_FstClusHI 20 /* Higher 16-bit of first cluster (WORD) */
Definition at line 473 of file ff.c.
Referenced by ld_clust(), and st_clust().
DIR_FstClusLO
#define DIR_FstClusLO 26 /* Lower 16-bit of first cluster (WORD) */
Definition at line 475 of file ff.c.
Referenced by ld_clust(), and st_clust().
DIR_LstAccDate
#define DIR_LstAccDate 18 /* Last accessed date (WORD) */
Definition at line 472 of file ff.c.
Referenced by f_sync().
DIR_ModTime
#define DIR_ModTime 22 /* Modified time (DWORD) */
Definition at line 474 of file ff.c.
Referenced by f_mkdir(), f_open(), f_rename(), f_sync(), and get_fileinfo().
DIR_Name
#define DIR_Name 0 /* Short file name (11-byte) */
Definition at line 467 of file ff.c.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_mkdir(), and f_rename().
DIR_NTres
#define DIR_NTres 12 /* Lower case flag (BYTE) */
Definition at line 469 of file ff.c.
Referenced by dir_register(), and get_fileinfo().
ENTER_FF
#define ENTER_FF (fs)
Definition at line 47 of file ff.c.
Referenced by find_volume(), and validate().
FA_DIRTY
#define FA_DIRTY 0x80 /* FIL.buf[] needs to be written-back */
Definition at line 363 of file ff.c.
Referenced by f_lseek(), f_read(), f_rename(), f_sync(), f_truncate(), and f_write().
FA_MODIFIED
#define FA_MODIFIED 0x40 /* File has been modified */
Definition at line 362 of file ff.c.
Referenced by f_lseek(), f_open(), f_rename(), f_sync(), f_truncate(), and f_write().
FA_SEEKEND
#define FA_SEEKEND 0x20 /* Seek to end of the file on file open */
Definition at line 361 of file ff.c.
Referenced by f_open().
FREE_NAMBUF
#define FREE_NAMBUF ()
Definition at line 540 of file ff.c.
Referenced by f_close(), f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), and f_unlink().
FSI_Free_Count
#define FSI_Free_Count 488 /* FAT32 FSI: Number of free clusters (DWORD) */
Definition at line 449 of file ff.c.
Referenced by f_rename(), find_volume(), and sync_fs().
FSI_LeadSig
#define FSI_LeadSig 0 /* FAT32 FSI: Leading signature (DWORD) */
Definition at line 447 of file ff.c.
Referenced by f_rename(), find_volume(), and sync_fs().
FSI_Nxt_Free
#define FSI_Nxt_Free 492 /* FAT32 FSI: Last allocated cluster (DWORD) */
Definition at line 450 of file ff.c.
Referenced by f_rename(), find_volume(), and sync_fs().
FSI_StrucSig
#define FSI_StrucSig 484 /* FAT32 FSI: Structure signature (DWORD) */
Definition at line 448 of file ff.c.
Referenced by f_rename(), find_volume(), and sync_fs().
GET_FATTIME
#define GET_FATTIME () get_fattime()
Definition at line 71 of file ff.c.
Referenced by f_mkdir(), f_open(), f_rename(), and f_sync().
INIT_NAMBUF
#define INIT_NAMBUF (fs)
Definition at line 539 of file ff.c.
Referenced by f_close(), f_mkdir(), f_open(), f_opendir(), f_readdir(), f_rename(), f_stat(), f_sync(), and f_unlink().
IsDBCS1
#define IsDBCS1 (c) 0
Definition at line 348 of file ff.c.
Referenced by create_name(), f_rename(), get_fileinfo(), and st_clust().
IsDBCS2
#define IsDBCS2 (c) 0
Definition at line 349 of file ff.c.
Referenced by create_name(), f_rename(), and get_fileinfo().
IsDigit
#define IsDigit (c) (((c)>='0')&&((c)<='9'))
Definition at line 330 of file ff.c.
Referenced by f_rename().
IsLower
#define IsLower (c) (((c)>='a')&&((c)<='z'))
Definition at line 329 of file ff.c.
Referenced by create_name(), f_rename(), get_fileinfo(), and get_ldnumber().
IsUpper
#define IsUpper (c) (((c)>='A')&&((c)<='Z'))
Definition at line 328 of file ff.c.
Referenced by create_name(), and get_fileinfo().
LDIR_Attr
#define LDIR_Attr 11 /* LFN attribute (BYTE) */
Definition at line 478 of file ff.c.
Referenced by st_clust().
LDIR_Chksum
#define LDIR_Chksum 13 /* Checksum of the SFN entry (BYTE) */
Definition at line 480 of file ff.c.
Referenced by dir_find(), dir_read(), and st_clust().
LDIR_FstClusLO
#define LDIR_FstClusLO 26 /* Must be zero (WORD) */
Definition at line 481 of file ff.c.
Referenced by st_clust().
LDIR_Ord
#define LDIR_Ord 0 /* LFN entry order and LLE flag (BYTE) */
Definition at line 477 of file ff.c.
Referenced by st_clust().
LDIR_Type
#define LDIR_Type 12 /* LFN type (BYTE) */
Definition at line 479 of file ff.c.
Referenced by st_clust().
LEAVE_FF
#define LEAVE_FF (fs, res) return res
Definition at line 48 of file ff.c.
Referenced by f_close(), f_getfree(), f_lseek(), f_mkdir(), f_mount(), f_open(), f_opendir(), f_read(), f_readdir(), f_rename(), f_stat(), f_sync(), f_truncate(), f_unlink(), and f_write().
LLEF
#define LLEF 0x40 /* Last long entry flag in LDIR_Ord */
Definition at line 505 of file ff.c.
Referenced by dir_find(), dir_read(), and st_clust().
MAX_DIR
#define MAX_DIR 0x200000 /* Maximum size of FAT directory */
Definition at line 383 of file ff.c.
Referenced by dir_next(), and dir_sdi().
MAX_DIR_EX
#define MAX_DIR_EX 0x10000000 /* Maximum size of exFAT directory */
Definition at line 384 of file ff.c.
Referenced by dir_next(), and dir_sdi().
MAX_EXFAT
#define MAX_EXFAT 0x7FFFFFFD /* Maximum number of exFAT clusters (limited by implementation) */
Definition at line 382 of file ff.c.
Referenced by f_rename(), and find_volume().
MAX_FAT12
#define MAX_FAT12 0xFF5 /* Maximum number of FAT12 clusters */
Definition at line 379 of file ff.c.
Referenced by f_rename(), and find_volume().
MAX_FAT16
#define MAX_FAT16 0xFFF5 /* Maximum number of FAT16 clusters */
Definition at line 380 of file ff.c.
Referenced by f_rename(), and find_volume().
MAX_FAT32
#define MAX_FAT32 0xFFFFFF5 /* Maximum number of FAT32 clusters */
Definition at line 381 of file ff.c.
Referenced by f_rename().
MBR_Table
#define MBR_Table 446 /* MBR: Offset of partition table in the MBR */
Definition at line 452 of file ff.c.
Referenced by f_rename(), and find_volume().
NS_BODY
#define NS_BODY 0x08 /* Lower case flag (body) */
Definition at line 371 of file ff.c.
Referenced by create_name(), dir_register(), and get_fileinfo().
NS_DOT
#define NS_DOT 0x20 /* Dot entry */
Definition at line 373 of file ff.c.
Referenced by create_name(), dir_register(), f_mkdir(), f_rename(), f_unlink(), and follow_path().
NS_EXT
#define NS_EXT 0x10 /* Lower case flag (ext) */
Definition at line 372 of file ff.c.
Referenced by create_name(), dir_register(), and get_fileinfo().
NS_LAST
#define NS_LAST 0x04 /* Last segment */
Definition at line 370 of file ff.c.
Referenced by create_name(), and follow_path().
NS_LFN
#define NS_LFN 0x02 /* Force to create LFN entry */
Definition at line 369 of file ff.c.
Referenced by create_name(), and dir_register().
NS_LOSS
#define NS_LOSS 0x01 /* Out of 8.3 format */
Definition at line 368 of file ff.c.
Referenced by create_name(), dir_find(), and dir_register().
NS_NOLFN
#define NS_NOLFN 0x40 /* Do not find LFN */
Definition at line 374 of file ff.c.
Referenced by dir_find(), and dir_register().
NS_NONAME
#define NS_NONAME 0x80 /* Not followed */
Definition at line 375 of file ff.c.
Referenced by dir_register(), f_close(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), and follow_path().
NSFLAG
#define NSFLAG 11 /* Index of name status byte in fn[] */
Definition at line 367 of file ff.c.
Referenced by create_name(), dir_find(), dir_register(), f_close(), f_mkdir(), f_open(), f_opendir(), f_rename(), f_stat(), f_unlink(), and follow_path().
PTE_Boot
#define PTE_Boot 0 /* MBR PTE: Boot indicator */
Definition at line 454 of file ff.c.
Referenced by f_rename().
PTE_EdCyl
#define PTE_EdCyl 7 /* MBR PTE: End cylinder */
Definition at line 461 of file ff.c.
Referenced by f_rename().
PTE_EdHead
#define PTE_EdHead 5 /* MBR PTE: End head */
Definition at line 459 of file ff.c.
Referenced by f_rename().
PTE_EdSec
#define PTE_EdSec 6 /* MBR PTE: End sector */
Definition at line 460 of file ff.c.
Referenced by f_rename().
PTE_SizLba
#define PTE_SizLba 12 /* MBR PTE: Size in LBA */
Definition at line 463 of file ff.c.
Referenced by f_rename().
PTE_StCyl
#define PTE_StCyl 3 /* MBR PTE: Start cylinder */
Definition at line 457 of file ff.c.
Referenced by f_rename().
PTE_StHead
#define PTE_StHead 1 /* MBR PTE: Start head */
Definition at line 455 of file ff.c.
Referenced by f_rename().
PTE_StLba
#define PTE_StLba 8 /* MBR PTE: Start in LBA */
Definition at line 462 of file ff.c.
Referenced by f_rename(), and find_volume().
PTE_StSec
#define PTE_StSec 2 /* MBR PTE: Start sector */
Definition at line 456 of file ff.c.
Referenced by f_rename().
PTE_System
#define PTE_System 4 /* MBR PTE: System ID */
Definition at line 458 of file ff.c.
Referenced by f_rename(), and find_volume().
RDDEM
#define RDDEM 0x05 /* Replacement of the character collides with DDEM */
Definition at line 507 of file ff.c.
Referenced by create_name(), and get_fileinfo().
SS
#define SS (fs) ((UINT)_MAX_SS) /* Fixed sector size */
Definition at line 58 of file ff.c.
Referenced by create_chain(), dir_next(), dir_register(), dir_sdi(), f_getfree(), f_lseek(), f_mkdir(), f_open(), f_read(), f_rename(), f_write(), find_volume(), follow_path(), get_fat(), put_fat(), and sync_fs().
SZ_PTE
#define SZ_PTE 16 /* MBR: Size of a partition table entry */
Definition at line 453 of file ff.c.
Referenced by f_rename(), and find_volume().
SZDIRE
#define SZDIRE 32 /* Size of a directory entry */
Definition at line 504 of file ff.c.
Referenced by dir_find(), dir_next(), dir_register(), dir_sdi(), f_close(), f_mkdir(), f_rename(), find_volume(), and st_clust().
XDIR_AccTime
#define XDIR_AccTime 16 /* Last accessed time (DWORD) */
Definition at line 491 of file ff.c.
Referenced by f_sync().
XDIR_AccTZ
#define XDIR_AccTZ 24 /* Last accessed timezone (BYTE) */
Definition at line 496 of file ff.c.
XDIR_Attr
#define XDIR_Attr 4 /* File attribute (WORD) */
Definition at line 488 of file ff.c.
Referenced by dir_read(), f_mkdir(), f_open(), f_rename(), f_sync(), and st_clust().
XDIR_CaseSum
#define XDIR_CaseSum 4 /* Sum of case conversion table (DWORD) */
Definition at line 485 of file ff.c.
XDIR_CrtTime
#define XDIR_CrtTime 8 /* Created time (DWORD) */
Definition at line 489 of file ff.c.
Referenced by f_open().
XDIR_CrtTime10
#define XDIR_CrtTime10 20 /* Created time subsecond (BYTE) */
Definition at line 492 of file ff.c.
Referenced by f_open().
XDIR_CrtTZ
#define XDIR_CrtTZ 22 /* Created timezone (BYTE) */
Definition at line 494 of file ff.c.
XDIR_FileSize
#define XDIR_FileSize 56 /* File/Directory size (QWORD) */
Definition at line 502 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_open(), f_opendir(), f_sync(), f_unlink(), follow_path(), and st_clust().
XDIR_FstClus
#define XDIR_FstClus 52 /* First cluster of the file data (DWORD) */
Definition at line 501 of file ff.c.
Referenced by f_close(), f_mkdir(), f_open(), f_opendir(), f_sync(), f_unlink(), and follow_path().
XDIR_GenFlags
#define XDIR_GenFlags 33 /* Gneral secondary flags (WORD) */
Definition at line 497 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_open(), f_opendir(), f_sync(), f_unlink(), and follow_path().
XDIR_Label
#define XDIR_Label 2 /* Volume label (11-WORD) */
Definition at line 484 of file ff.c.
Referenced by f_rename().
XDIR_ModTime
#define XDIR_ModTime 12 /* Modified time (DWORD) */
Definition at line 490 of file ff.c.
Referenced by f_mkdir(), f_open(), f_rename(), f_sync(), and st_clust().
XDIR_ModTime10
#define XDIR_ModTime10 21 /* Modified time subsecond (BYTE) */
Definition at line 493 of file ff.c.
Referenced by f_open(), and f_sync().
XDIR_ModTZ
#define XDIR_ModTZ 23 /* Modified timezone (BYTE) */
Definition at line 495 of file ff.c.
XDIR_NameHash
#define XDIR_NameHash 36 /* Hash of file name (WORD) */
Definition at line 499 of file ff.c.
Referenced by dir_find(), f_rename(), and st_clust().
XDIR_NumLabel
#define XDIR_NumLabel 1 /* Number of volume label characters (BYTE) */
Definition at line 483 of file ff.c.
Referenced by f_rename().
XDIR_NumName
#define XDIR_NumName 35 /* Number of file name characters (BYTE) */
Definition at line 498 of file ff.c.
Referenced by dir_find(), f_rename(), and st_clust().
XDIR_NumSec
#define XDIR_NumSec 1 /* Number of secondary entries (BYTE) */
Definition at line 486 of file ff.c.
Referenced by f_rename(), and st_clust().
XDIR_SetSum
#define XDIR_SetSum 2 /* Sum of the set of directory entries (WORD) */
Definition at line 487 of file ff.c.
Referenced by st_clust().
XDIR_Type
#define XDIR_Type 0 /* Type of exFAT directory entry (BYTE) */
Definition at line 482 of file ff.c.
Referenced by dir_alloc(), dir_remove(), f_rename(), and st_clust().
XDIR_ValidFileSize
#define XDIR_ValidFileSize 40 /* Valid file size (QWORD) */
Definition at line 500 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_open(), and f_sync().
Function Documentation
check_fs()
static BYTE check_fs (FATFS * fs, DWORD sect) static
Definition at line 2914 of file ff.c.
References BS_55AA, BS_FilSysType, BS_FilSysType32, BS_JmpBoot, ld_dword(), ld_word(), mem_cmp(), and move_window().
Referenced by find_volume().
chk_chr()
static int chk_chr (const char * str, int chr) static
Definition at line 715 of file ff.c.
References fs.
Referenced by create_name(), and f_rename().
clust2sect()
static DWORD clust2sect (FATFS * fs, DWORD clst) static
Definition at line 969 of file ff.c.
Referenced by dir_next(), dir_sdi(), f_lseek(), f_mkdir(), f_open(), f_read(), f_rename(), f_write(), find_volume(), and remove_chain().
create_chain()
static DWORD create_chain (_FDID * obj, DWORD clst) static
Definition at line 1312 of file ff.c.
References fp, fs, get_fat(), put_fat(), and SS.
Referenced by dir_next(), f_lseek(), f_mkdir(), and f_write().
create_name()
static FRESULT create_name (DIR * dp, const TCHAR ** path) static
Definition at line 2570 of file ff.c.
References chk_chr(), DDEM, IsDBCS1, IsDBCS2, IsLower, IsUpper, mem_set(), NS_BODY, NS_DOT, NS_EXT, NS_LAST, NS_LFN, NS_LOSS, NSFLAG, and RDDEM.
Referenced by follow_path().
dir_alloc()
static FRESULT dir_alloc (DIR * dp, UINT nent) static
Definition at line 1546 of file ff.c.
References DDEM, DIR_Name, dir_next(), dir_sdi(), fs, move_window(), and XDIR_Type.
Referenced by dir_register(), and f_rename().
dir_find()
static FRESULT dir_find (DIR * dp) static
Definition at line 2166 of file ff.c.
References AM_LFN, AM_MASK, AM_VOL, DDEM, DIR_Attr, DIR_Name, dir_next(), dir_read(), dir_sdi(), ld_word(), LDIR_Chksum, LLEF, mem_cmp(), move_window(), NS_LOSS, NS_NOLFN, NSFLAG, SZDIRE, XDIR_NameHash, and XDIR_NumName.
Referenced by dir_register(), and follow_path().
dir_next()
static FRESULT dir_next (DIR * dp, int stretch) static
Definition at line 1476 of file ff.c.
References clust2sect(), create_chain(), fs, get_fat(), MAX_DIR, MAX_DIR_EX, mem_set(), SS, sync_window(), and SZDIRE.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_close(), f_readdir(), and st_clust().
dir_read()
static FRESULT dir_read (DIR * dp, int vol) static
Definition at line 2089 of file ff.c.
References AM_LFN, AM_MASK, AM_VOL, DDEM, DIR_Attr, DIR_Name, dir_next(), LDIR_Chksum, LLEF, move_window(), and XDIR_Attr.
Referenced by dir_find(), f_close(), f_readdir(), f_rename(), and f_unlink().
dir_register()
static FRESULT dir_register (DIR * dp) static
Definition at line 2245 of file ff.c.
References dir_alloc(), dir_find(), DIR_Name, dir_next(), DIR_NTres, dir_sdi(), mem_cpy(), mem_set(), move_window(), NS_BODY, NS_DOT, NS_EXT, NS_LFN, NS_LOSS, NS_NOLFN, NS_NONAME, NSFLAG, SS, SZDIRE, XDIR_FileSize, XDIR_GenFlags, and XDIR_ValidFileSize.
Referenced by f_mkdir(), f_open(), and f_rename().
dir_remove()
static FRESULT dir_remove (DIR * dp) static
Definition at line 2348 of file ff.c.
References DDEM, DIR_Name, dir_next(), dir_sdi(), move_window(), and XDIR_Type.
Referenced by f_rename(), and f_unlink().
dir_sdi()
static FRESULT dir_sdi (DIR * dp, DWORD ofs) static
Definition at line 1427 of file ff.c.
References clust2sect(), fs, get_fat(), MAX_DIR, MAX_DIR_EX, SS, and SZDIRE.
Referenced by dir_alloc(), dir_find(), dir_register(), dir_remove(), f_close(), f_opendir(), f_readdir(), f_rename(), f_unlink(), follow_path(), and st_clust().
f_close()
FRESULT f_close (FIL * fp)
Definition at line 3753 of file ff.c.
References DEF_NAMBUF, dir_next(), dir_read(), dir_sdi(), f_sync(), find_volume(), follow_path(), FREE_NAMBUF, fs, get_fileinfo(), get_ldnumber(), INIT_NAMBUF, ld_clust(), ld_dword(), LEAVE_FF, move_window(), NS_NONAME, NSFLAG, SZDIRE, validate(), and XDIR_FstClus.
Referenced by SD_Read().
f_closedir()
FRESULT f_closedir (DIR * dp)
Definition at line 4162 of file ff.c.
References fs, and validate().
f_getfree()
FRESULT f_getfree (const TCHAR * path, DWORD * nclst, FATFS ** fatfs)
Definition at line 4318 of file ff.c.
References find_volume(), fs, get_fat(), ld_dword(), ld_word(), LEAVE_FF, move_window(), and SS.
f_lseek()
FRESULT f_lseek (FIL * fp, FSIZE_t ofs)
Definition at line 3940 of file ff.c.
References ABORT, clust2sect(), create_chain(), disk_read(), disk_write(), FA_DIRTY, FA_MODIFIED, fs, get_fat(), LEAVE_FF, SS, and validate().
f_mkdir()
FRESULT f_mkdir (const TCHAR * path)
Definition at line 4550 of file ff.c.
References clust2sect(), create_chain(), DEF_NAMBUF, DIR_Attr, DIR_ModTime, DIR_Name, dir_register(), find_volume(), follow_path(), FREE_NAMBUF, fs, GET_FATTIME, INIT_NAMBUF, LEAVE_FF, mem_cpy(), mem_set(), NS_DOT, NSFLAG, remove_chain(), SS, st_clust(), st_dword(), sync_fs(), sync_window(), SZDIRE, XDIR_Attr, XDIR_FileSize, XDIR_FstClus, XDIR_GenFlags, XDIR_ModTime, and XDIR_ValidFileSize.
f_mount()
FRESULT f_mount (FATFS * fs, const TCHAR * path, BYTE opt)
Definition at line 3198 of file ff.c.
References FatFs, find_volume(), fs, get_ldnumber(), and LEAVE_FF.
Referenced by SD_Read().
f_open()
FRESULT f_open (FIL * fp, const TCHAR * path, BYTE mode)
Definition at line 3245 of file ff.c.
References clust2sect(), DEF_NAMBUF, DIR_Attr, DIR_CrtTime, DIR_FileSize, DIR_ModTime, dir_register(), disk_read(), FA_MODIFIED, FA_SEEKEND, find_volume(), follow_path(), FREE_NAMBUF, fs, get_fat(), GET_FATTIME, INIT_NAMBUF, ld_clust(), ld_dword(), LEAVE_FF, mem_set(), move_window(), NS_NONAME, NSFLAG, remove_chain(), SS, st_clust(), st_dword(), XDIR_Attr, XDIR_CrtTime, XDIR_CrtTime10, XDIR_FileSize, XDIR_FstClus, XDIR_GenFlags, XDIR_ModTime, XDIR_ModTime10, and XDIR_ValidFileSize.
Referenced by SD_Read().
f_opendir()
FRESULT f_opendir (DIR * dp, const TCHAR * path)
Definition at line 4092 of file ff.c.
References DEF_NAMBUF, dir_sdi(), find_volume(), follow_path(), FREE_NAMBUF, fs, INIT_NAMBUF, ld_clust(), ld_dword(), LEAVE_FF, NS_NONAME, NSFLAG, XDIR_FileSize, XDIR_FstClus, and XDIR_GenFlags.
Referenced by f_readdir().
f_read()
FRESULT f_read (FIL * fp, void * buff, UINT btr, UINT * br)
Definition at line 3446 of file ff.c.
References ABORT, clust2sect(), disk_read(), disk_write(), FA_DIRTY, fs, get_fat(), LEAVE_FF, mem_cpy(), move_window(), SS, and validate().
Referenced by f_rename(), and SD_Read().
f_readdir()
FRESULT f_readdir (DIR * dp, FILINFO * fno)
Definition at line 4195 of file ff.c.
References DEF_NAMBUF, dir_next(), dir_read(), dir_sdi(), f_opendir(), FREE_NAMBUF, fs, get_fileinfo(), INIT_NAMBUF, LEAVE_FF, and validate().
f_rename()
FRESULT f_rename (const TCHAR * path_old, const TCHAR * path_new)
Definition at line 4643 of file ff.c.
References ABORT, AM_VOL, BPB_BkBootSec32, BPB_BytsPerSec, BPB_BytsPerSecEx, BPB_DataOfsEx, BPB_DrvNumEx, BPB_FatOfsEx, BPB_FATSz16, BPB_FATSz32, BPB_FatSzEx, BPB_FSInfo32, BPB_FSVerEx, BPB_HiddSec, BPB_Media, BPB_NumClusEx, BPB_NumFATs, BPB_NumFATsEx, BPB_NumHeads, BPB_PercInUseEx, BPB_RootClus32, BPB_RootClusEx, BPB_RootEntCnt, BPB_RsvdSecCnt, BPB_SecPerClus, BPB_SecPerClusEx, BPB_SecPerTrk, BPB_TotSec16, BPB_TotSec32, BPB_TotSecEx, BPB_VolFlagEx, BPB_VolIDEx, BPB_VolOfsEx, BS_55AA, BS_BootCodeEx, BS_BootSig, BS_BootSig32, BS_DrvNum, BS_DrvNum32, BS_JmpBoot, BS_VolID, BS_VolID32, BS_VolLab, BS_VolLab32, chk_chr(), clust2sect(), DDEM, DEF_NAMBUF, dir_alloc(), DIR_Attr, DIR_ModTime, DIR_Name, dir_read(), dir_register(), dir_remove(), dir_sdi(), disk_initialize(), disk_read(), disk_write(), f_read(), f_write(), FA_DIRTY, FA_MODIFIED, FatFs, find_volume(), follow_path(), fp, FREE_NAMBUF, fs, FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FSI_StrucSig, get_fat(), GET_FATTIME, get_ldnumber(), INIT_NAMBUF, IsDBCS1, IsDBCS2, IsDigit, IsLower, ld_clust(), ld_dword(), ld_word(), LEAVE_FF, MAX_EXFAT, MAX_FAT12, MAX_FAT16, MAX_FAT32, MBR_Table, mem_cpy(), mem_set(), move_window(), NS_DOT, NS_NONAME, NSFLAG, PTE_Boot, PTE_EdCyl, PTE_EdHead, PTE_EdSec, PTE_SizLba, PTE_StCyl, PTE_StHead, PTE_StLba, PTE_StSec, PTE_System, put_fat(), SS, st_clust(), st_dword(), st_word(), sync_fs(), SZ_PTE, SZDIRE, validate(), XDIR_Attr, XDIR_Label, XDIR_ModTime, XDIR_NameHash, XDIR_NumLabel, XDIR_NumName, XDIR_NumSec, and XDIR_Type.
f_stat()
FRESULT f_stat (const TCHAR * path, FILINFO * fno)
Definition at line 4283 of file ff.c.
References DEF_NAMBUF, find_volume(), follow_path(), FREE_NAMBUF, get_fileinfo(), INIT_NAMBUF, LEAVE_FF, NS_NONAME, and NSFLAG.
f_sync()
FRESULT f_sync (FIL * fp)
Definition at line 3675 of file ff.c.
References DEF_NAMBUF, DIR_Attr, DIR_FileSize, DIR_LstAccDate, DIR_ModTime, disk_write(), FA_DIRTY, FA_MODIFIED, FREE_NAMBUF, fs, GET_FATTIME, INIT_NAMBUF, LEAVE_FF, move_window(), st_clust(), st_dword(), st_word(), sync_fs(), validate(), XDIR_AccTime, XDIR_Attr, XDIR_FileSize, XDIR_FstClus, XDIR_GenFlags, XDIR_ModTime, XDIR_ModTime10, and XDIR_ValidFileSize.
Referenced by f_close().
f_truncate()
FRESULT f_truncate (FIL * fp)
Definition at line 4405 of file ff.c.
References ABORT, disk_write(), FA_DIRTY, FA_MODIFIED, fs, get_fat(), LEAVE_FF, remove_chain(), and validate().
f_unlink()
FRESULT f_unlink (const TCHAR * path)
Definition at line 4455 of file ff.c.
References DEF_NAMBUF, dir_read(), dir_remove(), dir_sdi(), find_volume(), follow_path(), FREE_NAMBUF, fs, INIT_NAMBUF, ld_clust(), ld_dword(), LEAVE_FF, NS_DOT, NS_NONAME, NSFLAG, remove_chain(), sync_fs(), XDIR_FileSize, XDIR_FstClus, and XDIR_GenFlags.
f_write()
FRESULT f_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
Definition at line 3550 of file ff.c.
References ABORT, clust2sect(), create_chain(), disk_read(), disk_write(), FA_DIRTY, FA_MODIFIED, fs, LEAVE_FF, mem_cpy(), move_window(), SS, sync_window(), and validate().
Referenced by f_rename().
find_volume()
static FRESULT find_volume (const TCHAR ** path, FATFS ** rfs, BYTE mode) static
Definition at line 2942 of file ff.c.
References BPB_BytsPerSec, BPB_BytsPerSecEx, BPB_DataOfsEx, BPB_FatOfsEx, BPB_FATSz16, BPB_FATSz32, BPB_FatSzEx, BPB_FSInfo32, BPB_FSVer32, BPB_FSVerEx, BPB_NumClusEx, BPB_NumFATs, BPB_NumFATsEx, BPB_RootClus32, BPB_RootClusEx, BPB_RootEntCnt, BPB_RsvdSecCnt, BPB_SecPerClus, BPB_SecPerClusEx, BPB_TotSec16, BPB_TotSec32, BPB_TotSecEx, BPB_ZeroedEx, BS_55AA, check_fs(), clust2sect(), disk_initialize(), disk_status(), ENTER_FF, FatFs, fs, FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FSI_StrucSig, Fsid, get_ldnumber(), ld_dword(), ld_word(), MAX_EXFAT, MAX_FAT12, MAX_FAT16, MBR_Table, move_window(), PTE_StLba, PTE_System, SS, SZ_PTE, and SZDIRE.
Referenced by f_close(), f_getfree(), f_mkdir(), f_mount(), f_open(), f_opendir(), f_rename(), f_stat(), and f_unlink().
follow_path()
static FRESULT follow_path (DIR * dp, const TCHAR * path) static
Definition at line 2765 of file ff.c.
References create_name(), dir_find(), dir_sdi(), ld_clust(), ld_dword(), NS_DOT, NS_LAST, NS_NONAME, NSFLAG, SS, XDIR_FileSize, XDIR_FstClus, and XDIR_GenFlags.
Referenced by f_close(), f_mkdir(), f_open(), f_opendir(), f_rename(), f_stat(), and f_unlink().
get_fat()
static DWORD get_fat (_FDID * obj, DWORD clst) static
Definition at line 987 of file ff.c.
References fs, ld_dword(), ld_word(), move_window(), and SS.
Referenced by create_chain(), dir_next(), dir_sdi(), f_getfree(), f_lseek(), f_open(), f_read(), f_rename(), f_truncate(), and remove_chain().
get_fileinfo()
static void get_fileinfo (DIR * dp, FILINFO * fno) static
Definition at line 2396 of file ff.c.
References DDEM, DIR_Attr, DIR_FileSize, DIR_ModTime, DIR_NTres, IsDBCS1, IsDBCS2, IsLower, IsUpper, ld_dword(), NS_BODY, NS_EXT, and RDDEM.
Referenced by f_close(), f_readdir(), and f_stat().
get_ldnumber()
static int get_ldnumber (const TCHAR ** path) static
Definition at line 2853 of file ff.c.
References IsLower.
Referenced by f_close(), f_mount(), f_rename(), and find_volume().
ld_clust()
static DWORD ld_clust (FATFS * fs, const BYTE * dir) static
Definition at line 1589 of file ff.c.
References DIR_FstClusHI, DIR_FstClusLO, and ld_word().
Referenced by f_close(), f_open(), f_opendir(), f_rename(), f_unlink(), and follow_path().
ld_dword()
static DWORD ld_dword (const BYTE * ptr) static
Definition at line 613 of file ff.c.
Referenced by check_fs(), f_close(), f_getfree(), f_open(), f_opendir(), f_rename(), f_unlink(), find_volume(), follow_path(), get_fat(), get_fileinfo(), and put_fat().
ld_word()
static WORD ld_word (const BYTE * ptr) static
Definition at line 603 of file ff.c.
Referenced by check_fs(), dir_find(), f_getfree(), f_rename(), find_volume(), get_fat(), ld_clust(), and st_clust().
mem_cmp()
static int mem_cmp (const void * dst, const void * src, UINT cnt) static
Definition at line 702 of file ff.c.
Referenced by check_fs(), and dir_find().
mem_cpy()
static void mem_cpy (void * dst, const void * src, UINT cnt) static
Definition at line 683 of file ff.c.
Referenced by dir_register(), f_mkdir(), f_read(), f_rename(), f_write(), and st_clust().
mem_set()
static void mem_set (void * dst, int val, UINT cnt) static
Definition at line 694 of file ff.c.
Referenced by create_name(), dir_next(), dir_register(), f_mkdir(), f_open(), f_rename(), st_clust(), and sync_fs().
move_window()
static FRESULT move_window (FATFS * fs, DWORD sector) static
Definition at line 898 of file ff.c.
References disk_read(), and sync_window().
Referenced by check_fs(), dir_alloc(), dir_find(), dir_read(), dir_register(), dir_remove(), f_close(), f_getfree(), f_open(), f_read(), f_rename(), f_sync(), f_write(), find_volume(), get_fat(), put_fat(), and st_clust().
put_fat()
static FRESULT put_fat (FATFS * fs, DWORD clst, DWORD val) static
Definition at line 1063 of file ff.c.
References fs, ld_dword(), move_window(), SS, st_dword(), and st_word().
Referenced by create_chain(), f_rename(), and remove_chain().
remove_chain()
static FRESULT remove_chain (_FDID * obj, DWORD clst, DWORD pclst) static
Definition at line 1232 of file ff.c.
References clust2sect(), fs, get_fat(), and put_fat().
Referenced by f_mkdir(), f_open(), f_truncate(), and f_unlink().
st_clust()
static void st_clust (FATFS * fs, BYTE * dir, DWORD cl) static
Definition at line 1607 of file ff.c.
References AM_LFN, DIR_FstClusHI, DIR_FstClusLO, dir_next(), dir_sdi(), dst, IsDBCS1, ld_word(), LDIR_Attr, LDIR_Chksum, LDIR_FstClusLO, LDIR_Ord, LDIR_Type, LLEF, mem_cpy(), mem_set(), move_window(), st_word(), SZDIRE, XDIR_Attr, XDIR_FileSize, XDIR_ModTime, XDIR_NameHash, XDIR_NumName, XDIR_NumSec, XDIR_SetSum, and XDIR_Type.
Referenced by f_mkdir(), f_open(), f_rename(), and f_sync().
st_dword()
static void st_dword (BYTE * ptr, DWORD val) static
Definition at line 651 of file ff.c.
Referenced by f_mkdir(), f_open(), f_rename(), f_sync(), put_fat(), and sync_fs().
st_word()
static void st_word (BYTE * ptr, WORD val) static
Definition at line 644 of file ff.c.
Referenced by f_rename(), f_sync(), put_fat(), st_clust(), and sync_fs().
sync_fs()
static FRESULT sync_fs (FATFS * fs) static
Definition at line 930 of file ff.c.
References BS_55AA, disk_write(), FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FSI_StrucSig, mem_set(), SS, st_dword(), st_word(), and sync_window().
Referenced by f_mkdir(), f_rename(), f_sync(), and f_unlink().
sync_window()
static FRESULT sync_window (FATFS * fs) static
Definition at line 869 of file ff.c.
References disk_write().
Referenced by dir_next(), f_mkdir(), f_write(), move_window(), and sync_fs().
validate()
static FRESULT validate (void * dfp, FATFS ** fs) static
Definition at line 3163 of file ff.c.
References disk_status(), and ENTER_FF.
Referenced by f_close(), f_closedir(), f_lseek(), f_read(), f_readdir(), f_rename(), f_sync(), f_truncate(), and f_write().
Variable Documentation
FatFs
FATFS* FatFs[_VOLUMES] static
Definition at line 526 of file ff.c.
Referenced by f_mount(), f_rename(), and find_volume().
Fsid
WORD Fsid static
Definition at line 527 of file ff.c.
Referenced by find_volume().