My FreeRTOS Project: freertos/src/FreeRTOSCommonHooks.h File Reference
FreeRTOSCommonHooks.h File Reference
Functions
void FreeRTOSDelay (uint32_t ms)
Delay for the specified number of milliSeconds.
void vApplicationMallocFailedHook (void)
FreeRTOS malloc fail hook.
void vApplicationIdleHook (void)
FreeRTOS application idle hook.
void vApplicationStackOverflowHook (xTaskHandle pxTask, signed char *pcTaskName)
FreeRTOS stack overflow hook.
void vApplicationTickHook (void)
FreeRTOS application tick hook.
Function Documentation
FreeRTOSDelay()
void FreeRTOSDelay (uint32_t ms)
Delay for the specified number of milliSeconds.
Parameters
ms : Delay in milliSeconds
Returns
Nothing
Note
Delays the specified number of milliSeoconds using a task delay
Definition at line 60 of file FreeRTOSCommonHooks.c.
References xTaskGetTickCount().
vApplicationIdleHook()
void vApplicationIdleHook (void)
FreeRTOS application idle hook.
Returns
Nothing
Note
Calls ARM Wait for Interrupt function to idle core
FreeRTOS application idle hook.
La tarea de menor prioridad del sistema. Se encarga de recibir los datos de la aplicacion de PC por bluetooth. Una vez terminado de recibir el paquete comprimido, da semaforo a tDescomprimir.
Definition at line 109 of file myTasks.c.
References SerialManager().
Referenced by portTASK_FUNCTION().
vApplicationMallocFailedHook()
void vApplicationMallocFailedHook (void)
FreeRTOS malloc fail hook.
Returns
Nothing
Note
This function is alled when a malloc fails to allocate data.
Definition at line 69 of file FreeRTOSCommonHooks.c.
Referenced by pvPortMalloc().
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (xTaskHandle pxTask, signed char * pcTaskName)
FreeRTOS stack overflow hook.
Parameters
pxTask : Task handle that overflowed stack
pcTaskName : Task name that overflowed stack
Returns
Nothing
Note
This function is alled when a stack overflow occurs.
Definition at line 84 of file FreeRTOSCommonHooks.c.
vApplicationTickHook()
void vApplicationTickHook (void)
FreeRTOS application tick hook.
Returns
Nothing
Note
This just returns to the caller.
FreeRTOS application tick hook.
Warning
this is called by an interrupt handler!
Definition at line 96 of file myTasks.c.