My FreeRTOS Project: Drivers/GPIOLPC1769.c File Reference
GPIOLPC1769.c File Reference
Funciones de manejo de GPIO.
#include "GPIOLPC1769.h"
Functions
void SetDIR (uint8_t puerto, uint8_t pin, uint8_t dir)
void SetPIN (uint8_t puerto, uint8_t pin, uint8_t estado)
uint8_t GetPIN (uint8_t puerto, uint8_t pin, uint8_t actividad)
void toggle (uint8_t puerto, uint8_t pin)
Detailed Description
Funciones de manejo de GPIO.
Definition in file GPIOLPC1769.c.
Function Documentation
GetPIN()
uint8_t GetPIN (uint8_t puerto, uint8_t pin, uint8_t actividad)
Definition at line 52 of file GPIOLPC1769.c.
References GPIO.
Referenced by SerialManager(), and toggle().
SetDIR()
void SetDIR (uint8_t puerto, uint8_t pin, uint8_t dir)
Definition at line 18 of file GPIOLPC1769.c.
References GPIO.
Referenced by ConfigPinBluetooth(), InitShifter(), TestPointInitBT(), and TestPointInitGeneral().
SetPIN()
void SetPIN (uint8_t puerto, uint8_t pin, uint8_t estado)
Definition at line 35 of file GPIOLPC1769.c.
References GPIO.
Referenced by Bluetooth_Init(), PrintStart(), ResetearHC05(), ShiftDataInterrupt(), TestPointInitGeneral(), TIMER0_IRQHandler(), and toggle().
toggle()
void toggle (uint8_t puerto, uint8_t pin)
Definition at line 68 of file GPIOLPC1769.c.
References GetPIN(), and SetPIN().