My FreeRTOS Project: inc/GPIOLPC1769.h File Reference
GPIOLPC1769.h File Reference
Asociaciones a GPIOLPC1769.c.
#include "RegsLPC1769.h"
Functions
void SetDIR (uint8_t, uint8_t, uint8_t)
void SetPIN (uint8_t, uint8_t, uint8_t)
uint8_t GetPIN (uint8_t, uint8_t, uint8_t)
void toggle (uint8_t puerto, uint8_t pin)
Detailed Description
Asociaciones a GPIOLPC1769.c.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file GPIOLPC1769.h.
Function Documentation
GetPIN()
uint8_t GetPIN (uint8_t , uint8_t , uint8_t)
Definition at line 52 of file GPIOLPC1769.c.
References GPIO.
Referenced by SerialManager(), and toggle().
SetDIR()
void SetDIR (uint8_t , uint8_t , uint8_t)
Definition at line 18 of file GPIOLPC1769.c.
References GPIO.
Referenced by ConfigPinBluetooth(), InitShifter(), TestPointInitBT(), and TestPointInitGeneral().
SetPIN()
void SetPIN (uint8_t , uint8_t , uint8_t)
Definition at line 35 of file GPIOLPC1769.c.
References GPIO.
Referenced by Bluetooth_Init(), PrintStart(), ResetearHC05(), ShiftDataInterrupt(), TestPointInitGeneral(), TIMER0_IRQHandler(), and toggle().
toggle()
void toggle (uint8_t puerto, uint8_t pin)
Definition at line 68 of file GPIOLPC1769.c.
References GetPIN(), and SetPIN().