My FreeRTOS Project: freertos/src/heap_3.c File Reference
heap_3.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Functions
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 83 of file heap_3.c.
Function Documentation
pvPortMalloc()
void* pvPortMalloc (size_t xWantedSize)
Definition at line 92 of file heap_3.c.
References vApplicationMallocFailedHook(), vTaskSuspendAll(), and xTaskResumeAll().
Referenced by CrearHallSensor(), CrearShifter(), and xQueueGenericCreate().
vPortFree()
void vPortFree (void * pv)
Definition at line 117 of file heap_3.c.
References vTaskSuspendAll(), and xTaskResumeAll().
Referenced by EliminarHallSensor(), EliminarShifter(), vQueueDelete(), and xQueueGenericCreate().