My FreeRTOS Project: inc/Initializations.h File Reference
Initializations.h File Reference
Asociaciones a Initializations.c.
Functions
void Inicializar (void)
Inicializacion de Hardware.
Detailed Description
Asociaciones a Initializations.c.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file Initializations.h.
Function Documentation
Inicializar()
void Inicializar (void)
Inicializacion de Hardware.
Parameters
void
Returns
:void
Definition at line 35 of file Initializations.c.
References InitHallSensor(), InitPLL(), InitShifter(), InitStatusFlags(), InitTimer0(), InitTimer1(), TestPointInitGeneral(), and UART_Init().
Referenced by tInit().