My FreeRTOS Project: freertos/inc/list.h File Reference
list.h File Reference
Data Structures
struct xLIST_ITEM
struct xMINI_LIST_ITEM
struct xLIST
Macros
#define configLIST_VOLATILE
#define listSET_LIST_ITEM_OWNER(pxListItem, pxOwner) ((pxListItem)->pvOwner = (void *) (pxOwner))
#define listGET_LIST_ITEM_OWNER(pxListItem) (pxListItem)->pvOwner
#define listSET_LIST_ITEM_VALUE(pxListItem, xValue) ((pxListItem)->xItemValue = (xValue))
#define listGET_LIST_ITEM_VALUE(pxListItem) ((pxListItem)->xItemValue)
#define listGET_ITEM_VALUE_OF_HEAD_ENTRY(pxList) ((&((pxList)->xListEnd))->pxNext->xItemValue)
#define listLIST_IS_EMPTY(pxList) ((portBASE_TYPE) ((pxList)->uxNumberOfItems == (unsigned portBASE_TYPE) 0))
#define listCURRENT_LIST_LENGTH(pxList) ((pxList)->uxNumberOfItems)
#define listGET_OWNER_OF_NEXT_ENTRY(pxTCB, pxList)
#define listGET_OWNER_OF_HEAD_ENTRY(pxList) ((&((pxList)->xListEnd))->pxNext->pvOwner)
#define listIS_CONTAINED_WITHIN(pxList, pxListItem) ((portBASE_TYPE) ((pxListItem)->pvContainer == (void *) (pxList)))
#define listLIST_ITEM_CONTAINER(pxListItem) ((pxListItem)->pvContainer)
#define listLIST_IS_INITIALISED(pxList) ((pxList)->xListEnd.xItemValue == portMAX_DELAY)
Typedefs
typedef struct xLIST_ITEM xListItem
typedef struct xMINI_LIST_ITEM xMiniListItem
typedef struct xLIST xList
Functions
void vListInitialise (xList *const pxList)
void vListInitialiseItem (xListItem *const pxItem)
void vListInsert (xList *const pxList, xListItem *const pxNewListItem)
void vListInsertEnd (xList *const pxList, xListItem *const pxNewListItem)
unsigned portBASE_TYPE uxListRemove (xListItem *const pxItemToRemove)
Macro Definition Documentation
configLIST_VOLATILE
#define configLIST_VOLATILE
Definition at line 127 of file list.h.
listCURRENT_LIST_LENGTH
#define listCURRENT_LIST_LENGTH (pxList) ((pxList)->uxNumberOfItems)
Definition at line 222 of file list.h.
Referenced by portTASK_FUNCTION(), prvAllocateTCBAndStack(), vTaskSuspendAll(), and xTaskIncrementTick().
listGET_ITEM_VALUE_OF_HEAD_ENTRY
#define listGET_ITEM_VALUE_OF_HEAD_ENTRY (pxList) ((&((pxList)->xListEnd))->pxNext->xItemValue)
Definition at line 208 of file list.h.
listGET_LIST_ITEM_OWNER
#define listGET_LIST_ITEM_OWNER (pxListItem) (pxListItem)->pvOwner
Definition at line 180 of file list.h.
listGET_LIST_ITEM_VALUE
#define listGET_LIST_ITEM_VALUE (pxListItem) ((pxListItem)->xItemValue)
Definition at line 199 of file list.h.
Referenced by xTaskIncrementTick().
listGET_OWNER_OF_HEAD_ENTRY
#define listGET_OWNER_OF_HEAD_ENTRY (pxList) ((&((pxList)->xListEnd))->pxNext->pvOwner)
Definition at line 273 of file list.h.
Referenced by prvCheckTasksWaitingTermination(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
listGET_OWNER_OF_NEXT_ENTRY
#define listGET_OWNER_OF_NEXT_ENTRY (pxTCB, pxList)
Value:
{                                                                                           \
xList * const pxConstList = (pxList);                                                     \
    /* Increment the index to the next item and return the item, ensuring */                \
    /* we don't return the marker used at the end of the list.  */                          \
    ( pxConstList )->pxIndex = ( pxConstList )->pxIndex->pxNext;                            \
    if( ( void * ) ( pxConstList )->pxIndex == ( void * ) &( ( pxConstList )->xListEnd ) )  \
    {                                                                                       \
        ( pxConstList )->pxIndex = ( pxConstList )->pxIndex->pxNext;                        \
    }                                                                                       \
    ( pxTCB ) = ( pxConstList )->pxIndex->pvOwner;                                          \
}
Definition at line 243 of file list.h.
Referenced by prvAllocateTCBAndStack().
listIS_CONTAINED_WITHIN
#define listIS_CONTAINED_WITHIN (pxList, pxListItem) ((portBASE_TYPE) ((pxListItem)->pvContainer == (void *) (pxList)))
Definition at line 285 of file list.h.
Referenced by prvAllocateTCBAndStack().
listLIST_IS_EMPTY
#define listLIST_IS_EMPTY (pxList) ((portBASE_TYPE) ((pxList)->uxNumberOfItems == (unsigned portBASE_TYPE) 0))
Definition at line 217 of file list.h.
Referenced by prvCheckTasksWaitingTermination(), prvUnlockQueue(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueIsQueueFullFromISR(), xQueueReceiveFromISR(), xTaskIncrementTick(), and xTaskResumeAll().
listLIST_IS_INITIALISED
#define listLIST_IS_INITIALISED (pxList) ((pxList)->xListEnd.xItemValue == portMAX_DELAY)
Definition at line 300 of file list.h.
listLIST_ITEM_CONTAINER
#define listLIST_ITEM_CONTAINER (pxListItem) ((pxListItem)->pvContainer)
Definition at line 293 of file list.h.
Referenced by xTaskIncrementTick().
listSET_LIST_ITEM_OWNER
#define listSET_LIST_ITEM_OWNER (pxListItem, pxOwner) ((pxListItem)->pvOwner = (void *) (pxOwner))
Definition at line 171 of file list.h.
Referenced by prvInitialiseTCBVariables().
listSET_LIST_ITEM_VALUE
#define listSET_LIST_ITEM_VALUE (pxListItem, xValue) ((pxListItem)->xItemValue = (xValue))
Definition at line 189 of file list.h.
Referenced by prvAddCurrentTaskToDelayedList(), prvAllocateTCBAndStack(), and prvInitialiseTCBVariables().
Typedef Documentation
xList
typedef struct xLIST xList
xListItem
typedef struct xLIST_ITEM xListItem
Definition at line 144 of file list.h.
xMiniListItem
typedef struct xMINI_LIST_ITEM xMiniListItem
Definition at line 152 of file list.h.
Function Documentation
uxListRemove()
unsigned portBASE_TYPE uxListRemove (xListItem *const pxItemToRemove)
Definition at line 181 of file list.c.
References xLIST_ITEM::pvContainer, xLIST::pxIndex, xLIST_ITEM::pxNext, xLIST_ITEM::pxPrevious, and xLIST::uxNumberOfItems.
Referenced by prvAllocateTCBAndStack(), prvCheckTasksWaitingTermination(), vTaskPlaceOnEventList(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
vListInitialise()
void vListInitialise (xList *const pxList)
Definition at line 75 of file list.c.
References portBASE_TYPE, portMAX_DELAY, xLIST::pxIndex, xMINI_LIST_ITEM::pxNext, xMINI_LIST_ITEM::pxPrevious, xLIST::uxNumberOfItems, xMINI_LIST_ITEM::xItemValue, and xLIST::xListEnd.
Referenced by prvInitialiseTaskLists(), xQueueGenericCreate(), and xQueueGenericReset().
vListInitialiseItem()
void vListInitialiseItem (xListItem *const pxItem)
Definition at line 95 of file list.c.
References xLIST_ITEM::pvContainer.
Referenced by prvInitialiseTCBVariables().
vListInsert()
void vListInsert (xList *const pxList, xListItem *const pxNewListItem)
Definition at line 123 of file list.c.
References portMAX_DELAY, xLIST_ITEM::pvContainer, xLIST_ITEM::pxNext, xLIST_ITEM::pxPrevious, xMINI_LIST_ITEM::pxPrevious, xLIST::uxNumberOfItems, xLIST_ITEM::xItemValue, and xLIST::xListEnd.
Referenced by prvAddCurrentTaskToDelayedList(), and vTaskPlaceOnEventList().
vListInsertEnd()
void vListInsertEnd (xList *const pxList, xListItem *const pxNewListItem)
Definition at line 102 of file list.c.
References xLIST_ITEM::pvContainer, xLIST::pxIndex, xLIST_ITEM::pxNext, xLIST_ITEM::pxPrevious, and xLIST::uxNumberOfItems.
Referenced by vTaskPlaceOnEventList(), and xTaskRemoveFromEventList().