My FreeRTOS Project: freertos/src/list.c File Reference
list.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "list.h"
Functions
void vListInitialise (xList *const pxList)
void vListInitialiseItem (xListItem *const pxItem)
void vListInsertEnd (xList *const pxList, xListItem *const pxNewListItem)
void vListInsert (xList *const pxList, xListItem *const pxNewListItem)
unsigned portBASE_TYPE uxListRemove (xListItem *const pxItemToRemove)
Function Documentation
uxListRemove()
unsigned portBASE_TYPE uxListRemove (xListItem *const pxItemToRemove)
Definition at line 181 of file list.c.
Referenced by prvAllocateTCBAndStack(), prvCheckTasksWaitingTermination(), vTaskPlaceOnEventList(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
vListInitialise()
void vListInitialise (xList *const pxList)
Definition at line 75 of file list.c.
Referenced by prvInitialiseTaskLists(), xQueueGenericCreate(), and xQueueGenericReset().
vListInitialiseItem()
void vListInitialiseItem (xListItem *const pxItem)
Definition at line 95 of file list.c.
Referenced by prvInitialiseTCBVariables().
vListInsert()
void vListInsert (xList *const pxList, xListItem *const pxNewListItem)
Definition at line 123 of file list.c.
Referenced by prvAddCurrentTaskToDelayedList(), and vTaskPlaceOnEventList().
vListInsertEnd()
void vListInsertEnd (xList *const pxList, xListItem *const pxNewListItem)
Definition at line 102 of file list.c.
Referenced by vTaskPlaceOnEventList(), and xTaskRemoveFromEventList().