My FreeRTOS Project: inc/lz4.h File Reference
lz4.h File Reference
Data Structures
struct LZ4_stream_t
struct LZ4_streamDecode_t
Macros
#define LZ4_VERSION_MAJOR 1 /* for breaking interface changes */
#define LZ4_VERSION_MINOR 7 /* for new (non-breaking) interface capabilities */
#define LZ4_VERSION_RELEASE 1 /* for tweaks, bug-fixes, or development */
#define LZ4_VERSION_NUMBER (LZ4_VERSION_MAJOR *100*100 + LZ4_VERSION_MINOR *100 + LZ4_VERSION_RELEASE)
#define LZ4_MEMORY_USAGE 14
#define LZ4_MAX_INPUT_SIZE 0x7E000000 /* 2 113 929 216 bytes */
#define LZ4_COMPRESSBOUND(isize) ((unsigned)(isize) > (unsigned)LZ4_MAX_INPUT_SIZE ? 0 : (isize) + ((isize)/255) + 16)
#define LZ4_STREAMSIZE_U64 ((1 << (LZ4_MEMORY_USAGE-3)) + 4)
#define LZ4_STREAMSIZE (LZ4_STREAMSIZE_U64 * sizeof(long long))
#define LZ4_STREAMDECODESIZE_U64 4
#define LZ4_STREAMDECODESIZE (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
#define LZ4_DEPRECATE_WARNING_DEFBLOCK
#define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
#define LZ4_DEPRECATED(message)
Functions
int LZ4_versionNumber (void)
int LZ4_compress_default (const char *source, char *dest, int sourceSize, int maxDestSize)
int LZ4_decompress_safe (const char *source, char *dest, int compressedSize, int maxDecompressedSize)
int LZ4_compressBound (int inputSize)
int LZ4_compress_fast (const char *source, char *dest, int sourceSize, int maxDestSize, int acceleration)
int LZ4_sizeofState (void)
int LZ4_compress_fast_extState (void *state, const char *source, char *dest, int inputSize, int maxDestSize, int acceleration)
int LZ4_compress_destSize (const char *source, char *dest, int *sourceSizePtr, int targetDestSize)
int LZ4_decompress_fast (const char *source, char *dest, int originalSize)
int LZ4_decompress_safe_partial (const char *source, char *dest, int compressedSize, int targetOutputSize, int maxDecompressedSize)
void LZ4_resetStream (LZ4_stream_t *streamPtr)
LZ4_stream_t * LZ4_createStream (void)
int LZ4_freeStream (LZ4_stream_t *streamPtr)
int LZ4_loadDict (LZ4_stream_t *streamPtr, const char *dictionary, int dictSize)
int LZ4_compress_fast_continue (LZ4_stream_t *streamPtr, const char *src, char *dst, int srcSize, int maxDstSize, int acceleration)
int LZ4_saveDict (LZ4_stream_t *streamPtr, char *safeBuffer, int dictSize)
LZ4_streamDecode_t * LZ4_createStreamDecode (void)
int LZ4_freeStreamDecode (LZ4_streamDecode_t *LZ4_stream)
int LZ4_setStreamDecode (LZ4_streamDecode_t *LZ4_streamDecode, const char *dictionary, int dictSize)
int LZ4_decompress_safe_continue (LZ4_streamDecode_t *LZ4_streamDecode, const char *source, char *dest, int compressedSize, int maxDecompressedSize)
int LZ4_decompress_fast_continue (LZ4_streamDecode_t *LZ4_streamDecode, const char *source, char *dest, int originalSize)
int LZ4_decompress_safe_usingDict (const char *source, char *dest, int compressedSize, int maxDecompressedSize, const char *dictStart, int dictSize)
int LZ4_decompress_fast_usingDict (const char *source, char *dest, int originalSize, const char *dictStart, int dictSize)
int LZ4_compress (const char *source, char *dest, int sourceSize)
int LZ4_compress_limitedOutput (const char *source, char *dest, int sourceSize, int maxOutputSize)
int LZ4_compress_withState (void *state, const char *source, char *dest, int inputSize)
int LZ4_compress_limitedOutput_withState (void *state, const char *source, char *dest, int inputSize, int maxOutputSize)
int LZ4_compress_continue (LZ4_stream_t *LZ4_streamPtr, const char *source, char *dest, int inputSize)
int LZ4_compress_limitedOutput_continue (LZ4_stream_t *LZ4_streamPtr, const char *source, char *dest, int inputSize, int maxOutputSize)
LZ4_DEPRECATED ("use LZ4_createStream() instead") void *LZ4_create(char *inputBuffer)
LZ4_DEPRECATED ("use LZ4_resetStream() instead") int LZ4_resetStreamState(void *state
LZ4_DEPRECATED ("use LZ4_saveDict() instead") char *LZ4_slideInputBuffer(void *state)
LZ4_DEPRECATED ("use LZ4_decompress_safe_usingDict() instead") int LZ4_decompress_safe_withPrefix64k(const char *src
LZ4_DEPRECATED ("use LZ4_decompress_fast_usingDict() instead") int LZ4_decompress_fast_withPrefix64k(const char *src
Variables
char * inputBuffer
char * dst
char int compressedSize
char int int maxDstSize
char int originalSize
Macro Definition Documentation
LZ4_COMPRESSBOUND
#define LZ4_COMPRESSBOUND (isize) ((unsigned)(isize) > (unsigned)LZ4_MAX_INPUT_SIZE ? 0 : (isize) + ((isize)/255) + 16)
Definition at line 106 of file lz4.h.
Referenced by LZ4_compressBound().
LZ4_DEPRECATE_WARNING_DEFBLOCK
#define LZ4_DEPRECATE_WARNING_DEFBLOCK
Definition at line 314 of file lz4.h.
LZ4_DEPRECATED
#define LZ4_DEPRECATED (message)
Definition at line 324 of file lz4.h.
LZ4_GCC_VERSION
#define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
Definition at line 315 of file lz4.h.
LZ4_MAX_INPUT_SIZE
#define LZ4_MAX_INPUT_SIZE 0x7E000000 /* 2 113 929 216 bytes */
Definition at line 105 of file lz4.h.
Referenced by LZ4_compress_destSize_generic(), and LZ4_compress_generic().
LZ4_MEMORY_USAGE
#define LZ4_MEMORY_USAGE 14
Definition at line 66 of file lz4.h.
LZ4_STREAMDECODESIZE
#define LZ4_STREAMDECODESIZE (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
Definition at line 248 of file lz4.h.
LZ4_STREAMDECODESIZE_U64
#define LZ4_STREAMDECODESIZE_U64 4
Definition at line 247 of file lz4.h.
LZ4_STREAMSIZE
#define LZ4_STREAMSIZE (LZ4_STREAMSIZE_U64 * sizeof(long long))
Definition at line 188 of file lz4.h.
Referenced by LZ4_createStream(), LZ4_init(), LZ4_sizeofState(), and LZ4_sizeofStreamState().
LZ4_STREAMSIZE_U64
#define LZ4_STREAMSIZE_U64 ((1 << (LZ4_MEMORY_USAGE-3)) + 4)
Definition at line 187 of file lz4.h.
Referenced by LZ4_create(), and LZ4_createStream().
LZ4_VERSION_MAJOR
#define LZ4_VERSION_MAJOR 1 /* for breaking interface changes */
Definition at line 50 of file lz4.h.
LZ4_VERSION_MINOR
#define LZ4_VERSION_MINOR 7 /* for new (non-breaking) interface capabilities */
Definition at line 51 of file lz4.h.
LZ4_VERSION_NUMBER
#define LZ4_VERSION_NUMBER (LZ4_VERSION_MAJOR *100*100 + LZ4_VERSION_MINOR *100 + LZ4_VERSION_RELEASE)
Definition at line 53 of file lz4.h.
Referenced by LZ4_versionNumber().
LZ4_VERSION_RELEASE
#define LZ4_VERSION_RELEASE 1 /* for tweaks, bug-fixes, or development */
Definition at line 52 of file lz4.h.
Function Documentation
LZ4_compress()
int LZ4_compress (const char * source, char * dest, int sourceSize)
Definition at line 1491 of file lz4.c.
References LZ4_compress_default(), and LZ4_compressBound().
LZ4_compress_continue()
int LZ4_compress_continue (LZ4_stream_t * LZ4_streamPtr, const char * source, char * dest, int inputSize)
Definition at line 1495 of file lz4.c.
References LZ4_compress_fast_continue(), and LZ4_compressBound().
LZ4_compress_default()
int LZ4_compress_default (const char * source, char * dest, int sourceSize, int maxDestSize)
Definition at line 732 of file lz4.c.
References LZ4_compress_fast().
Referenced by LZ4_compress(), and LZ4_compress_limitedOutput().
LZ4_compress_destSize()
int LZ4_compress_destSize (const char * source, char * dest, int * sourceSizePtr, int targetDestSize)
Definition at line 947 of file lz4.c.
References ALLOCATOR, FREEMEM, and LZ4_compress_destSize_extState().
LZ4_compress_fast()
int LZ4_compress_fast (const char * source, char * dest, int sourceSize, int maxDestSize, int acceleration)
Definition at line 714 of file lz4.c.
References ALLOCATOR, FREEMEM, and LZ4_compress_fast_extState().
Referenced by LZ4_compress_default().
LZ4_compress_fast_continue()
int LZ4_compress_fast_continue (LZ4_stream_t * streamPtr, const char * src, char * dst, int srcSize, int maxDstSize, int acceleration)
Definition at line 1046 of file lz4.c.
References ACCELERATION_DEFAULT, byU32, LZ4_stream_t_internal::currentOffset, LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, dictSmall, LZ4_stream_t_internal::initCheck, KB, limitedOutput, LZ4_compress_generic(), LZ4_renormDictT(), noDictIssue, usingExtDict, and withPrefix64k.
Referenced by LZ4_compress_continue(), and LZ4_compress_limitedOutput_continue().
LZ4_compress_fast_extState()
int LZ4_compress_fast_extState (void * state, const char * source, char * dest, int inputSize, int maxDestSize, int acceleration)
Definition at line 692 of file lz4.c.
References ACCELERATION_DEFAULT, byPtr, byU16, byU32, limitedOutput, LZ4_64bits(), LZ4_64Klimit, LZ4_compress_generic(), LZ4_compressBound(), LZ4_resetStream(), noDict, noDictIssue, and notLimited.
Referenced by LZ4_compress_destSize_extState(), LZ4_compress_fast(), LZ4_compress_limitedOutput_withState(), and LZ4_compress_withState().
LZ4_compress_limitedOutput()
int LZ4_compress_limitedOutput (const char * source, char * dest, int sourceSize, int maxOutputSize)
Definition at line 1490 of file lz4.c.
References LZ4_compress_default().
LZ4_compress_limitedOutput_continue()
int LZ4_compress_limitedOutput_continue (LZ4_stream_t * LZ4_streamPtr, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 1494 of file lz4.c.
References LZ4_compress_fast_continue().
LZ4_compress_limitedOutput_withState()
int LZ4_compress_limitedOutput_withState (void * state, const char * source, char * dest, int inputSize, int maxOutputSize)
Definition at line 1492 of file lz4.c.
References LZ4_compress_fast_extState().
LZ4_compress_withState()
int LZ4_compress_withState (void * state, const char * source, char * dest, int inputSize)
Definition at line 1493 of file lz4.c.
References LZ4_compress_fast_extState(), and LZ4_compressBound().
LZ4_compressBound()
int LZ4_compressBound (int inputSize)
Definition at line 407 of file lz4.c.
References LZ4_COMPRESSBOUND.
Referenced by LZ4_compress(), LZ4_compress_continue(), LZ4_compress_destSize_extState(), LZ4_compress_fast_extState(), and LZ4_compress_withState().
LZ4_createStream()
LZ4_stream_t* LZ4_createStream (void)
Definition at line 970 of file lz4.c.
References ALLOCATOR, LZ4_resetStream(), LZ4_STATIC_ASSERT, LZ4_STREAMSIZE, and LZ4_STREAMSIZE_U64.
LZ4_createStreamDecode()
LZ4_streamDecode_t* LZ4_createStreamDecode (void)
Definition at line 1354 of file lz4.c.
References ALLOCATOR.
LZ4_decompress_fast()
int LZ4_decompress_fast (const char * source, char * dest, int originalSize)
Definition at line 1333 of file lz4.c.
References endOnOutputSize, full, KB, LZ4_decompress_generic(), and withPrefix64k.
Referenced by LZ4_uncompress().
LZ4_decompress_fast_continue()
int LZ4_decompress_fast_continue (LZ4_streamDecode_t * LZ4_streamDecode, const char * source, char * dest, int originalSize)
Definition at line 1419 of file lz4.c.
References endOnOutputSize, LZ4_streamDecode_t_internal::extDictSize, LZ4_streamDecode_t_internal::externalDict, full, LZ4_decompress_generic(), originalSize, LZ4_streamDecode_t_internal::prefixEnd, LZ4_streamDecode_t_internal::prefixSize, and usingExtDict.
LZ4_decompress_fast_usingDict()
int LZ4_decompress_fast_usingDict (const char * source, char * dest, int originalSize, const char * dictStart, int dictSize)
Definition at line 1474 of file lz4.c.
References LZ4_decompress_usingDict_generic().
LZ4_decompress_safe()
int LZ4_decompress_safe (const char * source, char * dest, int compressedSize, int maxDecompressedSize)
Definition at line 1323 of file lz4.c.
References endOnInputSize, full, LZ4_decompress_generic(), and noDict.
Referenced by LZ4_uncompress_unknownOutputSize().
LZ4_decompress_safe_continue()
int LZ4_decompress_safe_continue (LZ4_streamDecode_t * LZ4_streamDecode, const char * source, char * dest, int compressedSize, int maxDecompressedSize)
Definition at line 1390 of file lz4.c.
References endOnInputSize, LZ4_streamDecode_t_internal::extDictSize, LZ4_streamDecode_t_internal::externalDict, full, LZ4_decompress_generic(), LZ4_streamDecode_t_internal::prefixEnd, LZ4_streamDecode_t_internal::prefixSize, and usingExtDict.
LZ4_decompress_safe_partial()
int LZ4_decompress_safe_partial (const char * source, char * dest, int compressedSize, int targetOutputSize, int maxDecompressedSize)
Definition at line 1328 of file lz4.c.
References endOnInputSize, LZ4_decompress_generic(), noDict, and partial.
LZ4_decompress_safe_usingDict()
int LZ4_decompress_safe_usingDict (const char * source, char * dest, int compressedSize, int maxDecompressedSize, const char * dictStart, int dictSize)
Definition at line 1469 of file lz4.c.
References LZ4_decompress_usingDict_generic().
Referenced by Descomprimir().
LZ4_DEPRECATED() [1/5]
LZ4_DEPRECATED ("use LZ4_createStream() instead")
LZ4_DEPRECATED() [2/5]
LZ4_DEPRECATED ("use LZ4_resetStream() instead")
LZ4_DEPRECATED() [3/5]
LZ4_DEPRECATED ("use LZ4_saveDict() instead")
LZ4_DEPRECATED() [4/5]
LZ4_DEPRECATED ("use LZ4_decompress_safe_usingDict() instead") const
LZ4_DEPRECATED() [5/5]
LZ4_DEPRECATED ("use LZ4_decompress_fast_usingDict() instead") const
LZ4_freeStream()
int LZ4_freeStream (LZ4_stream_t * streamPtr)
Definition at line 983 of file lz4.c.
References FREEMEM.
LZ4_freeStreamDecode()
int LZ4_freeStreamDecode (LZ4_streamDecode_t * LZ4_stream)
Definition at line 1360 of file lz4.c.
References FREEMEM.
LZ4_loadDict()
int LZ4_loadDict (LZ4_stream_t * streamPtr, const char * dictionary, int dictSize)
Definition at line 991 of file lz4.c.
References byU32, LZ4_stream_t_internal::currentOffset, LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, GB, HASH_UNIT, LZ4_stream_t_internal::hashTable, LZ4_stream_t_internal::initCheck, KB, LZ4_putPosition(), and LZ4_resetStream().
LZ4_resetStream()
void LZ4_resetStream (LZ4_stream_t * streamPtr)
Definition at line 978 of file lz4.c.
References MEM_INIT.
Referenced by LZ4_compress_destSize_extState(), LZ4_compress_fast_extState(), LZ4_compress_fast_force(), LZ4_createStream(), and LZ4_loadDict().
LZ4_saveDict()
int LZ4_saveDict (LZ4_stream_t * streamPtr, char * safeBuffer, int dictSize)
Definition at line 1118 of file lz4.c.
References LZ4_stream_t_internal::dictionary, LZ4_stream_t_internal::dictSize, and KB.
Referenced by LZ4_slideInputBuffer().
LZ4_setStreamDecode()
int LZ4_setStreamDecode (LZ4_streamDecode_t * LZ4_streamDecode, const char * dictionary, int dictSize)
Definition at line 1373 of file lz4.c.
References LZ4_streamDecode_t_internal::extDictSize, LZ4_streamDecode_t_internal::externalDict, LZ4_streamDecode_t_internal::prefixEnd, and LZ4_streamDecode_t_internal::prefixSize.
LZ4_sizeofState()
int LZ4_sizeofState (void)
Definition at line 408 of file lz4.c.
References LZ4_STREAMSIZE.
LZ4_versionNumber()
int LZ4_versionNumber (void)
Definition at line 406 of file lz4.c.
References LZ4_VERSION_NUMBER.
Variable Documentation
compressedSize
char int compressedSize
Definition at line 354 of file lz4.h.
dst
char * dst
Definition at line 354 of file lz4.h.
Referenced by LZ4_compress_destSize_generic(), and st_clust().
inputBuffer
char* inputBuffer
Definition at line 350 of file lz4.h.
maxDstSize
char int int maxDstSize
Definition at line 354 of file lz4.h.
originalSize
char int originalSize
Definition at line 355 of file lz4.h.
Referenced by LZ4_decompress_fast_continue().