My FreeRTOS Project: Applications/myTasks.c File Reference
myTasks.c File Reference
Todas las tareas del S.O.
#include "myTasks.h"
#include "Shifter.h"
#include "HallSensor.h"
#include "Display.h"
#include "Initializations.h"
#include "InterruptHandler.h"
#include "StatusHandler.h"
#include "myTimers.h"
#include "GPIOLPC1769.h"
#include "SD.h"
Functions
void disk_timerproc ()
void CrearSemaforos (void)
Crea Semaforos necesarios para las tareas del S.O.
void CrearTareas (void)
Crea las tareas requeridas por el S.O.
void vApplicationTickHook (void)
10ms tickhook
void vApplicationIdleHook (void)
Idle Hook from FreeRTOS.
void tPeriodic (void *pv)
Marca cada cuanto pido informacion a la aplicacion de PC.
void tInit (void *pv)
Tarea de inicializacion de software.
void tHallSensor (void *pv)
Task asociada a la interrupcion del sensor hall.
void tRefreshTimerSetup (void *pv)
Configura Timer 1.
void tCargaData (void *pv)
Asociada a la carga del Shifter_t.
void tDescomprimir (void *pv)
Asociada al algoritmo de descompresion.
Variables
xSemaphoreHandle stick
xSemaphoreHandle sHallSensor
xSemaphoreHandle sRefreshTimerSetup
xSemaphoreHandle sCargaData
xSemaphoreHandle sDescomprimir
Detailed Description
Todas las tareas del S.O.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file myTasks.c.
Function Documentation
CrearSemaforos()
void CrearSemaforos (void)
Crea Semaforos necesarios para las tareas del S.O.
Definition at line 62 of file myTasks.c.
References sCargaData, sDescomprimir, sHallSensor, sRefreshTimerSetup, and stick.
Referenced by main().
CrearTareas()
void CrearTareas (void)
Crea las tareas requeridas por el S.O.
Definition at line 81 of file myTasks.c.
References configMINIMAL_STACK_SIZE, tCargaData(), tDescomprimir(), tHallSensor(), tInit(), tPeriodic(), and tRefreshTimerSetup().
Referenced by main().
disk_timerproc()
void disk_timerproc ()
Definition at line 604 of file mmc.c.
References Stat, Timer1, and Timer2.
Referenced by tPeriodic().
tCargaData()
void tCargaData (void * pv)
Asociada a la carga del Shifter_t.
Encargada de desglosar la siguiente linea de la imagen a ser impresa y cargarla como dato futuro en una estructura Shifter_t
Parameters
pv Pointer to void
Definition at line 227 of file myTasks.c.
References CargaData(), and sCargaData.
Referenced by CrearTareas().
tDescomprimir()
void tDescomprimir (void * pv)
Asociada al algoritmo de descompresion.
Parameters
pv Pointer to void
Definition at line 241 of file myTasks.c.
References Descomprimir(), and sDescomprimir.
Referenced by CrearTareas().
tHallSensor()
void tHallSensor (void * pv)
Task asociada a la interrupcion del sensor hall.
Encargada de hacer el sensado de la velocidad del motor.
Parameters
pv
Definition at line 189 of file myTasks.c.
References HallSensorInterrupt(), ON, REFRESHTIMER_ALREADY_SETUP, sHallSensor, and Status_Flags.
Referenced by CrearTareas().
tInit()
void tInit (void * pv)
Tarea de inicializacion de software.
Se ejecuta una unica vez.
Parameters
pv
Definition at line 166 of file myTasks.c.
References CrearHallSensor(), CrearShifter(), DisplaySend(), DisplayStop(), Inicializar(), and SD_Read().
Referenced by CrearTareas().
tPeriodic()
void tPeriodic (void * pv)
Marca cada cuanto pido informacion a la aplicacion de PC.
Parameters
pv Pointer to void
Definition at line 123 of file myTasks.c.
References disk_timerproc(), REFRESH_STREAM_S, stick, and Stream().
Referenced by CrearTareas().
tRefreshTimerSetup()
void tRefreshTimerSetup (void * pv)
Configura Timer 1.
Se ejecuta una unica vez.
Parameters
pv Pointer to void
Definition at line 209 of file myTasks.c.
References RefreshTimerSetup(), and sRefreshTimerSetup.
Referenced by CrearTareas().
vApplicationIdleHook()
void vApplicationIdleHook (void)
Idle Hook from FreeRTOS.
FreeRTOS application idle hook.
La tarea de menor prioridad del sistema. Se encarga de recibir los datos de la aplicacion de PC por bluetooth. Una vez terminado de recibir el paquete comprimido, da semaforo a tDescomprimir.
Definition at line 109 of file myTasks.c.
Referenced by portTASK_FUNCTION().
vApplicationTickHook()
void vApplicationTickHook (void)
10ms tickhook
FreeRTOS application tick hook.
Warning
this is called by an interrupt handler!
Definition at line 96 of file myTasks.c.
Variable Documentation
sCargaData
xSemaphoreHandle sCargaData
Semaforo binario para tCargaData
Definition at line 28 of file myTasks.c.
Referenced by CrearSemaforos(), tCargaData(), and TIMER1_IRQHandler().
sDescomprimir
xSemaphoreHandle sDescomprimir
Semaforo binario para tDescomprimir
Definition at line 28 of file myTasks.c.
Referenced by CrearSemaforos(), SerialManager(), and tDescomprimir().
sHallSensor
xSemaphoreHandle sHallSensor
Semaforo binario para tHallSensor
Definition at line 28 of file myTasks.c.
Referenced by CrearSemaforos(), EINT1_IRQHandler(), and tHallSensor().
sRefreshTimerSetup
xSemaphoreHandle sRefreshTimerSetup
Semaforo binario para tRefreshTimerSetup
Definition at line 28 of file myTasks.c.
Referenced by CrearSemaforos(), HallSensorInterrupt(), and tRefreshTimerSetup().
stick
xSemaphoreHandle stick
Semaforo binario para tPeriodic
Definition at line 28 of file myTasks.c.
Referenced by CrearSemaforos(), tPeriodic(), and vApplicationTickHook().