My FreeRTOS Project: inc/myTimers.h File Reference
myTimers.h File Reference
Asociaciones a Timers.c.
#include "HallSensor.h"
Macros
#define FRECUENCIA_DE_IMPRESION 3300
#define PERIODO_LATCH (100000000/FRECUENCIA_DE_IMPRESION)
#define FILAS_IMAGEN 128
Functions
void InitTimer0 (void)
Inicializa Timer 0.
void InitTimer1 (void)
Inicializa Timer 1.
void TIMER0_IRQHandler (void)
Handler de interrupcion del NVIC del Cortex-M3.
void TIMER1_IRQHandler (void)
Handler de interrupcion del NVIC del Cortex-M3.
void RefreshTimerSetup (HallSensor_t *This_HallSensor)
Configura el Timer 1 con datos del sensor hall.
Detailed Description
Asociaciones a Timers.c.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file myTimers.h.
Macro Definition Documentation
FILAS_IMAGEN
#define FILAS_IMAGEN 128
Cantidad de filas en las que esta dividida la imagen de la aplicacion de PC. Representa tambien la cantidad de veces que las ilera de led debe tener un dato distinto.
Definition at line 38 of file myTimers.h.
Referenced by RefreshTimerSetup().
FRECUENCIA_DE_IMPRESION
#define FRECUENCIA_DE_IMPRESION 3300
Frecuencia en Hertz de muestreo. Definida por el usuario.
Definition at line 26 of file myTimers.h.
PERIODO_LATCH
#define PERIODO_LATCH (100000000/FRECUENCIA_DE_IMPRESION)
Periodo al cual sera seteado el timer de shifteo teniendo en cuenta FRECUENCIA_DE_IMPRESION y la frecuencia a la que trabaja el micro (PLL)
Definition at line 32 of file myTimers.h.
Referenced by InitTimer0().
Function Documentation
InitTimer0()
void InitTimer0 (void)
Inicializa Timer 0.
Encargado de ser el clock de shifteo y latcheo de los C.I. Shifter. Encargado de generar efecto dimmer por PWM en los leds.
Definition at line 37 of file Timers.c.
References CANT_SHIFTERS, CE, ISER0, MR0I, MR0R, MR1I, MYCR, MYPCONP, PCLKSEL0, PERIODO_LATCH, T0CTCR, T0MCR, T0MR0, T0MR1, and T0TCR.
Referenced by Inicializar().
InitTimer1()
void InitTimer1 (void)
Inicializa Timer 1.
Encargado del resfresco de los datos a mostrar. Principio de funcionamiento: Este timer arranca a contar "free wheeling" sin habilitar su interrupcion. Al iniciar el programa, tendra un tiempo de demora hasta que el motor arranque, llegue a una velocidad de trabajo estable, la cual será sensada y calculada por HallSensor_t. La velocidad estable será calculada en base a la cuenta que lleve este timer, traducida y almacenada en HallSensor_t->WorkingFrequency para que a su vez, dicha variable SOBRE ESCRIBIRA los registros T1MR0 y T1MR1 para adecuar los periodos de trabajo a los que se debe realmente refreshear el dato (2,8º)
Notese que la configuracion se realiza solamente sobre el timer 1 y no tambien sobre el timer 0, los cuales logicamente deberian tener algun tipo de relacion. Con esta salvedad se logra independizar la frecuencia de muestreo (asociada al shifteo + pwm) y la frecuencia de refresco (asociada al cambio del dato a imprimir) de la imagen.
Definition at line 78 of file Timers.c.
References CE, MYCR, MYPCONP, PCLKSEL0, T1CTCR, T1MCR, and T1TCR.
Referenced by Inicializar().
RefreshTimerSetup()
void RefreshTimerSetup (HallSensor_t * This_HallSensor)
Configura el Timer 1 con datos del sensor hall.
Una vez detectada una frecuencia estable, re-configura el timer 1 con su nuevo periodo y lo habilita a interrumpir al S.O.
Parameters
This_HallSensor Puntero a la informacion del sensor hall.
Definition at line 165 of file Timers.c.
References CE, FILAS_IMAGEN, ISER0, MR0I, MR0R, MYCR, ON, REFRESHTIMER_ALREADY_SETUP, Status_Flags, T1MCR, T1MR0, T1TCR, and HallSensor::WorkingFrequency.
Referenced by tRefreshTimerSetup().
TIMER0_IRQHandler()
void TIMER0_IRQHandler (void)
Handler de interrupcion del NVIC del Cortex-M3.
Interrupcion del Timer 0 = Timer encargado de la logica de shifteo y latcheo. Que tambien se encarga de cambiar PwmStateIndex (A la frecuencia de latcheo)
Definition at line 103 of file Timers.c.
References CANT_SHIFTERS, IRMR0, IRMR1, LCLK_PIN, PwmStateIndex, SCLK_PIN, SetPIN(), ShiftCounter, ShiftDataInterrupt(), and T0IR.
TIMER1_IRQHandler()
void TIMER1_IRQHandler (void)
Handler de interrupcion del NVIC del Cortex-M3.
Ver descripcion en InitTimer1. Avisa al S.O. del cambio de datos.
Definition at line 146 of file Timers.c.
References IRMR0, RefreshDataInterrupt(), sCargaData, and T1IR.