My FreeRTOS Project: inc/PinoutConfigLPC1769.h File Reference
PinoutConfigLPC1769.h File Reference
Asociaciones a PinoutConfigLPC1769.c.
#include "RegsLPC1769.h"
Functions
void SetPINSEL (uint8_t, uint8_t, uint8_t)
void SetMODE (uint8_t, uint8_t, uint8_t)
Detailed Description
Asociaciones a PinoutConfigLPC1769.c.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file PinoutConfigLPC1769.h.
Function Documentation
SetMODE()
void SetMODE (uint8_t , uint8_t , uint8_t)
Definition at line 33 of file PinoutConfigLPC1769.c.
References MYPINMODE.
Referenced by InitShifter().
SetPINSEL()
void SetPINSEL (uint8_t , uint8_t , uint8_t)
Definition at line 16 of file PinoutConfigLPC1769.c.
References MYPINSEL.
Referenced by ConfigPinBluetooth(), InitHallSensor(), InitShifter(), TestPointInitBT(), TestPointInitGeneral(), and UART_Init().