My FreeRTOS Project: freertos/inc/queue.h File Reference
queue.h File Reference
Macros
#define queueSEND_TO_BACK ((portBASE_TYPE) 0)
#define queueSEND_TO_FRONT ((portBASE_TYPE) 1)
#define queueOVERWRITE ((portBASE_TYPE) 2)
#define queueQUEUE_TYPE_BASE ((unsigned char) 0U)
#define queueQUEUE_TYPE_SET ((unsigned char) 0U)
#define queueQUEUE_TYPE_MUTEX ((unsigned char) 1U)
#define queueQUEUE_TYPE_COUNTING_SEMAPHORE ((unsigned char) 2U)
#define queueQUEUE_TYPE_BINARY_SEMAPHORE ((unsigned char) 3U)
#define queueQUEUE_TYPE_RECURSIVE_MUTEX ((unsigned char) 4U)
#define xQueueCreate(uxQueueLength, uxItemSize) xQueueGenericCreate(uxQueueLength, uxItemSize, queueQUEUE_TYPE_BASE)
#define xQueueSendToFront(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
#define xQueueSendToBack(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueSend(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueOverwrite(xQueue, pvItemToQueue) xQueueGenericSend((xQueue), (pvItemToQueue), 0, queueOVERWRITE)
#define xQueuePeek(xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
#define xQueueReceive(xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
#define xQueueSendToFrontFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_FRONT)
#define xQueueSendToBackFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
#define xQueueOverwriteFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueOVERWRITE)
#define xQueueSendFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
#define xQueueAltSendToFront(xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
#define xQueueAltSendToBack(xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueAltReceive(xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
#define xQueueAltPeek(xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
#define xQueueReset(xQueue) xQueueGenericReset(xQueue, pdFALSE)
Typedefs
typedef void * xQueueHandle
typedef void * xQueueSetHandle
typedef void * xQueueSetMemberHandle
Functions
signed portBASE_TYPE xQueueGenericSend (xQueueHandle xQueue, const void *const pvItemToQueue, portTickType xTicksToWait, portBASE_TYPE xCopyPosition) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueuePeekFromISR (xQueueHandle xQueue, const void *const pvBuffer) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueueGenericReceive (xQueueHandle xQueue, const void *const pvBuffer, portTickType xTicksToWait, portBASE_TYPE xJustPeek) PRIVILEGED_FUNCTION
unsigned portBASE_TYPE uxQueueMessagesWaiting (const xQueueHandle xQueue) PRIVILEGED_FUNCTION
unsigned portBASE_TYPE uxQueueSpacesAvailable (const xQueueHandle xQueue) PRIVILEGED_FUNCTION
void vQueueDelete (xQueueHandle xQueue) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueueGenericSendFromISR (xQueueHandle xQueue, const void *const pvItemToQueue, signed portBASE_TYPE *pxHigherPriorityTaskWoken, portBASE_TYPE xCopyPosition) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueueReceiveFromISR (xQueueHandle xQueue, const void *const pvBuffer, signed portBASE_TYPE *pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueueIsQueueEmptyFromISR (const xQueueHandle xQueue) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueueIsQueueFullFromISR (const xQueueHandle xQueue) PRIVILEGED_FUNCTION
unsigned portBASE_TYPE uxQueueMessagesWaitingFromISR (const xQueueHandle xQueue) PRIVILEGED_FUNCTION
signed portBASE_TYPE xQueueAltGenericSend (xQueueHandle xQueue, const void *const pvItemToQueue, portTickType xTicksToWait, portBASE_TYPE xCopyPosition)
signed portBASE_TYPE xQueueAltGenericReceive (xQueueHandle xQueue, void *const pvBuffer, portTickType xTicksToWait, portBASE_TYPE xJustPeeking)
signed portBASE_TYPE xQueueCRSendFromISR (xQueueHandle xQueue, const void *pvItemToQueue, signed portBASE_TYPE xCoRoutinePreviouslyWoken)
signed portBASE_TYPE xQueueCRReceiveFromISR (xQueueHandle xQueue, void *pvBuffer, signed portBASE_TYPE *pxTaskWoken)
signed portBASE_TYPE xQueueCRSend (xQueueHandle xQueue, const void *pvItemToQueue, portTickType xTicksToWait)
signed portBASE_TYPE xQueueCRReceive (xQueueHandle xQueue, void *pvBuffer, portTickType xTicksToWait)
xQueueHandle xQueueCreateMutex (unsigned char ucQueueType) PRIVILEGED_FUNCTION
xQueueHandle xQueueCreateCountingSemaphore (unsigned portBASE_TYPE uxCountValue, unsigned portBASE_TYPE uxInitialCount) PRIVILEGED_FUNCTION
void * xQueueGetMutexHolder (xQueueHandle xSemaphore) PRIVILEGED_FUNCTION
portBASE_TYPE xQueueTakeMutexRecursive (xQueueHandle xMutex, portTickType xBlockTime) PRIVILEGED_FUNCTION
portBASE_TYPE xQueueGiveMutexRecursive (xQueueHandle pxMutex) PRIVILEGED_FUNCTION
xQueueHandle xQueueGenericCreate (unsigned portBASE_TYPE uxQueueLength, unsigned portBASE_TYPE uxItemSize, unsigned char ucQueueType) PRIVILEGED_FUNCTION
xQueueSetHandle xQueueCreateSet (unsigned portBASE_TYPE uxEventQueueLength) PRIVILEGED_FUNCTION
portBASE_TYPE xQueueAddToSet (xQueueSetMemberHandle xQueueOrSemaphore, xQueueSetHandle xQueueSet) PRIVILEGED_FUNCTION
portBASE_TYPE xQueueRemoveFromSet (xQueueSetMemberHandle xQueueOrSemaphore, xQueueSetHandle xQueueSet) PRIVILEGED_FUNCTION
xQueueSetMemberHandle xQueueSelectFromSet (xQueueSetHandle xQueueSet, portTickType xBlockTimeTicks) PRIVILEGED_FUNCTION
xQueueSetMemberHandle xQueueSelectFromSetFromISR (xQueueSetHandle xQueueSet) PRIVILEGED_FUNCTION
void vQueueWaitForMessageRestricted (xQueueHandle xQueue, portTickType xTicksToWait) PRIVILEGED_FUNCTION
portBASE_TYPE xQueueGenericReset (xQueueHandle xQueue, portBASE_TYPE xNewQueue) PRIVILEGED_FUNCTION
void vQueueSetQueueNumber (xQueueHandle xQueue, unsigned char ucQueueNumber) PRIVILEGED_FUNCTION
unsigned char ucQueueGetQueueNumber (xQueueHandle xQueue) PRIVILEGED_FUNCTION
unsigned char ucQueueGetQueueType (xQueueHandle xQueue) PRIVILEGED_FUNCTION
Macro Definition Documentation
queueOVERWRITE
#define queueOVERWRITE ((portBASE_TYPE) 2)
Definition at line 103 of file queue.h.
Referenced by prvCopyDataToQueue(), xQueueGenericSend(), and xQueueGenericSendFromISR().
queueQUEUE_TYPE_BASE
#define queueQUEUE_TYPE_BASE ((unsigned char) 0U)
Definition at line 106 of file queue.h.
queueQUEUE_TYPE_BINARY_SEMAPHORE
#define queueQUEUE_TYPE_BINARY_SEMAPHORE ((unsigned char) 3U)
Definition at line 110 of file queue.h.
queueQUEUE_TYPE_COUNTING_SEMAPHORE
#define queueQUEUE_TYPE_COUNTING_SEMAPHORE ((unsigned char) 2U)
Definition at line 109 of file queue.h.
Referenced by xQueueGenericCreate().
queueQUEUE_TYPE_MUTEX
#define queueQUEUE_TYPE_MUTEX ((unsigned char) 1U)
Definition at line 108 of file queue.h.
queueQUEUE_TYPE_RECURSIVE_MUTEX
#define queueQUEUE_TYPE_RECURSIVE_MUTEX ((unsigned char) 4U)
Definition at line 111 of file queue.h.
queueQUEUE_TYPE_SET
#define queueQUEUE_TYPE_SET ((unsigned char) 0U)
Definition at line 107 of file queue.h.
Referenced by xQueueIsQueueFullFromISR().
queueSEND_TO_BACK
#define queueSEND_TO_BACK ((portBASE_TYPE) 0)
Definition at line 101 of file queue.h.
Referenced by prvCopyDataToQueue(), prvUnlockQueue(), xQueueGenericCreate(), and xQueueIsQueueFullFromISR().
queueSEND_TO_FRONT
#define queueSEND_TO_FRONT ((portBASE_TYPE) 1)
Definition at line 102 of file queue.h.
xQueueAltPeek
#define xQueueAltPeek (xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
Definition at line 1454 of file queue.h.
xQueueAltReceive
#define xQueueAltReceive (xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
Definition at line 1453 of file queue.h.
xQueueAltSendToBack
#define xQueueAltSendToBack (xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 1452 of file queue.h.
xQueueAltSendToFront
#define xQueueAltSendToFront (xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
Definition at line 1451 of file queue.h.
xQueueCreate
#define xQueueCreate (uxQueueLength, uxItemSize) xQueueGenericCreate(uxQueueLength, uxItemSize, queueQUEUE_TYPE_BASE)
Definition at line 169 of file queue.h.
xQueueOverwrite
#define xQueueOverwrite (xQueue, pvItemToQueue) xQueueGenericSend((xQueue), (pvItemToQueue), 0, queueOVERWRITE)
Definition at line 500 of file queue.h.
xQueueOverwriteFromISR
#define xQueueOverwriteFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueOVERWRITE)
Definition at line 1183 of file queue.h.
xQueuePeek
#define xQueuePeek (xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
Definition at line 684 of file queue.h.
xQueueReceive
#define xQueueReceive (xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
Definition at line 810 of file queue.h.
xQueueReset
#define xQueueReset (xQueue) xQueueGenericReset(xQueue, pdFALSE)
Definition at line 1492 of file queue.h.
xQueueSend
#define xQueueSend (xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 417 of file queue.h.
xQueueSendFromISR
#define xQueueSendFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
Definition at line 1257 of file queue.h.
xQueueSendToBack
#define xQueueSendToBack (xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 333 of file queue.h.
xQueueSendToBackFromISR
#define xQueueSendToBackFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
Definition at line 1096 of file queue.h.
xQueueSendToFront
#define xQueueSendToFront (xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
Definition at line 251 of file queue.h.
xQueueSendToFrontFromISR
#define xQueueSendToFrontFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_FRONT)
Definition at line 1025 of file queue.h.
Typedef Documentation
xQueueHandle
typedef void* xQueueHandle
Type by which queues are referenced. For example, a call to xQueueCreate() returns an xQueueHandle variable that can then be used as a parameter to xQueueSend(), xQueueReceive(), etc.
Definition at line 84 of file queue.h.
xQueueSetHandle
typedef void* xQueueSetHandle
Type by which queue sets are referenced. For example, a call to xQueueCreateSet() returns an xQueueSet variable that can then be used as a parameter to xQueueSelectFromSet(), xQueueAddToSet(), etc.
Definition at line 91 of file queue.h.
xQueueSetMemberHandle
typedef void* xQueueSetMemberHandle
Queue sets can contain both queues and semaphores, so the xQueueSetMemberHandle is defined as a type to be used where a parameter or return value can be either an xQueueHandle or an xSemaphoreHandle.
Definition at line 98 of file queue.h.
Function Documentation
ucQueueGetQueueNumber()
unsigned char ucQueueGetQueueNumber (xQueueHandle xQueue)
Referenced by vQueueDelete().
ucQueueGetQueueType()
unsigned char ucQueueGetQueueType (xQueueHandle xQueue)
Referenced by vQueueDelete().
uxQueueMessagesWaiting()
unsigned portBASE_TYPE uxQueueMessagesWaiting (const xQueueHandle xQueue)
Definition at line 1319 of file queue.c.
References configASSERT, portBASE_TYPE, taskENTER_CRITICAL, and taskEXIT_CRITICAL.
uxQueueMessagesWaitingFromISR()
unsigned portBASE_TYPE uxQueueMessagesWaitingFromISR (const xQueueHandle xQueue)
Definition at line 1349 of file queue.c.
References configASSERT, and portBASE_TYPE.
uxQueueSpacesAvailable()
unsigned portBASE_TYPE uxQueueSpacesAvailable (const xQueueHandle xQueue)
Definition at line 1333 of file queue.c.
References configASSERT, portBASE_TYPE, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
vQueueDelete()
void vQueueDelete (xQueueHandle xQueue)
Definition at line 1361 of file queue.c.
References configASSERT, QueueDefinition::pcHead, traceQUEUE_DELETE, ucQueueGetQueueNumber(), ucQueueGetQueueType(), vPortFree(), vQueueSetQueueNumber(), and vQueueUnregisterQueue.
vQueueSetQueueNumber()
void vQueueSetQueueNumber (xQueueHandle xQueue, unsigned char ucQueueNumber)
Referenced by vQueueDelete().
vQueueWaitForMessageRestricted()
void vQueueWaitForMessageRestricted (xQueueHandle xQueue, portTickType xTicksToWait)
Referenced by xQueueIsQueueFullFromISR().
xQueueAddToSet()
portBASE_TYPE xQueueAddToSet (xQueueSetMemberHandle xQueueOrSemaphore, xQueueSetHandle xQueueSet)
Referenced by xQueueIsQueueFullFromISR().
xQueueAltGenericReceive()
signed portBASE_TYPE xQueueAltGenericReceive (xQueueHandle xQueue, void *const pvBuffer, portTickType xTicksToWait, portBASE_TYPE xJustPeeking)
Referenced by xQueueGenericSend().
xQueueAltGenericSend()
signed portBASE_TYPE xQueueAltGenericSend (xQueueHandle xQueue, const void *const pvItemToQueue, portTickType xTicksToWait, portBASE_TYPE xCopyPosition)
Referenced by xQueueGenericSend().
xQueueCreateCountingSemaphore()
xQueueHandle xQueueCreateCountingSemaphore (unsigned portBASE_TYPE uxCountValue, unsigned portBASE_TYPE uxInitialCount)
Referenced by xQueueGenericCreate().
xQueueCreateMutex()
xQueueHandle xQueueCreateMutex (unsigned char ucQueueType)
Referenced by xQueueGenericCreate().
xQueueCreateSet()
xQueueSetHandle xQueueCreateSet (unsigned portBASE_TYPE uxEventQueueLength)
Referenced by xQueueIsQueueFullFromISR().
xQueueCRReceive()
signed portBASE_TYPE xQueueCRReceive (xQueueHandle xQueue, void * pvBuffer, portTickType xTicksToWait)
Referenced by xQueueIsQueueFullFromISR().
xQueueCRReceiveFromISR()
signed portBASE_TYPE xQueueCRReceiveFromISR (xQueueHandle xQueue, void * pvBuffer, signed portBASE_TYPE * pxTaskWoken)
Referenced by xQueueIsQueueFullFromISR().
xQueueCRSend()
signed portBASE_TYPE xQueueCRSend (xQueueHandle xQueue, const void * pvItemToQueue, portTickType xTicksToWait)
Referenced by xQueueIsQueueFullFromISR().
xQueueCRSendFromISR()
signed portBASE_TYPE xQueueCRSendFromISR (xQueueHandle xQueue, const void * pvItemToQueue, signed portBASE_TYPE xCoRoutinePreviouslyWoken)
Referenced by xQueueIsQueueFullFromISR().
xQueueGenericCreate()
xQueueHandle xQueueGenericCreate (unsigned portBASE_TYPE uxQueueLength, unsigned portBASE_TYPE uxItemSize, unsigned char ucQueueType)
Definition at line 284 of file queue.c.
References configASSERT, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcWriteTo, pdFAIL, pdFALSE, pdPASS, pdTRUE, portBASE_TYPE, pvPortMalloc(), pxMutexHolder, queueMUTEX_GIVE_BLOCK_TIME, queueQUEUE_IS_MUTEX, queueQUEUE_TYPE_COUNTING_SEMAPHORE, queueSEMAPHORE_QUEUE_ITEM_LENGTH, queueSEND_TO_BACK, queueUNLOCKED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceCREATE_COUNTING_SEMAPHORE, traceCREATE_COUNTING_SEMAPHORE_FAILED, traceCREATE_MUTEX, traceCREATE_MUTEX_FAILED, traceGIVE_MUTEX_RECURSIVE, traceGIVE_MUTEX_RECURSIVE_FAILED, traceQUEUE_CREATE, traceQUEUE_CREATE_FAILED, traceTAKE_MUTEX_RECURSIVE, traceTAKE_MUTEX_RECURSIVE_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, uxQueueType, QueueDefinition::uxRecursiveCallCount, vListInitialise(), vPortFree(), xQueueCreateCountingSemaphore(), xQueueCreateMutex(), xQueueGenericCreate(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueGetMutexHolder(), xQueueGiveMutexRecursive(), xQueueTakeMutexRecursive(), QueueDefinition::xRxLock, xTaskGetCurrentTaskHandle(), QueueDefinition::xTasksWaitingToReceive, QueueDefinition::xTasksWaitingToSend, and QueueDefinition::xTxLock.
Referenced by xQueueGenericCreate(), and xQueueIsQueueFullFromISR().
xQueueGenericReceive()
signed portBASE_TYPE xQueueGenericReceive (xQueueHandle xQueue, const void *const pvBuffer, portTickType xTicksToWait, portBASE_TYPE xJustPeek)
Definition at line 1036 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, QueueDefinition::pcReadFrom, pdFALSE, pdPASS, pdTRUE, portBASE_TYPE, portENTER_CRITICAL, portEXIT_CRITICAL, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), queueQUEUE_IS_MUTEX, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_PEEK, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, vTaskPlaceOnEventList(), vTaskPriorityInherit(), vTaskSetTimeOutState(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetCurrentTaskHandle(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueGenericCreate(), and xQueueIsQueueFullFromISR().
xQueueGenericReset()
portBASE_TYPE xQueueGenericReset (xQueueHandle xQueue, portBASE_TYPE xNewQueue)
Definition at line 239 of file queue.c.
References configASSERT, listLIST_IS_EMPTY, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::pcWriteTo, pdFALSE, pdPASS, pdTRUE, portBASE_TYPE, portYIELD_WITHIN_API, queueUNLOCKED, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vListInitialise(), QueueDefinition::xRxLock, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, QueueDefinition::xTasksWaitingToSend, and QueueDefinition::xTxLock.
Referenced by xQueueGenericCreate().
xQueueGenericSend()
signed portBASE_TYPE xQueueGenericSend (xQueueHandle xQueue, const void *const pvItemToQueue, portTickType xTicksToWait, portBASE_TYPE xCopyPosition)
Definition at line 554 of file queue.c.
References configASSERT, errQUEUE_EMPTY, errQUEUE_FULL, listLIST_IS_EMPTY, QueueDefinition::pcReadFrom, pdFALSE, pdPASS, pdTRUE, portBASE_TYPE, portENTER_CRITICAL, portEXIT_CRITICAL, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvCopyDataToQueue(), prvIsQueueEmpty(), prvIsQueueFull(), prvLockQueue, prvUnlockQueue(), queueOVERWRITE, queueQUEUE_IS_MUTEX, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_QUEUE_RECEIVE, traceBLOCKING_ON_QUEUE_SEND, traceQUEUE_PEEK, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, traceQUEUE_SEND, traceQUEUE_SEND_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vTaskPlaceOnEventList(), vTaskPriorityInherit(), vTaskSetTimeOutState(), vTaskSuspendAll(), xQueueAltGenericReceive(), xQueueAltGenericSend(), xTaskCheckForTimeOut(), xTaskGetCurrentTaskHandle(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueGenericCreate().
xQueueGenericSendFromISR()
signed portBASE_TYPE xQueueGenericSendFromISR (xQueueHandle xQueue, const void *const pvItemToQueue, signed portBASE_TYPE * pxHigherPriorityTaskWoken, portBASE_TYPE xCopyPosition)
Definition at line 924 of file queue.c.
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portBASE_TYPE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataToQueue(), queueOVERWRITE, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTxLock.
xQueueGetMutexHolder()
void* xQueueGetMutexHolder (xQueueHandle xSemaphore)
Referenced by xQueueGenericCreate().
xQueueGiveMutexRecursive()
portBASE_TYPE xQueueGiveMutexRecursive (xQueueHandle pxMutex)
Referenced by xQueueGenericCreate().
xQueueIsQueueEmptyFromISR()
signed portBASE_TYPE xQueueIsQueueEmptyFromISR (const xQueueHandle xQueue)
Definition at line 1592 of file queue.c.
References configASSERT, pdFALSE, pdTRUE, portBASE_TYPE, and QueueDefinition::uxMessagesWaiting.
xQueueIsQueueFullFromISR()
signed portBASE_TYPE xQueueIsQueueFullFromISR (const xQueueHandle xQueue)
Definition at line 1631 of file queue.c.
References configASSERT, configQUEUE_REGISTRY_SIZE, errQUEUE_BLOCKED, errQUEUE_FULL, errQUEUE_YIELD, listLIST_IS_EMPTY, memcpy, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, pdFAIL, pdFALSE, pdPASS, pdTRUE, portBASE_TYPE, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, prvCopyDataToQueue(), prvIsQueueFull(), prvLockQueue, prvUnlockQueue(), queueQUEUE_TYPE_SET, queueSEND_TO_BACK, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceQUEUE_SEND, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vCoRoutineAddToDelayedList(), vQueueAddToRegistry, vQueueUnregisterQueue, vQueueWaitForMessageRestricted(), vTaskPlaceOnEventListRestricted(), xCoRoutineRemoveFromEventList(), xQueueAddToSet(), xQueueCreateSet(), xQueueCRReceive(), xQueueCRReceiveFromISR(), xQueueCRSend(), xQueueCRSendFromISR(), xQueueGenericCreate(), xQueueGenericReceive(), xQueueReceiveFromISR(), xQueueRemoveFromSet(), xQueueSelectFromSet(), xQueueSelectFromSetFromISR(), xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
xQueuePeekFromISR()
signed portBASE_TYPE xQueuePeekFromISR (xQueueHandle xQueue, const void *const pvBuffer)
Definition at line 1266 of file queue.c.
References configASSERT, QueueDefinition::pcReadFrom, pdFAIL, pdPASS, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portBASE_TYPE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), traceQUEUE_PEEK_FROM_ISR, traceQUEUE_PEEK_FROM_ISR_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, and QueueDefinition::uxMessagesWaiting.
xQueueReceiveFromISR()
signed portBASE_TYPE xQueueReceiveFromISR (xQueueHandle xQueue, const void *const pvBuffer, signed portBASE_TYPE * pxHigherPriorityTaskWoken)
Definition at line 1191 of file queue.c.
References configASSERT, listLIST_IS_EMPTY, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portBASE_TYPE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), queueUNLOCKED, traceQUEUE_RECEIVE_FROM_ISR, traceQUEUE_RECEIVE_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, QueueDefinition::xRxLock, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToSend.
Referenced by xQueueIsQueueFullFromISR().
xQueueRemoveFromSet()
portBASE_TYPE xQueueRemoveFromSet (xQueueSetMemberHandle xQueueOrSemaphore, xQueueSetHandle xQueueSet)
Referenced by xQueueIsQueueFullFromISR().
xQueueSelectFromSet()
xQueueSetMemberHandle xQueueSelectFromSet (xQueueSetHandle xQueueSet, portTickType xBlockTimeTicks)
Referenced by xQueueIsQueueFullFromISR().
xQueueSelectFromSetFromISR()
xQueueSetMemberHandle xQueueSelectFromSetFromISR (xQueueSetHandle xQueueSet)
Referenced by xQueueIsQueueFullFromISR().
xQueueTakeMutexRecursive()
portBASE_TYPE xQueueTakeMutexRecursive (xQueueHandle xMutex, portTickType xBlockTime)
Referenced by xQueueGenericCreate().