My FreeRTOS Project: inc/SD.h File Reference
SD.h File Reference
Asociaciones a SD.c.
Macros
#define FILENAME "matriz.txt"
#define filas 32
#define columnas 128
Functions
void SD_Read ()
Carga la mariz de la imagen desde un archivo.txt.
Detailed Description
Asociaciones a SD.c.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file SD.h.
Macro Definition Documentation
columnas
#define columnas 128
Definition at line 19 of file SD.h.
Referenced by SD_Read().
filas
#define filas 32
Definition at line 18 of file SD.h.
Referenced by SD_Read().
FILENAME
#define FILENAME "matriz.txt"
Definition at line 17 of file SD.h.
Referenced by SD_Read().
Function Documentation
SD_Read()
void SD_Read ()
Carga la mariz de la imagen desde un archivo.txt.
El archivo debe contener en texto plano la informacion de la matriz imagen lista para ser leida y copiada al buffer en RAM.
Definition at line 30 of file SD.c.
References Buffer::Buffers, columnas, f_close(), f_mount(), f_open(), f_read(), filas, FILENAME, fp, fs, and Image.
Referenced by SerialManager(), and tInit().