My FreeRTOS Project: Drivers/Serial.c File Reference
Serial.c File Reference
Primitiva de comunicación serie.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <Serial.h>
#include "InterruptHandler.h"
#include "StatusHandler.h"
#include "Bluetooth.h"
#include "GPIOLPC1769.h"
#include "SD.h"
#include "FreeRTOS.h"
#include "semphr.h"
#include "myTasks.h"
Macros
#define HEADER 0
#define DATA 1
Functions
static uint8_t PushRx (uint8_t data)
static uint8_t PopTx (uint8_t *data)
void Serial_RxIntHandler (void)
void Serial_TxIntHandler (void)
uint8_t Serial_PopRx (uint8_t *data)
uint8_t Serial_PushTx (uint8_t data)
void SerialManager (void)
Encargada de recibir los datos del bluetooth.
Variables
struct Buffer Image ={0}
uint8_t g_txBuffer [TXBUFFER_SIZE]
uint8_t g_rxBuffer [RXBUFFER_SIZE]
uint8_t g_txIn
uint8_t g_txOut
uint8_t g_rxIn
uint8_t g_rxOut
uint8_t g_txBufferCount = 0
uint8_t g_rxBufferCount = 0
static uint8_t g_txStart = 0
Detailed Description
Primitiva de comunicación serie.
buffers de RX y TX protegidos
Author
Pablo Irrera Condines
Date
2013.05.08
Definition in file Serial.c.
Macro Definition Documentation
DATA
#define DATA 1
Definition at line 27 of file Serial.c.
Referenced by SerialManager().
HEADER
#define HEADER 0
Definition at line 26 of file Serial.c.
Referenced by SerialManager().
Function Documentation
PopTx()
static uint8_t PopTx (uint8_t * data) static
Definition at line 63 of file Serial.c.
References g_txBuffer, g_txBufferCount, g_txOut, and TXBUFFER_SIZE.
Referenced by Serial_TxIntHandler().
PushRx()
static uint8_t PushRx (uint8_t data) static
Definition at line 50 of file Serial.c.
References g_rxBuffer, g_rxBufferCount, g_rxIn, and RXBUFFER_SIZE.
Referenced by Serial_RxIntHandler().
Serial_PopRx()
uint8_t Serial_PopRx (uint8_t * data)
Definition at line 95 of file Serial.c.
References g_rxBuffer, g_rxBufferCount, g_rxOut, and RXBUFFER_SIZE.
Referenced by SerialManager().
Serial_PushTx()
uint8_t Serial_PushTx (uint8_t data)
Definition at line 108 of file Serial.c.
References g_txBuffer, g_txBufferCount, g_txIn, g_txStart, Serial_TxIntHandler(), and TXBUFFER_SIZE.
Referenced by MandarAT(), and Stream().
Serial_RxIntHandler()
void Serial_RxIntHandler (void)
Definition at line 77 of file Serial.c.
References PushRx(), and UART_ReceiveByte().
Referenced by UART0_IRQHandler().
Serial_TxIntHandler()
void Serial_TxIntHandler (void)
Definition at line 84 of file Serial.c.
References g_txStart, PopTx(), and UART_SendByte().
Referenced by Serial_PushTx(), and UART0_IRQHandler().
SerialManager()
void SerialManager (void)
Encargada de recibir los datos del bluetooth.
Returns
void
Definition at line 135 of file Serial.c.
References BT_CONNECTED, DATA, GetPIN(), HEADER, ON, SD_Read(), sDescomprimir, Serial_PopRx(), STATE_PIN, Status_Flags, STREAM, Buffer::Stream_Buffer, and Buffer::Stream_Size.
Referenced by vApplicationIdleHook().
Variable Documentation
g_rxBuffer
uint8_t g_rxBuffer[RXBUFFER_SIZE]
Definition at line 35 of file Serial.c.
Referenced by PushRx(), and Serial_PopRx().
g_rxBufferCount
uint8_t g_rxBufferCount = 0
Definition at line 42 of file Serial.c.
Referenced by PushRx(), and Serial_PopRx().
g_rxIn
uint8_t g_rxIn
Definition at line 40 of file Serial.c.
Referenced by PushRx().
g_rxOut
uint8_t g_rxOut
Definition at line 40 of file Serial.c.
Referenced by Serial_PopRx().
g_txBuffer
uint8_t g_txBuffer[TXBUFFER_SIZE]
Definition at line 33 of file Serial.c.
Referenced by PopTx(), and Serial_PushTx().
g_txBufferCount
uint8_t g_txBufferCount = 0
Definition at line 42 of file Serial.c.
Referenced by PopTx(), and Serial_PushTx().
g_txIn
uint8_t g_txIn
Definition at line 38 of file Serial.c.
Referenced by Serial_PushTx().
g_txOut
uint8_t g_txOut
Definition at line 38 of file Serial.c.
Referenced by PopTx().
g_txStart
uint8_t g_txStart = 0 static
Definition at line 45 of file Serial.c.
Referenced by Serial_PushTx(), and Serial_TxIntHandler().
Image
struct Buffer Image ={0}
Definition at line 30 of file Serial.c.
Referenced by CargaData(), Descomprimir(), and SD_Read().