My FreeRTOS Project: inc/Serial.h File Reference
Serial.h File Reference
#include "UART.h"
#include "lz4.h"
Data Structures
struct Buffer
Buffer de descompresion.
Macros
#define TXBUFFER_SIZE 200
#define RXBUFFER_SIZE 200
#define CANT 3
#define N_LEDS 32
#define N_CIR N_LEDS*4
#define N_PIX N_LEDS * N_CIR
#define IW (Image.Buffer_Index)
#define MYIR ((Image.Buffer_Index + 1) % 2)
Functions
uint8_t Serial_PushTx (uint8_t dato)
uint8_t Serial_PopRx (uint8_t *dato)
uint8_t Serial_Send (const uint8_t *buffer, uint8_t count)
void Serial_RxIntHandler (void)
void Serial_TxIntHandler (void)
void SerialManager (void)
Encargada de recibir los datos del bluetooth.
Variables
struct Buffer Image
Macro Definition Documentation
CANT
#define CANT 3
Definition at line 16 of file Serial.h.
IW
#define IW (Image.Buffer_Index)
Definition at line 30 of file Serial.h.
Referenced by Descomprimir().
MYIR
#define MYIR ((Image.Buffer_Index + 1) % 2)
Definition at line 31 of file Serial.h.
Referenced by CargaData(), and Descomprimir().
N_CIR
#define N_CIR N_LEDS*4
Definition at line 28 of file Serial.h.
Referenced by CargaData().
N_LEDS
#define N_LEDS 32
Definition at line 27 of file Serial.h.
Referenced by CargaData().
N_PIX
#define N_PIX N_LEDS * N_CIR
Definition at line 29 of file Serial.h.
Referenced by Descomprimir().
RXBUFFER_SIZE
#define RXBUFFER_SIZE 200
Definition at line 15 of file Serial.h.
Referenced by PushRx(), and Serial_PopRx().
TXBUFFER_SIZE
#define TXBUFFER_SIZE 200
Definition at line 14 of file Serial.h.
Referenced by PopTx(), and Serial_PushTx().
Function Documentation
Serial_PopRx()
uint8_t Serial_PopRx (uint8_t * dato)
Definition at line 95 of file Serial.c.
References g_rxBuffer, g_rxBufferCount, g_rxOut, and RXBUFFER_SIZE.
Referenced by SerialManager().
Serial_PushTx()
uint8_t Serial_PushTx (uint8_t dato)
Definition at line 108 of file Serial.c.
References g_txBuffer, g_txBufferCount, g_txIn, g_txStart, Serial_TxIntHandler(), and TXBUFFER_SIZE.
Referenced by MandarAT(), and Stream().
Serial_RxIntHandler()
void Serial_RxIntHandler (void)
Definition at line 77 of file Serial.c.
References PushRx(), and UART_ReceiveByte().
Referenced by UART0_IRQHandler().
Serial_Send()
uint8_t Serial_Send (const uint8_t * buffer, uint8_t count)
Serial_TxIntHandler()
void Serial_TxIntHandler (void)
Definition at line 84 of file Serial.c.
References g_txStart, PopTx(), and UART_SendByte().
Referenced by Serial_PushTx(), and UART0_IRQHandler().
SerialManager()
void SerialManager (void)
Encargada de recibir los datos del bluetooth.
Returns
void
Definition at line 135 of file Serial.c.
References BT_CONNECTED, DATA, GetPIN(), HEADER, ON, SD_Read(), sDescomprimir, Serial_PopRx(), STATE_PIN, Status_Flags, STREAM, Buffer::Stream_Buffer, and Buffer::Stream_Size.
Referenced by vApplicationIdleHook().
Variable Documentation
Image
struct Buffer Image
Definition at line 30 of file Serial.c.
Referenced by CargaData(), Descomprimir(), and SD_Read().