My FreeRTOS Project: Drivers/Shifter.c File Reference
Shifter.c File Reference
Funcionalidades de los C.I. Shifter.
#include "Shifter.h"
#include "GPIOLPC1769.h"
#include "PinoutConfigLPC1769.h"
#include "InterruptHandler.h"
#include "FreeRTOS.h"
#include "semphr.h"
#include "myTasks.h"
Functions
void InitShifter (void)
Inicializa el hardware asociado a los shifters.
void CrearShifter (Shifter_t **ShifterHEAD)
Crea y aloja en RAM estatica la memoria necesaria.
void EliminarShifter (Shifter_t **ShifterHEAD)
Elimina la memoria previamente alojada.
void ShiftDataInterrupt (Shifter_t *This_Shifter)
Transfiere la informacion en memoria a los pines fisicos.
void RefreshDataInterrupt (Shifter_t *This_Shifter)
Actualiza el dato a imprimir desde el dato futuro almacenado.
Variables
int ShiftCounter
int PwmStateIndex
Shifter_t * Shifter
Global Pointer to a Shifter_t.
Detailed Description
Funcionalidades de los C.I. Shifter.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Castro Germán
Date
07-Dic-2018
Definition in file Shifter.c.
Function Documentation
CrearShifter()
void CrearShifter (Shifter_t ** ShifterHEAD)
Crea y aloja en RAM estatica la memoria necesaria.
Parameters
ShifterHEAD Direccion del puntero
Returns
void
Definition at line 73 of file Shifter.c.
References Shifter::DataSource, and pvPortMalloc().
Referenced by tInit().
EliminarShifter()
void EliminarShifter (Shifter_t ** ShifterHEAD)
Elimina la memoria previamente alojada.
Parameters
ShifterHEAD Direccion del puntero
Returns
void
Definition at line 88 of file Shifter.c.
References vPortFree().
InitShifter()
void InitShifter (void)
Inicializa el hardware asociado a los shifters.
Returns
void
Definition at line 43 of file Shifter.c.
References D0_PIN, D1_PIN, D2_PIN, D3_PIN, LCLK_PIN, SCLK_PIN, SetDIR(), SetMODE(), and SetPINSEL().
Referenced by Inicializar().
RefreshDataInterrupt()
void RefreshDataInterrupt (Shifter_t * This_Shifter)
Actualiza el dato a imprimir desde el dato futuro almacenado.
La dispara un timer cuyo periodo fue previamente seteado por el sensor hall. Encargada de copiar el buffer que la aplicacion cargo en un Shifter_t.
Parameters
This_Shifter Puntero a la informacion de los shifters.
Returns
void
Definition at line 116 of file Shifter.c.
References Shifter::Data, Shifter::DataSource, FILAS_SHIFTERS, and PWM_STATE.
Referenced by TIMER1_IRQHandler().
ShiftDataInterrupt()
void ShiftDataInterrupt (Shifter_t * This_Shifter)
Transfiere la informacion en memoria a los pines fisicos.
Parameters
This_Shifter Direccion de memoria de la informacion a transferir.
Returns
void
Definition at line 100 of file Shifter.c.
References D0_PIN, D1_PIN, D2_PIN, D3_PIN, Shifter::Data, PwmStateIndex, SetPIN(), and ShiftCounter.
Referenced by TIMER0_IRQHandler().
Variable Documentation
PwmStateIndex
int PwmStateIndex
Index de estado de PWM
Definition at line 28 of file Shifter.c.
Referenced by PrintStart(), ShiftDataInterrupt(), and TIMER0_IRQHandler().
ShiftCounter
int ShiftCounter
Index de shifteo
Definition at line 27 of file Shifter.c.
Referenced by PrintStop(), ShiftDataInterrupt(), and TIMER0_IRQHandler().
Shifter
Shifter
Global Pointer to a Shifter_t.
El puntero principal que maneja la info de los shifters.
Definition at line 36 of file Shifter.c.