My FreeRTOS Project: freertos/src/tasks.c File Reference
tasks.c File Reference
#include <stdlib.h>
#include <string.h>
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
#include "StackMacros.h"
Data Structures
struct tskTaskControlBlock
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define tskIDLE_STACK_SIZE configMINIMAL_STACK_SIZE
#define tskSTACK_FILL_BYTE (0xa5U)
#define tskBLOCKED_CHAR ((signed char) 'B')
#define tskREADY_CHAR ((signed char) 'R')
#define tskDELETED_CHAR ((signed char) 'D')
#define tskSUSPENDED_CHAR ((signed char) 'S')
#define taskRECORD_READY_PRIORITY(uxPriority)
#define taskSELECT_HIGHEST_PRIORITY_TASK()
#define taskRESET_READY_PRIORITY(uxPriority)
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
#define taskSWITCH_DELAYED_LISTS()
#define prvAddTaskToReadyList(pxTCB)
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? (tskTCB *) pxCurrentTCB : (tskTCB *) (pxHandle))
Typedefs
typedef struct tskTaskControlBlock tskTCB
Functions
void vApplicationStackOverflowHook (xTaskHandle xTask, signed char *pcTaskName)
FreeRTOS stack overflow hook.
void vApplicationTickHook (void)
10ms tickhook
static void prvInitialiseTCBVariables (tskTCB *pxTCB, const signed char *const pcName, unsigned portBASE_TYPE uxPriority, const xMemoryRegion *const xRegions, unsigned short usStackDepth) PRIVILEGED_FUNCTION
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void)
void vTaskStartScheduler (void)
void vTaskEndScheduler (void)
void vTaskSuspendAll (void)
signed portBASE_TYPE xTaskResumeAll (void)
portTickType xTaskGetTickCount (void)
portTickType xTaskGetTickCountFromISR (void)
unsigned portBASE_TYPE uxTaskGetNumberOfTasks (void)
portBASE_TYPE xTaskIncrementTick (void)
void vTaskSwitchContext (void)
void vTaskPlaceOnEventList (xList *const pxEventList, portTickType xTicksToWait)
signed portBASE_TYPE xTaskRemoveFromEventList (const xList *const pxEventList)
void vTaskSetTimeOutState (xTimeOutType *const pxTimeOut)
portBASE_TYPE xTaskCheckForTimeOut (xTimeOutType *const pxTimeOut, portTickType *const pxTicksToWait)
void vTaskMissedYield (void)
static portTASK_FUNCTION (prvIdleTask, pvParameters)
static void prvInitialiseTaskLists (void)
static void prvCheckTasksWaitingTermination (void)
static void prvAddCurrentTaskToDelayedList (portTickType xTimeToWake)
static tskTCB * prvAllocateTCBAndStack (unsigned short usStackDepth, portSTACK_TYPE *puxStackBuffer)
Variables
PRIVILEGED_DATA tskTCB *volatile pxCurrentTCB = NULL
static PRIVILEGED_DATA xList pxReadyTasksLists [configMAX_PRIORITIES]
static PRIVILEGED_DATA xList xDelayedTaskList1
static PRIVILEGED_DATA xList xDelayedTaskList2
static PRIVILEGED_DATA xList *volatile pxDelayedTaskList
static PRIVILEGED_DATA xList *volatile pxOverflowDelayedTaskList
static PRIVILEGED_DATA xList xPendingReadyList
static PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxCurrentNumberOfTasks = (unsigned portBASE_TYPE) 0U
static PRIVILEGED_DATA volatile portTickType xTickCount = (portTickType) 0U
static PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxTopReadyPriority = tskIDLE_PRIORITY
static PRIVILEGED_DATA volatile signed portBASE_TYPE xSchedulerRunning = pdFALSE
static PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxSchedulerSuspended = (unsigned portBASE_TYPE) pdFALSE
static PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxPendedTicks = (unsigned portBASE_TYPE) 0U
static PRIVILEGED_DATA volatile portBASE_TYPE xYieldPending = pdFALSE
static PRIVILEGED_DATA volatile portBASE_TYPE xNumOfOverflows = (portBASE_TYPE) 0
static PRIVILEGED_DATA unsigned portBASE_TYPE uxTaskNumber = (unsigned portBASE_TYPE) 0U
static PRIVILEGED_DATA volatile portTickType xNextTaskUnblockTime = portMAX_DELAY
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 73 of file tasks.c.
portRESET_READY_PRIORITY
#define portRESET_READY_PRIORITY (uxPriority, uxTopReadyPriority)
Definition at line 282 of file tasks.c.
Referenced by vTaskPlaceOnEventList().
prvAddTaskToReadyList
#define prvAddTaskToReadyList (pxTCB)
Value:
traceMOVED_TASK_TO_READY_STATE(pxTCB)                                                                         \
    taskRECORD_READY_PRIORITY( ( pxTCB )->uxPriority );                                                             \
    vListInsertEnd( &( pxReadyTasksLists[ ( pxTCB )->uxPriority ] ), &( ( pxTCB )->xGenericListItem ) )
Definition at line 362 of file tasks.c.
Referenced by prvAllocateTCBAndStack(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
prvGetTCBFromHandle
#define prvGetTCBFromHandle (pxHandle) (((pxHandle) == NULL) ? (tskTCB *) pxCurrentTCB : (tskTCB *) (pxHandle))
Definition at line 374 of file tasks.c.
Referenced by prvAllocateTCBAndStack(), prvInitialiseTCBVariables(), and uxTaskGetNumberOfTasks().
taskRECORD_READY_PRIORITY
#define taskRECORD_READY_PRIORITY (uxPriority)
Value:
{                                                                                                                   \
        if( ( uxPriority ) > uxTopReadyPriority )                                                                       \
        {                                                                                                               \
            uxTopReadyPriority = ( uxPriority );                                                                        \
        }                                                                                                               \
    } /* taskRECORD_READY_PRIORITY */
Definition at line 252 of file tasks.c.
taskRESET_READY_PRIORITY
#define taskRESET_READY_PRIORITY (uxPriority)
Definition at line 281 of file tasks.c.
Referenced by prvAllocateTCBAndStack().
taskSELECT_HIGHEST_PRIORITY_TASK
#define taskSELECT_HIGHEST_PRIORITY_TASK ()
Value:
{                                                                                                                   \
        /* Find the highest priority queue that contains ready tasks. */                                                \
        while( listLIST_IS_EMPTY( &( pxReadyTasksLists[ uxTopReadyPriority ] ) ) )                                      \
        {                                                                                                               \
            configASSERT( uxTopReadyPriority );                                                                         \
            --uxTopReadyPriority;                                                                                       \
        }                                                                                                               \
                                                                                                                        \
        /* listGET_OWNER_OF_NEXT_ENTRY indexes through the list, so the tasks of                                        \
        the same priority get an equal share of the processor time. */                                                  \
        listGET_OWNER_OF_NEXT_ENTRY( pxCurrentTCB, &( pxReadyTasksLists[ uxTopReadyPriority ] ) );                      \
    } /* taskSELECT_HIGHEST_PRIORITY_TASK */
Definition at line 262 of file tasks.c.
Referenced by vTaskSwitchContext().
taskSWITCH_DELAYED_LISTS
#define taskSWITCH_DELAYED_LISTS ()
Value:
{                                                                                                   \
    xList *pxTemp;                                                                                  \
                                                                                                    \
    /* The delayed tasks list should be empty when the lists are switched. */                       \
    configASSERT( ( listLIST_IS_EMPTY( pxDelayedTaskList ) ) );                                     \
                                                                                                    \
    pxTemp = pxDelayedTaskList;                                                                     \
    pxDelayedTaskList = pxOverflowDelayedTaskList;                                                  \
    pxOverflowDelayedTaskList = pxTemp;                                                             \
    xNumOfOverflows++;                                                                              \
                                                                                                    \
    if( listLIST_IS_EMPTY( pxDelayedTaskList ) != pdFALSE )                                         \
    {                                                                                               \
        /* The new current delayed list is empty.  Set                                              \
        xNextTaskUnblockTime to the maximum possible value so it is                                 \
        extremely unlikely that the                                                                 \
        if( xTickCount >= xNextTaskUnblockTime ) test will pass until                               \
        there is an item in the delayed list. */                                                    \
        xNextTaskUnblockTime = portMAX_DELAY;                                                       \
    }                                                                                               \
    else                                                                                            \
    {                                                                                               \
        /* The new current delayed list is not empty, get the value of                              \
        the item at the head of the delayed list.  This is the time at                              \
        which the task at the head of the delayed list should be removed                            \
        from the Blocked state. */                                                                  \
        pxTCB = ( tskTCB * ) listGET_OWNER_OF_HEAD_ENTRY( pxDelayedTaskList );                      \
        xNextTaskUnblockTime = listGET_LIST_ITEM_VALUE( &( pxTCB->xGenericListItem ) );             \
    }                                                                                               \
}
Definition at line 324 of file tasks.c.
Referenced by xTaskIncrementTick().
tskBLOCKED_CHAR
#define tskBLOCKED_CHAR ((signed char) 'B')
Definition at line 237 of file tasks.c.
Referenced by prvAllocateTCBAndStack().
tskDELETED_CHAR
#define tskDELETED_CHAR ((signed char) 'D')
Definition at line 239 of file tasks.c.
Referenced by prvAllocateTCBAndStack().
tskIDLE_STACK_SIZE
#define tskIDLE_STACK_SIZE configMINIMAL_STACK_SIZE
Definition at line 105 of file tasks.c.
Referenced by vTaskStartScheduler().
tskREADY_CHAR
#define tskREADY_CHAR ((signed char) 'R')
Definition at line 238 of file tasks.c.
Referenced by prvAllocateTCBAndStack().
tskSTACK_FILL_BYTE
#define tskSTACK_FILL_BYTE (0xa5U)
Definition at line 232 of file tasks.c.
Referenced by prvAllocateTCBAndStack().
tskSUSPENDED_CHAR
#define tskSUSPENDED_CHAR ((signed char) 'S')
Definition at line 240 of file tasks.c.
Referenced by prvAllocateTCBAndStack().
Typedef Documentation
tskTCB
typedef struct tskTaskControlBlock tskTCB
Function Documentation
portTASK_FUNCTION()
static portTASK_FUNCTION (prvIdleTask , pvParameters) static
Definition at line 2128 of file tasks.c.
References prvCheckTasksWaitingTermination(), pxReadyTasksLists, uxCurrentNumberOfTasks, vApplicationIdleHook(), vTaskSuspendAll(), xNextTaskUnblockTime, xPendingReadyList, xTaskResumeAll(), xTickCount, and xYieldPending.
prvAddCurrentTaskToDelayedList()
static void prvAddCurrentTaskToDelayedList (portTickType xTimeToWake) static
Definition at line 2426 of file tasks.c.
References pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, vListInsert(), tskTaskControlBlock::xGenericListItem, xNextTaskUnblockTime, and xTickCount.
Referenced by vTaskPlaceOnEventList().
prvAllocateTCBAndStack()
static tskTCB* prvAllocateTCBAndStack (unsigned short usStackDepth, portSTACK_TYPE * puxStackBuffer) static
Definition at line 2452 of file tasks.c.
References tskTaskControlBlock::pcTaskName, prvAddTaskToReadyList, prvGetTCBFromHandle, pvPortMalloc(), pxCurrentTCB, pxMutexHolder, pxReadyTasksLists, tskTaskControlBlock::pxStack, taskRESET_READY_PRIORITY, tskBLOCKED_CHAR, tskDELETED_CHAR, tskREADY_CHAR, tskSTACK_FILL_BYTE, tskSUSPENDED_CHAR, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vPortFree(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, and xSchedulerRunning.
prvCheckTasksWaitingTermination()
static void prvCheckTasksWaitingTermination (void) static
Definition at line 2391 of file tasks.c.
References uxCurrentNumberOfTasks, uxListRemove(), vTaskSuspendAll(), tskTaskControlBlock::xGenericListItem, and xTaskResumeAll().
Referenced by portTASK_FUNCTION().
prvInitialiseTaskLists() [1/2]
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void) static
Definition at line 392 of file tasks.c.
prvInitialiseTaskLists() [2/2]
static void prvInitialiseTaskLists (void) static
Definition at line 2359 of file tasks.c.
References pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskTaskControlBlock::uxPriority, vListInitialise(), xDelayedTaskList1, xDelayedTaskList2, and xPendingReadyList.
prvInitialiseTCBVariables()
static void prvInitialiseTCBVariables (tskTCB * pxTCB, const signed char *const pcName, unsigned portBASE_TYPE uxPriority, const xMemoryRegion *const xRegions, unsigned short usStackDepth) static
Definition at line 2259 of file tasks.c.
References configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, tskTaskControlBlock::pcTaskName, prvGetTCBFromHandle, tskTaskControlBlock::pxStack, tskTaskControlBlock::uxPriority, vListInitialiseItem(), tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xGenericListItem.
uxTaskGetNumberOfTasks()
unsigned portBASE_TYPE uxTaskGetNumberOfTasks (void)
Definition at line 1458 of file tasks.c.
References configMAX_PRIORITIES, tskTaskControlBlock::pcTaskName, prvGetTCBFromHandle, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, uxCurrentNumberOfTasks, vTaskSuspendAll(), xNextTaskUnblockTime, xTaskResumeAll(), and xTickCount.
vApplicationStackOverflowHook()
void vApplicationStackOverflowHook (xTaskHandle xTask, signed char * pcTaskName)
FreeRTOS stack overflow hook.
Parameters
pxTask : Task handle that overflowed stack
pcTaskName : Task name that overflowed stack
Returns
Nothing
Note
This function is alled when a stack overflow occurs.
Definition at line 84 of file FreeRTOSCommonHooks.c.
vApplicationTickHook()
void vApplicationTickHook (void)
10ms tickhook
FreeRTOS application tick hook.
Warning
this is called by an interrupt handler!
10ms tickhook
Returns
Nothing
Note
This just returns to the caller.
FreeRTOS application tick hook.
Warning
this is called by an interrupt handler!
Definition at line 96 of file myTasks.c.
References stick.
Referenced by xTaskIncrementTick().
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 1299 of file tasks.c.
References vPortEndScheduler(), and xSchedulerRunning.
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 2073 of file tasks.c.
References xYieldPending.
Referenced by prvUnlockQueue().
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (xList *const pxEventList, portTickType xTicksToWait)
Definition at line 1868 of file tasks.c.
References portRESET_READY_PRIORITY, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, vListInsert(), vListInsertEnd(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, and xTickCount.
Referenced by xQueueGenericReceive(), and xQueueGenericSend().
vTaskSetTimeOutState()
void vTaskSetTimeOutState (xTimeOutType *const pxTimeOut)
Definition at line 2016 of file tasks.c.
References xNumOfOverflows, and xTickCount.
Referenced by xQueueGenericReceive(), xQueueGenericSend(), and xTaskCheckForTimeOut().
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1225 of file tasks.c.
References pxCurrentTCB, tskIDLE_STACK_SIZE, xPortStartScheduler(), xSchedulerRunning, and xTickCount.
Referenced by main().
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 1310 of file tasks.c.
References pxCurrentTCB, pxReadyTasksLists, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, xNextTaskUnblockTime, and xTickCount.
Referenced by portTASK_FUNCTION(), prvCheckTasksWaitingTermination(), pvPortMalloc(), uxTaskGetNumberOfTasks(), vPortFree(), xQueueGenericReceive(), and xQueueGenericSend().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 1814 of file tasks.c.
References pxCurrentTCB, taskSELECT_HIGHEST_PRIORITY_TASK, uxSchedulerSuspended, and xYieldPending.
xTaskCheckForTimeOut()
portBASE_TYPE xTaskCheckForTimeOut (xTimeOutType *const pxTimeOut, portTickType *const pxTicksToWait)
Definition at line 2024 of file tasks.c.
References vTaskSetTimeOutState(), xNumOfOverflows, and xTickCount.
Referenced by xQueueGenericReceive(), and xQueueGenericSend().
xTaskGetTickCount()
portTickType xTaskGetTickCount (void)
Definition at line 1414 of file tasks.c.
References xTickCount.
Referenced by FreeRTOSDelay().
xTaskGetTickCountFromISR()
portTickType xTaskGetTickCountFromISR (void)
Definition at line 1429 of file tasks.c.
References xTickCount.
xTaskIncrementTick()
portBASE_TYPE xTaskIncrementTick (void)
Definition at line 1583 of file tasks.c.
References prvAddTaskToReadyList, pxCurrentTCB, pxDelayedTaskList, pxReadyTasksLists, taskSWITCH_DELAYED_LISTS, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vApplicationTickHook(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, xNextTaskUnblockTime, xTickCount, and xYieldPending.
Referenced by xPortSysTickHandler(), and xTaskResumeAll().
xTaskRemoveFromEventList()
signed portBASE_TYPE xTaskRemoveFromEventList (const xList *const pxEventList)
Definition at line 1961 of file tasks.c.
References prvAddTaskToReadyList, pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, xPendingReadyList, and xYieldPending.
Referenced by prvUnlockQueue(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueIsQueueFullFromISR(), and xQueueReceiveFromISR().
xTaskResumeAll()
signed portBASE_TYPE xTaskResumeAll (void)
Definition at line 1346 of file tasks.c.
References prvAddTaskToReadyList, pxCurrentTCB, uxCurrentNumberOfTasks, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, xPendingReadyList, xTaskIncrementTick(), and xYieldPending.
Referenced by portTASK_FUNCTION(), prvCheckTasksWaitingTermination(), pvPortMalloc(), uxTaskGetNumberOfTasks(), vPortFree(), xQueueGenericReceive(), and xQueueGenericSend().
Variable Documentation
pxCurrentTCB
PRIVILEGED_DATA tskTCB* volatile pxCurrentTCB = NULL
Definition at line 176 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvAllocateTCBAndStack(), vTaskPlaceOnEventList(), vTaskStartScheduler(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
pxDelayedTaskList
PRIVILEGED_DATA xList* volatile pxDelayedTaskList static
Definition at line 182 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), uxTaskGetNumberOfTasks(), and xTaskIncrementTick().
pxOverflowDelayedTaskList
PRIVILEGED_DATA xList* volatile pxOverflowDelayedTaskList static
Definition at line 183 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), and uxTaskGetNumberOfTasks().
pxReadyTasksLists
PRIVILEGED_DATA xList pxReadyTasksLists[configMAX_PRIORITIES] static
Definition at line 179 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAllocateTCBAndStack(), prvInitialiseTaskLists(), uxTaskGetNumberOfTasks(), vTaskSuspendAll(), and xTaskIncrementTick().
uxCurrentNumberOfTasks
PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxCurrentNumberOfTasks = (unsigned portBASE_TYPE) 0U static
Definition at line 206 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAllocateTCBAndStack(), prvCheckTasksWaitingTermination(), uxTaskGetNumberOfTasks(), and xTaskResumeAll().
uxPendedTicks
PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxPendedTicks = (unsigned portBASE_TYPE) 0U static
Definition at line 211 of file tasks.c.
Referenced by xTaskIncrementTick(), and xTaskResumeAll().
uxSchedulerSuspended
PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxSchedulerSuspended = (unsigned portBASE_TYPE) pdFALSE static
Definition at line 210 of file tasks.c.
Referenced by prvAllocateTCBAndStack(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().
uxTaskNumber
PRIVILEGED_DATA unsigned portBASE_TYPE uxTaskNumber = (unsigned portBASE_TYPE) 0U static
Definition at line 214 of file tasks.c.
uxTopReadyPriority
PRIVILEGED_DATA volatile unsigned portBASE_TYPE uxTopReadyPriority = tskIDLE_PRIORITY static
Definition at line 208 of file tasks.c.
Referenced by vTaskPlaceOnEventList().
xDelayedTaskList1
PRIVILEGED_DATA xList xDelayedTaskList1 static
Definition at line 180 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xDelayedTaskList2
PRIVILEGED_DATA xList xDelayedTaskList2 static
Definition at line 181 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xNextTaskUnblockTime
PRIVILEGED_DATA volatile portTickType xNextTaskUnblockTime = portMAX_DELAY static
Definition at line 215 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), uxTaskGetNumberOfTasks(), vTaskSuspendAll(), and xTaskIncrementTick().
xNumOfOverflows
PRIVILEGED_DATA volatile portBASE_TYPE xNumOfOverflows = (portBASE_TYPE) 0 static
Definition at line 213 of file tasks.c.
Referenced by vTaskSetTimeOutState(), and xTaskCheckForTimeOut().
xPendingReadyList
PRIVILEGED_DATA xList xPendingReadyList static
Definition at line 184 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvInitialiseTaskLists(), xTaskRemoveFromEventList(), and xTaskResumeAll().
xSchedulerRunning
PRIVILEGED_DATA volatile signed portBASE_TYPE xSchedulerRunning = pdFALSE static
Definition at line 209 of file tasks.c.
Referenced by prvAllocateTCBAndStack(), vTaskEndScheduler(), and vTaskStartScheduler().
xTickCount
PRIVILEGED_DATA volatile portTickType xTickCount = (portTickType) 0U static
Definition at line 207 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), uxTaskGetNumberOfTasks(), vTaskPlaceOnEventList(), vTaskSetTimeOutState(), vTaskStartScheduler(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskGetTickCountFromISR(), and xTaskIncrementTick().
xYieldPending
PRIVILEGED_DATA volatile portBASE_TYPE xYieldPending = pdFALSE static
Definition at line 212 of file tasks.c.
Referenced by portTASK_FUNCTION(), vTaskMissedYield(), vTaskSwitchContext(), xTaskIncrementTick(), xTaskRemoveFromEventList(), and xTaskResumeAll().