My FreeRTOS Project: freertos/inc/task.h File Reference
task.h File Reference
#include "list.h"
Data Structures
struct xTIME_OUT
struct xMEMORY_REGION
struct xTASK_PARAMTERS
struct xTASK_STATUS
Macros
#define tskKERNEL_VERSION_NUMBER "V7.5.3"
#define tskIDLE_PRIORITY ((unsigned portBASE_TYPE) 0U)
#define taskYIELD() portYIELD()
#define taskENTER_CRITICAL() portENTER_CRITICAL()
#define taskEXIT_CRITICAL() portEXIT_CRITICAL()
#define taskDISABLE_INTERRUPTS() portDISABLE_INTERRUPTS()
#define taskENABLE_INTERRUPTS() portENABLE_INTERRUPTS()
#define taskSCHEDULER_NOT_STARTED ((portBASE_TYPE) 0)
#define taskSCHEDULER_RUNNING ((portBASE_TYPE) 1)
#define taskSCHEDULER_SUSPENDED ((portBASE_TYPE) 2)
#define xTaskCreate(pvTaskCode, pcName, usStackDepth, pvParameters, uxPriority, pxCreatedTask) xTaskGenericCreate((pvTaskCode), (pcName), (usStackDepth), (pvParameters), (uxPriority), (pxCreatedTask), (NULL), (NULL))
#define xTaskCreateRestricted(x, pxCreatedTask) xTaskGenericCreate(((x)->pvTaskCode), ((x)->pcName), ((x)->usStackDepth), ((x)->pvParameters), ((x)->uxPriority), (pxCreatedTask), ((x)->puxStackBuffer), ((x)->xRegions))
Typedefs
typedef void * xTaskHandle
typedef struct xTIME_OUT xTimeOutType
typedef struct xMEMORY_REGION xMemoryRegion
typedef struct xTASK_PARAMTERS xTaskParameters
typedef struct xTASK_STATUS xTaskStatusType
Enumerations
enum eTaskState {
eRunning = 0, eReady, eBlocked, eSuspended,
eDeleted
}
enum eSleepModeStatus { eAbortSleep = 0, eStandardSleep, eNoTasksWaitingTimeout }
Functions
void vTaskAllocateMPURegions (xTaskHandle xTask, const xMemoryRegion *const pxRegions) PRIVILEGED_FUNCTION
void vTaskDelete (xTaskHandle xTaskToDelete) PRIVILEGED_FUNCTION
void vTaskDelay (portTickType xTicksToDelay) PRIVILEGED_FUNCTION
void vTaskDelayUntil (portTickType *const pxPreviousWakeTime, portTickType xTimeIncrement) PRIVILEGED_FUNCTION
unsigned portBASE_TYPE uxTaskPriorityGet (xTaskHandle xTask) PRIVILEGED_FUNCTION
eTaskState eTaskGetState (xTaskHandle xTask) PRIVILEGED_FUNCTION
void vTaskPrioritySet (xTaskHandle xTask, unsigned portBASE_TYPE uxNewPriority) PRIVILEGED_FUNCTION
void vTaskSuspend (xTaskHandle xTaskToSuspend) PRIVILEGED_FUNCTION
void vTaskResume (xTaskHandle xTaskToResume) PRIVILEGED_FUNCTION
portBASE_TYPE xTaskResumeFromISR (xTaskHandle xTaskToResume) PRIVILEGED_FUNCTION
void vTaskStartScheduler (void) PRIVILEGED_FUNCTION
void vTaskEndScheduler (void) PRIVILEGED_FUNCTION
void vTaskSuspendAll (void) PRIVILEGED_FUNCTION
signed portBASE_TYPE xTaskResumeAll (void) PRIVILEGED_FUNCTION
signed portBASE_TYPE xTaskIsTaskSuspended (xTaskHandle xTask) PRIVILEGED_FUNCTION
portTickType xTaskGetTickCount (void) PRIVILEGED_FUNCTION
portTickType xTaskGetTickCountFromISR (void) PRIVILEGED_FUNCTION
unsigned portBASE_TYPE uxTaskGetNumberOfTasks (void) PRIVILEGED_FUNCTION
signed char * pcTaskGetTaskName (xTaskHandle xTaskToQuery)
unsigned portBASE_TYPE uxTaskGetStackHighWaterMark (xTaskHandle xTask) PRIVILEGED_FUNCTION
portBASE_TYPE xTaskCallApplicationTaskHook (xTaskHandle xTask, void *pvParameter) PRIVILEGED_FUNCTION
xTaskHandle xTaskGetIdleTaskHandle (void)
unsigned portBASE_TYPE uxTaskGetSystemState (xTaskStatusType *pxTaskStatusArray, unsigned portBASE_TYPE uxArraySize, unsigned long *pulTotalRunTime)
void vTaskList (signed char *pcWriteBuffer) PRIVILEGED_FUNCTION
void vTaskGetRunTimeStats (signed char *pcWriteBuffer) PRIVILEGED_FUNCTION
portBASE_TYPE xTaskIncrementTick (void) PRIVILEGED_FUNCTION
void vTaskPlaceOnEventList (xList *const pxEventList, portTickType xTicksToWait) PRIVILEGED_FUNCTION
void vTaskPlaceOnEventListRestricted (xList *const pxEventList, portTickType xTicksToWait) PRIVILEGED_FUNCTION
signed portBASE_TYPE xTaskRemoveFromEventList (const xList *const pxEventList) PRIVILEGED_FUNCTION
void vTaskSwitchContext (void) PRIVILEGED_FUNCTION
xTaskHandle xTaskGetCurrentTaskHandle (void) PRIVILEGED_FUNCTION
void vTaskSetTimeOutState (xTimeOutType *const pxTimeOut) PRIVILEGED_FUNCTION
portBASE_TYPE xTaskCheckForTimeOut (xTimeOutType *const pxTimeOut, portTickType *const pxTicksToWait) PRIVILEGED_FUNCTION
void vTaskMissedYield (void) PRIVILEGED_FUNCTION
portBASE_TYPE xTaskGetSchedulerState (void) PRIVILEGED_FUNCTION
void vTaskPriorityInherit (xTaskHandle const pxMutexHolder) PRIVILEGED_FUNCTION
void vTaskPriorityDisinherit (xTaskHandle const pxMutexHolder) PRIVILEGED_FUNCTION
signed portBASE_TYPE xTaskGenericCreate (pdTASK_CODE pxTaskCode, const signed char *const pcName, unsigned short usStackDepth, void *pvParameters, unsigned portBASE_TYPE uxPriority, xTaskHandle *pxCreatedTask, portSTACK_TYPE *puxStackBuffer, const xMemoryRegion *const xRegions) PRIVILEGED_FUNCTION
unsigned portBASE_TYPE uxTaskGetTaskNumber (xTaskHandle xTask)
void vTaskSetTaskNumber (xTaskHandle xTask, unsigned portBASE_TYPE uxHandle)
void vTaskStepTick (portTickType xTicksToJump)
eSleepModeStatus eTaskConfirmSleepModeStatus (void)
Macro Definition Documentation
taskDISABLE_INTERRUPTS
#define taskDISABLE_INTERRUPTS () portDISABLE_INTERRUPTS()
Definition at line 217 of file task.h.
Referenced by vApplicationMallocFailedHook(), and vApplicationStackOverflowHook().
taskENABLE_INTERRUPTS
#define taskENABLE_INTERRUPTS () portENABLE_INTERRUPTS()
Definition at line 227 of file task.h.
taskENTER_CRITICAL
#define taskENTER_CRITICAL () portENTER_CRITICAL()
Definition at line 193 of file task.h.
Referenced by prvCheckTasksWaitingTermination(), prvIsQueueEmpty(), prvIsQueueFull(), prvUnlockQueue(), uxQueueMessagesWaiting(), uxQueueSpacesAvailable(), xQueueGenericCreate(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueIsQueueFullFromISR(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskIncrementTick(), and xTaskResumeAll().
taskEXIT_CRITICAL
#define taskEXIT_CRITICAL () portEXIT_CRITICAL()
Definition at line 207 of file task.h.
Referenced by prvCheckTasksWaitingTermination(), prvIsQueueEmpty(), prvIsQueueFull(), prvUnlockQueue(), uxQueueMessagesWaiting(), uxQueueSpacesAvailable(), xQueueGenericCreate(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueIsQueueFullFromISR(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskIncrementTick(), and xTaskResumeAll().
taskSCHEDULER_NOT_STARTED
#define taskSCHEDULER_NOT_STARTED ((portBASE_TYPE) 0)
Definition at line 230 of file task.h.
Referenced by prvAllocateTCBAndStack().
taskSCHEDULER_RUNNING
#define taskSCHEDULER_RUNNING ((portBASE_TYPE) 1)
Definition at line 231 of file task.h.
Referenced by prvAllocateTCBAndStack().
taskSCHEDULER_SUSPENDED
#define taskSCHEDULER_SUSPENDED ((portBASE_TYPE) 2)
Definition at line 232 of file task.h.
Referenced by prvAllocateTCBAndStack().
taskYIELD
#define taskYIELD () portYIELD()
Definition at line 179 of file task.h.
Referenced by portTASK_FUNCTION().
tskIDLE_PRIORITY
#define tskIDLE_PRIORITY ((unsigned portBASE_TYPE) 0U)
Definition at line 169 of file task.h.
Referenced by CrearTareas(), portTASK_FUNCTION(), uxTaskGetNumberOfTasks(), vTaskStartScheduler(), and vTaskSuspendAll().
tskKERNEL_VERSION_NUMBER
#define tskKERNEL_VERSION_NUMBER "V7.5.3"
Definition at line 84 of file task.h.
xTaskCreate
#define xTaskCreate (pvTaskCode, pcName, usStackDepth, pvParameters, uxPriority, pxCreatedTask) xTaskGenericCreate((pvTaskCode), (pcName), (usStackDepth), (pvParameters), (uxPriority), (pxCreatedTask), (NULL), (NULL))
Definition at line 314 of file task.h.
Referenced by CrearTareas(), and vTaskStartScheduler().
xTaskCreateRestricted
#define xTaskCreateRestricted (x, pxCreatedTask) xTaskGenericCreate(((x)->pvTaskCode), ((x)->pcName), ((x)->usStackDepth), ((x)->pvParameters), ((x)->uxPriority), (pxCreatedTask), ((x)->puxStackBuffer), ((x)->xRegions))
Definition at line 383 of file task.h.
Typedef Documentation
xMemoryRegion
typedef struct xMEMORY_REGION xMemoryRegion
xTaskHandle
typedef void* xTaskHandle
Definition at line 96 of file task.h.
xTaskParameters
typedef struct xTASK_PARAMTERS xTaskParameters
xTaskStatusType
typedef struct xTASK_STATUS xTaskStatusType
xTimeOutType
typedef struct xTIME_OUT xTimeOutType
Enumeration Type Documentation
eSleepModeStatus
enum eSleepModeStatus
Enumerator
eAbortSleep
eStandardSleep
eNoTasksWaitingTimeout
Definition at line 156 of file task.h.
eTaskState
enum eTaskState
Enumerator
eRunning
eReady
eBlocked
eSuspended
eDeleted
Definition at line 99 of file task.h.
Function Documentation
eTaskConfirmSleepModeStatus()
eSleepModeStatus eTaskConfirmSleepModeStatus (void)
Referenced by portTASK_FUNCTION(), and xPortSysTickHandler().
eTaskGetState()
eTaskState eTaskGetState (xTaskHandle xTask)
task. h
eTaskState eTaskGetState(xTaskHandle xTask);
INCLUDE_eTaskGetState must be defined as 1 for this function to be available. See the configuration section for more information.
Obtain the state of any task. States are encoded by the eTaskState enumerated type.
Parameters
xTask Handle of the task to be queried.
Returns
The state of xTask at the time the function was called. Note the state of the task might change between the function being called, and the functions return value being tested by the calling task.
pcTaskGetTaskName()
signed char* pcTaskGetTaskName (xTaskHandle xTaskToQuery)
Referenced by uxTaskGetNumberOfTasks().
uxTaskGetNumberOfTasks()
unsigned portBASE_TYPE uxTaskGetNumberOfTasks (void)
Definition at line 1458 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, eBlocked, eDeleted, eReady, eSuspended, pcTaskGetTaskName(), tskTaskControlBlock::pcTaskName, prvGetTCBFromHandle, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, traceINCREASE_TICK_COUNT, tskIDLE_PRIORITY, uxCurrentNumberOfTasks, uxTaskGetSystemState(), vTaskStepTick(), vTaskSuspendAll(), xNextTaskUnblockTime, xTaskGetIdleTaskHandle(), xTaskResumeAll(), and xTickCount.
uxTaskGetStackHighWaterMark()
unsigned portBASE_TYPE uxTaskGetStackHighWaterMark (xTaskHandle xTask)
task.h
unsigned portBASE_TYPE uxTaskGetStackHighWaterMark(xTaskHandle xTask);
INCLUDE_uxTaskGetStackHighWaterMark must be set to 1 in FreeRTOSConfig.h for this function to be available.
Returns the high water mark of the stack associated with xTask. That is, the minimum free stack space there has been (in words, so on a 32 bit machine a value of 1 means 4 bytes) since the task started. The smaller the returned number the closer the task has come to overflowing its stack.
Parameters
xTask Handle of the task associated with the stack to be checked. Set xTask to NULL to check the stack of the calling task.
Returns
The smallest amount of free stack space there has been (in bytes) since the task referenced by xTask was created.
Referenced by prvAllocateTCBAndStack().
uxTaskGetSystemState()
unsigned portBASE_TYPE uxTaskGetSystemState (xTaskStatusType * pxTaskStatusArray, unsigned portBASE_TYPE uxArraySize, unsigned long * pulTotalRunTime)
configUSE_TRACE_FACILITY must bet defined as 1 in FreeRTOSConfig.h for uxTaskGetSystemState() to be available.
uxTaskGetSystemState() populates an xTaskStatusType structure for each task in the system. xTaskStatusType structures contain, among other things, members for the task handle, task name, task priority, task state, and total amount of run time consumed by the task. See the xTaskStatusType structure definition in this file for the full member list.
NOTE: This function is intended for debugging use only as its use results in the scheduler remaining suspended for an extended period.
Parameters
pxTaskStatusArray A pointer to an array of xTaskStatusType structures. The array must contain at least one xTaskStatusType structure for each task that is under the control of the RTOS. The number of tasks under the control of the RTOS can be determined using the uxTaskGetNumberOfTasks() API function.
uxArraySize The size of the array pointed to by the pxTaskStatusArray parameter. The size is specified as the number of indexes in the array, or the number of xTaskStatusType structures contained in the array, not by the number of bytes in the array.
pulTotalRunTime If configGENERATE_RUN_TIME_STATS is set to 1 in FreeRTOSConfig.h then *pulTotalRunTime is set by uxTaskGetSystemState() to the total run time (as defined by the run time stats clock, see http://www.freertos.org/rtos-run-time-stats.html) since the target booted. pulTotalRunTime can be set to NULL to omit the total run time information.
Returns
The number of xTaskStatusType structures that were populated by uxTaskGetSystemState(). This should equal the number returned by the uxTaskGetNumberOfTasks() API function, but will be zero if the value passed in the uxArraySize parameter was too small.
Example usage:
 // This example demonstrates how a human readable table of run time stats
 // information is generated from raw data provided by uxTaskGetSystemState().
 // The human readable table is written to pcWriteBuffer
 void vTaskGetRunTimeStats( signed char *pcWriteBuffer )
 {
 xTaskStatusType *pxTaskStatusArray;
 volatile unsigned portBASE_TYPE uxArraySize, x;
 unsigned long ulTotalRunTime, ulStatsAsPercentage;
    // Make sure the write buffer does not contain a string.
    *pcWriteBuffer = 0x00;
    // Take a snapshot of the number of tasks in case it changes while this
    // function is executing.
    uxArraySize = uxCurrentNumberOfTasks();
    // Allocate a xTaskStatusType structure for each task.  An array could be
    // allocated statically at compile time.
    pxTaskStatusArray = pvPortMalloc( uxCurrentNumberOfTasks * sizeof( xTaskStatusType ) );
    if( pxTaskStatusArray != NULL )
    {
        // Generate raw status information about each task.
        uxArraySize = uxTaskGetSystemState( pxTaskStatusArray, uxArraySize, &ulTotalRunTime );
        // For percentage calculations.
        ulTotalRunTime /= 100UL;
        // Avoid divide by zero errors.
        if( ulTotalRunTime > 0 )
        {
            // For each populated position in the pxTaskStatusArray array,
            // format the raw data as human readable ASCII data
            for( x = 0; x < uxArraySize; x++ )
            {
                // What percentage of the total run time has the task used?
                // This will always be rounded down to the nearest integer.
                // ulTotalRunTimeDiv100 has already been divided by 100.
                ulStatsAsPercentage = pxTaskStatusArray[ x ].ulRunTimeCounter / ulTotalRunTime;
                if( ulStatsAsPercentage > 0UL )
                {
                    sprintf( ( char * ) pcWriteBuffer, ( char * ) "%s\t\t%lu\t\t%lu%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter, ulStatsAsPercentage );
                }
                else
                {
                    // If the percentage is zero here then the task has
                    // consumed less than 1% of the total run time.
                    sprintf( ( char * ) pcWriteBuffer, ( char * ) "%s\t\t%lu\t\t<1%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter );
                }
                pcWriteBuffer += strlen( ( char * ) pcWriteBuffer );
            }
        }
        // The array is no longer needed, free the memory it consumes.
        vPortFree( pxTaskStatusArray );
    }
 }
Referenced by prvAllocateTCBAndStack(), and uxTaskGetNumberOfTasks().
uxTaskGetTaskNumber()
unsigned portBASE_TYPE uxTaskGetTaskNumber (xTaskHandle xTask)
Referenced by vTaskMissedYield().
uxTaskPriorityGet()
unsigned portBASE_TYPE uxTaskPriorityGet (xTaskHandle xTask)
vTaskAllocateMPURegions()
void vTaskAllocateMPURegions (xTaskHandle xTask, const xMemoryRegion *const pxRegions)
Referenced by prvInitialiseTCBVariables().
vTaskDelay()
void vTaskDelay (portTickType xTicksToDelay)
vTaskDelayUntil()
void vTaskDelayUntil (portTickType *const pxPreviousWakeTime, portTickType xTimeIncrement)
Referenced by FreeRTOSDelay().
vTaskDelete()
void vTaskDelete (xTaskHandle xTaskToDelete)
Referenced by tHallSensor(), tInit(), and tRefreshTimerSetup().
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 1299 of file tasks.c.
References pdFALSE, portDISABLE_INTERRUPTS, vPortEndScheduler(), and xSchedulerRunning.
vTaskGetRunTimeStats()
void vTaskGetRunTimeStats (signed char * pcWriteBuffer)
Referenced by prvAllocateTCBAndStack().
vTaskList()
void vTaskList (signed char * pcWriteBuffer)
Referenced by prvAllocateTCBAndStack().
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 2073 of file tasks.c.
References pdTRUE, uxTaskGetTaskNumber(), vTaskSetTaskNumber(), and xYieldPending.
Referenced by prvUnlockQueue().
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (xList *const pxEventList, portTickType xTicksToWait)
Definition at line 1868 of file tasks.c.
References configASSERT, portMAX_DELAY, portRESET_READY_PRIORITY, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, traceTASK_DELAY_UNTIL, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, vListInsert(), vListInsertEnd(), vTaskPlaceOnEventListRestricted(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, and xTickCount.
Referenced by xQueueGenericReceive(), and xQueueGenericSend().
vTaskPlaceOnEventListRestricted()
void vTaskPlaceOnEventListRestricted (xList *const pxEventList, portTickType xTicksToWait)
Referenced by vTaskPlaceOnEventList(), and xQueueIsQueueFullFromISR().
vTaskPriorityDisinherit()
void vTaskPriorityDisinherit (xTaskHandle const pxMutexHolder)
Referenced by prvAllocateTCBAndStack(), and prvCopyDataToQueue().
vTaskPriorityInherit()
void vTaskPriorityInherit (xTaskHandle const pxMutexHolder)
Referenced by prvAllocateTCBAndStack(), xQueueGenericReceive(), and xQueueGenericSend().
vTaskPrioritySet()
void vTaskPrioritySet (xTaskHandle xTask, unsigned portBASE_TYPE uxNewPriority)
vTaskResume()
void vTaskResume (xTaskHandle xTaskToResume)
vTaskSetTaskNumber()
void vTaskSetTaskNumber (xTaskHandle xTask, unsigned portBASE_TYPE uxHandle)
Referenced by vTaskMissedYield().
vTaskSetTimeOutState()
void vTaskSetTimeOutState (xTimeOutType *const pxTimeOut)
Definition at line 2016 of file tasks.c.
References configASSERT, xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericReceive(), xQueueGenericSend(), and xTaskCheckForTimeOut().
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1225 of file tasks.c.
References configASSERT, pdPASS, pdTRUE, portCONFIGURE_TIMER_FOR_RUN_TIME_STATS, portDISABLE_INTERRUPTS, pxCurrentTCB, tskIDLE_PRIORITY, tskIDLE_STACK_SIZE, xPortStartScheduler(), xSchedulerRunning, xTaskCreate, xTickCount, and xTimerCreateTimerTask().
Referenced by main().
vTaskStepTick()
void vTaskStepTick (portTickType xTicksToJump)
Referenced by uxTaskGetNumberOfTasks(), and xPortSysTickHandler().
vTaskSuspend()
void vTaskSuspend (xTaskHandle xTaskToSuspend)
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 1310 of file tasks.c.
References listCURRENT_LIST_LENGTH, pxCurrentTCB, pxReadyTasksLists, tskIDLE_PRIORITY, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, xNextTaskUnblockTime, and xTickCount.
Referenced by portTASK_FUNCTION(), prvCheckTasksWaitingTermination(), pvPortMalloc(), uxTaskGetNumberOfTasks(), vPortFree(), xQueueGenericReceive(), and xQueueGenericSend().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 1814 of file tasks.c.
References pdFALSE, pdTRUE, pxCurrentTCB, taskFIRST_CHECK_FOR_STACK_OVERFLOW, taskSECOND_CHECK_FOR_STACK_OVERFLOW, taskSELECT_HIGHEST_PRIORITY_TASK, traceTASK_SWITCHED_IN, traceTASK_SWITCHED_OUT, uxSchedulerSuspended, and xYieldPending.
xTaskCallApplicationTaskHook()
portBASE_TYPE xTaskCallApplicationTaskHook (xTaskHandle xTask, void * pvParameter)
task.h
portBASE_TYPE xTaskCallApplicationTaskHook(xTaskHandle xTask, pdTASK_HOOK_CODE pxHookFunction);
Calls the hook function associated with xTask. Passing xTask as NULL has the effect of calling the Running tasks (the calling task) hook function.
pvParameter is passed to the hook function for the task to interpret as it wants.
Referenced by xTaskIncrementTick().
xTaskCheckForTimeOut()
portBASE_TYPE xTaskCheckForTimeOut (xTimeOutType *const pxTimeOut, portTickType *const pxTicksToWait)
Definition at line 2024 of file tasks.c.
References configASSERT, pdFALSE, pdTRUE, portMAX_DELAY, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskSetTimeOutState(), xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericReceive(), and xQueueGenericSend().
xTaskGenericCreate()
signed portBASE_TYPE xTaskGenericCreate (pdTASK_CODE pxTaskCode, const signed char *const pcName, unsigned short usStackDepth, void * pvParameters, unsigned portBASE_TYPE uxPriority, xTaskHandle * pxCreatedTask, portSTACK_TYPE * puxStackBuffer, const xMemoryRegion *const xRegions)
xTaskGetCurrentTaskHandle()
xTaskHandle xTaskGetCurrentTaskHandle (void)
Referenced by prvAllocateTCBAndStack(), xQueueGenericCreate(), xQueueGenericReceive(), and xQueueGenericSend().
xTaskGetIdleTaskHandle()
xTaskHandle xTaskGetIdleTaskHandle (void)
xTaskGetIdleTaskHandle() is only available if INCLUDE_xTaskGetIdleTaskHandle is set to 1 in FreeRTOSConfig.h.
Simply returns the handle of the idle task. It is not valid to call xTaskGetIdleTaskHandle() before the scheduler has been started.
Referenced by uxTaskGetNumberOfTasks().
xTaskGetSchedulerState()
portBASE_TYPE xTaskGetSchedulerState (void)
Referenced by prvAllocateTCBAndStack().
xTaskGetTickCount()
portTickType xTaskGetTickCount (void)
Definition at line 1414 of file tasks.c.
References taskENTER_CRITICAL, taskEXIT_CRITICAL, and xTickCount.
Referenced by FreeRTOSDelay().
xTaskGetTickCountFromISR()
portTickType xTaskGetTickCountFromISR (void)
Definition at line 1429 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTickCount.
xTaskIncrementTick()
portBASE_TYPE xTaskIncrementTick (void)
Definition at line 1583 of file tasks.c.
References listCURRENT_LIST_LENGTH, listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, listLIST_ITEM_CONTAINER, pdFAIL, pdFALSE, pdTRUE, portMAX_DELAY, prvAddTaskToReadyList, pxCurrentTCB, pxDelayedTaskList, pxReadyTasksLists, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSWITCH_DELAYED_LISTS, traceTASK_INCREMENT_TICK, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vApplicationTickHook(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, xNextTaskUnblockTime, xTaskCallApplicationTaskHook(), xTickCount, and xYieldPending.
Referenced by xPortSysTickHandler(), and xTaskResumeAll().
xTaskIsTaskSuspended()
signed portBASE_TYPE xTaskIsTaskSuspended (xTaskHandle xTask)
task. h
signed portBASE_TYPE xTaskIsTaskSuspended(const xTaskHandle xTask);
Utility task that simply returns pdTRUE if the task referenced by xTask is currently in the Suspended state, or pdFALSE if the task referenced by xTask is in any other state.
xTaskRemoveFromEventList()
signed portBASE_TYPE xTaskRemoveFromEventList (const xList *const pxEventList)
Definition at line 1961 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, xPendingReadyList, and xYieldPending.
Referenced by prvUnlockQueue(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueIsQueueFullFromISR(), and xQueueReceiveFromISR().
xTaskResumeAll()
signed portBASE_TYPE xTaskResumeAll (void)
Definition at line 1346 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddTaskToReadyList, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, uxCurrentNumberOfTasks, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xGenericListItem, xPendingReadyList, xTaskIncrementTick(), and xYieldPending.
Referenced by portTASK_FUNCTION(), prvCheckTasksWaitingTermination(), pvPortMalloc(), uxTaskGetNumberOfTasks(), vPortFree(), xQueueGenericReceive(), and xQueueGenericSend().
xTaskResumeFromISR()
portBASE_TYPE xTaskResumeFromISR (xTaskHandle xTaskToResume)