My FreeRTOS Project: Drivers/UART.c File Reference
UART.c File Reference
Funcionalidades de la comunicacion UART.
#include "GPIOLPC1769.h"
#include "Serial.h"
#include "UART.h"
#include "PinoutConfigLPC1769.h"
#include "Bluetooth.h"
Functions
void UART_Init (uint32_t BaudRate)
uint8_t UART_ReceiveByte (void)
void UART_SendByte (uint8_t byte)
void UART0_IRQHandler (void)
Detailed Description
Funcionalidades de la comunicacion UART.
El codigo fuente, asi como el resto del proyecto, se encuentra disponible en su totalidad, libre y gratuito en:
https://github.com/CastroGerman/TD2-Project/
Cualquier consulta, correccion y/o aporte al codigo y al proyecto es bienvenida por mail a: gcast.nosp@m.ro@e.nosp@m.st.fr.nosp@m.ba.u.nosp@m.tn.ed.nosp@m.u.ar
Atentamente: Castro Germán.
Author
Pablo
Date
07-Dic-2018
Definition in file UART.c.
Function Documentation
UART0_IRQHandler()
void UART0_IRQHandler (void)
Definition at line 165 of file UART.c.
References Serial_RxIntHandler(), Serial_TxIntHandler(), and U0IIR.
UART_Init()
void UART_Init (uint32_t BaudRate)
Definition at line 23 of file UART.c.
References ISER0, MYPCONP, PCLKSEL0, RXD0_PIN, SetPINSEL(), TestPointInitBT(), TXD0_PIN, U0DLL, U0DLM, U0FDR, U0IER, and U0LCR.
Referenced by Bluetooth_Init(), and Inicializar().
UART_ReceiveByte()
uint8_t UART_ReceiveByte (void)
Definition at line 155 of file UART.c.
References U0RBR.
Referenced by Serial_RxIntHandler().
UART_SendByte()
void UART_SendByte (uint8_t byte)
Definition at line 160 of file UART.c.
References U0THR.