var searchData=
[
  ['vcoroutineschedule',['vCoRoutineSchedule',['../group__vCoRoutineSchedule.html',1,'']]],
  ['vqueuedelete',['vQueueDelete',['../group__vQueueDelete.html',1,'']]],
  ['vsemaphorecreatebinary',['vSemaphoreCreateBinary',['../group__vSemaphoreCreateBinary.html',1,'']]],
  ['vsemaphorecreatemutex',['vSemaphoreCreateMutex',['../group__vSemaphoreCreateMutex.html',1,'']]],
  ['vsemaphoredelete',['vSemaphoreDelete',['../group__vSemaphoreDelete.html',1,'']]],
  ['vtaskdelay',['vTaskDelay',['../group__vTaskDelay.html',1,'']]],
  ['vtaskdelayuntil',['vTaskDelayUntil',['../group__vTaskDelayUntil.html',1,'']]],
  ['vtaskdelete',['vTaskDelete',['../group__vTaskDelete.html',1,'']]],
  ['vtaskendscheduler',['vTaskEndScheduler',['../group__vTaskEndScheduler.html',1,'']]],
  ['vtaskgetruntimestats',['vTaskGetRunTimeStats',['../group__vTaskGetRunTimeStats.html',1,'']]],
  ['vtasklist',['vTaskList',['../group__vTaskList.html',1,'']]],
  ['vtaskpriorityset',['vTaskPrioritySet',['../group__vTaskPrioritySet.html',1,'']]],
  ['vtaskresume',['vTaskResume',['../group__vTaskResume.html',1,'']]],
  ['vtaskresumefromisr',['vTaskResumeFromISR',['../group__vTaskResumeFromISR.html',1,'']]],
  ['vtaskstartscheduler',['vTaskStartScheduler',['../group__vTaskStartScheduler.html',1,'']]],
  ['vtasksuspend',['vTaskSuspend',['../group__vTaskSuspend.html',1,'']]],
  ['vtasksuspendall',['vTaskSuspendAll',['../group__vTaskSuspendAll.html',1,'']]]
];
