var searchData=
[
  ['xcoroutinecreate',['xCoRoutineCreate',['../group__xCoRoutineCreate.html',1,'']]],
  ['xqueuecreate',['xQueueCreate',['../group__xQueueCreate.html',1,'']]],
  ['xqueueoverwrite',['xQueueOverwrite',['../group__xQueueOverwrite.html',1,'']]],
  ['xqueueoverwritefromisr',['xQueueOverwriteFromISR',['../group__xQueueOverwriteFromISR.html',1,'']]],
  ['xqueuepeekfromisr',['xQueuePeekFromISR',['../group__xQueuePeekFromISR.html',1,'']]],
  ['xqueuereceive',['xQueueReceive',['../group__xQueueReceive.html',1,'']]],
  ['xqueuereceivefromisr',['xQueueReceiveFromISR',['../group__xQueueReceiveFromISR.html',1,'']]],
  ['xqueuesend',['xQueueSend',['../group__xQueueSend.html',1,'']]],
  ['xqueuesendfromisr',['xQueueSendFromISR',['../group__xQueueSendFromISR.html',1,'']]],
  ['xsemaphorecreatecounting',['xSemaphoreCreateCounting',['../group__xSemaphoreCreateCounting.html',1,'']]],
  ['xsemaphoregive',['xSemaphoreGive',['../group__xSemaphoreGive.html',1,'']]],
  ['xsemaphoregivefromisr',['xSemaphoreGiveFromISR',['../group__xSemaphoreGiveFromISR.html',1,'']]],
  ['xsemaphoregiverecursive',['xSemaphoreGiveRecursive',['../group__xSemaphoreGiveRecursive.html',1,'']]],
  ['xsemaphoretake',['xSemaphoreTake',['../group__xSemaphoreTake.html',1,'']]],
  ['xsemaphoretakerecursive',['xSemaphoreTakeRecursive',['../group__xSemaphoreTakeRecursive.html',1,'']]],
  ['xtaskcreate',['xTaskCreate',['../group__xTaskCreate.html',1,'']]],
  ['xtaskcreaterestricted',['xTaskCreateRestricted',['../group__xTaskCreateRestricted.html',1,'']]],
  ['xtaskgettickcount',['xTaskGetTickCount',['../group__xTaskGetTickCount.html',1,'']]],
  ['xtaskhandle',['xTaskHandle',['../group__xTaskHandle.html',1,'']]],
  ['xtaskresumeall',['xTaskResumeAll',['../group__xTaskResumeAll.html',1,'']]]
];
